### ISSUE TITLE
Support for OAuth2 authentication is not clear ?

### ISSUE THREAD

**Issue by nazimkh** [googleapis/nodejs-pubsub#1002]
**How to use this module for following:**

- To sign in behalf of user using OAuth2 access_token & refresh_token.
- Is there a way to override the default authentication type of PubSub client with OAuth2 ?

**Comment by feywind** [comment]
The Pub/Sub library should support the underlying config options from gax/gRPC, so I think it might be a question for them. Let me see if I can find someone who would know.

**Comment by JustinBeckwith** [comment]
Greetings!  Today this library doesn't support user-scoped auth, or a way to override the default auth client.  Generally though, this isn't a problem :) What specifically are you trying to do?

**Comment by feywind** [comment]
This hasn't seen an update in a while so I'm going to go ahead and close it.
