### ISSUE TITLE
Could we add a link to the release notes to the README.md file?  

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#1007]
Could we add a link to the release notes to the README.md file?  There has been a major version number change in the latest release and I'd like to read about what's changed.

**Comment by tbadlov** [comment]
You can review it in the releases section => https://github.com/googleapis/nodejs-pubsub/releases

**Comment by bcoe** [comment]
@tbadlov @npomfret perhaps we could add a link to the CHANGELOG in the README, just to help direct people towards it.

There's a [CHANGELOG maintained here](https://github.com/googleapis/nodejs-pubsub/blob/master/CHANGELOG.md).

**Comment by feywind** [comment]
The super TL;DR version of the 2.0.0 release is:

* No more Node 8 support; you'll need to push up to Node 10 at the minimum for this release
* TypeScript version updates and switching to the TS-based micro-generator for the GAPIC parts; there's one small change in the wording of one of the API methods, but this should largely be a no-op for most
* Dependencies updated

I think in practice, the last point will be the most interesting for people.

There's been a lot of discussion about how to get info about updates out to users, and there hasn't been a solid conclusion yet. How would you all want to hear about this sort of update?

**Comment by feywind** [comment]
There is a fix in synthtool now that should add a link to the CHANGELOG.md from the README.md on all repos.

https://github.com/googleapis/synthtool/pull/701
