### ISSUE TITLE
Google PubSub Import Error

### ISSUE THREAD

**Issue by oaguilar5** [googleapis/nodejs-pubsub#1011]
**Environment details**
OS: Windows
Node.js version: v13.10.1
npm version: 6.13.7
Google Cloud SDK 293.0.0
bq 2.0.57
core 2020.05.15
gsutil 4.50

**Steps to reproduce**
Importing @google-cloud/pubsub results in what looks like a combination of bootstrap and GRPC errors. I have included the stack trace and package.json for reference. The error appears to be an issue from google gax and grpc status codes (undefined). 

stack trace:
[errorStackTrace.txt](https://github.com/googleapis/google-cloud-node/files/4685119/errorStackTrace.txt)

package.json : 
[package.txt](https://github.com/googleapis/google-cloud-node/files/4685120/package.txt)

**Steps I Have Taken That Did Not Fix**
-reinstalled Google Pub Sub through npm
-removed all node-modules, cleared npm cache, and ran npm install
-installed GRPC, attempted to import GRPC and use it to initialize PubSub
-reinstalled Firebase through npm
*deleted package-lock before reinstalling through npm

**Reference**
This issue occurs just by importing PubSub, no initialization of PubSub or actual client-library code written. If I remove the import, my application runs and does not crash. I have attempted to import in two different ways and get the same result:

`const {PubSub} = require('@google-cloud/pubsub');  //from the google docs`
and
`import PubSub from '@google-cloud/pubsub'`

For reference, my application runs on React and heavily uses Firebase for real time data syncing. I am looking to use Google Pub Sub to communicate notifications to the main console of the application, and notifications will be published by many different sub-components throughout the application.

**Comment by qstrahl** [comment]
I've got the same issue with the following npm/node:
```
npm --version
6.14.4

node --version
v10.20.1
```

**Comment by feywind** [comment]
@oaguilar5 @qstrahl Thanks for the report. There are some TypeScript incompatibilities that were introduced when we moved up to the latest minor in Pub/Sub 2.0.0. I wonder if there's something going on there, but I'll try to look at this after fixing that other issue.

**Comment by JustinBeckwith** [comment]
@oaguilar5 just to make this crystal clear - you're trying to run this through webpack and run it in the browser, right?

**Comment by oaguilar5** [comment]
@JustinBeckwith correct, tried both import and require

**Comment by naraB** [comment]
any updates on this?

**Comment by JustinBeckwith** [comment]
Nope

**Comment by feywind** [comment]
I somehow totally missed the browser connection there. After a bit of internal discussion, we don't actually support using this library from a browser, but it's an aspiration. It looks like what's happening here is that it's failing to load protos via gax, which is pretty understandable. (I think they are dynamically require()'d in.) So I'm going to flip this from a question to a feature request for working webpack support.

**Comment by oaguilar5** [comment]
@feywind thank you! This would be fantastic to use on a browser to enable communication of components that are not worthy of being saved to a database (i.e. user field focus on a shared form). At the moment we are blocked on this aspect of our app - may I ask on a ballpark level how feasible this feature request will be to process/implement? (A month, this year, next year, etc) depending on feasibility, we may need to look at alternate solutions but would like to use google pub sub since our app is built entirely within the google engine. Thanks in advance!

**Comment by feywind** [comment]
I haven't dug into it in depth, but I _think_ the dynamic loading issue is in gax. And we may still be referencing gRPC C++ by default, which is not going to work for a browser context. There may be other issues, too, it's just not a tested use case right now.

That `web` label Justin added is for us to track these kinds of requests though, to make a case for spending some time on doing it. I'm afraid someone higher up than me would need to comment on the if/when 😅

**Comment by feywind** [comment]
We were talking this over today and the general consensus is that we just don't want to support direct Pub/Sub usage from a web browser for several reasons (mostly security issues with service keys). The normal recommendation there is just to provide an endpoint (cloud functions or whatnot) that would do the actual publish.

This is tagged `web` though, we'll take a look again if we get to trying to make webpack work on the server side.

**Comment by Andrew-Pynch** [comment]
My main use case is actually for the subscription to published data.

Do you have any recommendations on how to subscribe to a topic from a web client?

For a couple of reasons, we would like to avoid realtime database and firestore document subscriptions.

**Comment by cdelguercio** [comment]
> We were talking this over today and the general consensus is that we just don't want to support direct Pub/Sub usage from a web browser for several reasons (mostly security issues with service keys). The normal recommendation there is just to provide an endpoint (cloud functions or whatnot) that would do the actual publish.
> 
> This is tagged `web` though, we'll take a look again if we get to trying to make webpack work on the server side.

The use case for using pubsub directly is for really large request loads. I currently use this pattern for events where I have 100k+ users sending multiple requests a minute for a short period of time. For my use case, I don't care about security either.

**Comment by feywind** [comment]
@kamalaboulhosn Did I ping you about this one yet? There's more interest about using Pub/Sub directly from browsers.

I think the last reason I heard that we don't really want to do this is that the service side isn't optimized to scale for many clients (in addition to any security concerns). There's an assumption that you'll have long-running clients with long-running HTTP/2 connections and just stream data like that. In that situation you'd use a web service to proxy to Pub/Sub, since those are more strongly optimized for that use case.

Certainly this kind of feedback is useful though. It's not always great to have to funnel all your data through a web server or cloud function.

**Comment by kamalaboulhosn** [comment]
Subscribing from browsers is really going to be tough for a lot of reasons, even if one isn't worried about security. When would subscriptions be created? A subscriber is not going to have access to the data published before the subscription was created? How do the subscriptions get deleted? Is it by the browser? What if the session terminates before the subscription is deleted? Is it going to just use expiration of subscriptions? Could their be enough users over the minimum expiration period such that the 10,000 subscriptions per topic limit could be exceeded? So subscribing via the web browser is going to be fraught with issues and I think is a good reason to not support it.

Publish is less worrisome as there is no limit on the number of publisher clients. @cdelguercio is your case one for publishing or for subscribing?

**Comment by cdelguercio** [comment]
@kamalaboulhosn publishing.

Also, I've already hacked the library and completed a project using unauthenticated browser pubsub and it worked great. As long as you're okay with and understand the security consequences, there are plenty of use cases where this can work.

**Comment by feywind** [comment]
We discussed this at a team meeting, and the more or less definitive answer is:

As we consider Pub/Sub outside the context of torrents and more trickle based use cases, this may be something we will revisit but this is not a language specific consideration and is more of a product consideration.

In other words, it's not so much that JS working in the browser or not is the issue, it's the use case of large numbers of (potentially unauthenticated) publishers from outside end users. (Or subscribers, though you'd need authentication and such for that anyway.) So we can probably make this library work in the browser eventually, but it's not high on the priority list, because it mostly enables that usage.

@kamalaboulhosn Did I mostly sum that up properly?

**Comment by tejohnso** [comment]
>  it's not so much that JS working in the browser or not is the issue, it's the use case of large numbers of (potentially unauthenticated) publishers from outside end users

>  this may be something we will revisit but this is not a language specific consideration and is more of a product consideration.

The [main product page](https://cloud.google.com/pubsub) use case for Stream Analytics shows exactly that scenario. Large number of unauthenticated publishes from outside users. At least, that's what I gather from the "mobile" and "web" boxes flowing directly into the Pub/Sub box. Also judging by Pub/Sub's quota and architecture. Perhaps the authentication status isn't implied, but authentication could be added if that's the concern. 

Can someone confirm whether @cdelguercio is using the product in an unintended manner?
Could we also get confirmation about whether it is ill advised to use this particular library in that way?

![use-case](https://user-images.githubusercontent.com/1511535/212405301-f3782d91-399e-492f-9a0a-bfa22503a132.png)
