### ISSUE TITLE
Expose Prometheus metrics to track numPendingRequests and numInFlightRequests

### ISSUE THREAD

**Issue by koalaty-code** [googleapis/nodejs-pubsub#1034]
**Is your feature request related to a problem? Please describe.**
It is difficult to gain insight into the number of messages currently being processed by a subscriber client. This has led to difficulty when trying to fine-tune flow control settings.

 **Describe the solution you'd like**
Expose Prometheus metrics that can be scraped from the application to track the number of numPendingRequests and numInFlightRequests. We could add further cardinality with labels for which stage each message is at in the pipeline; `ack`, `mockAck`, etc.

 **Describe alternatives you've considered**
I am not aware of any alternatives to gain this level of observability in a subscriber client. Please advise if alternatives are already present.

**Comment by feywind** [comment]
Thanks for the request! I'm not completely sure off the top of my head, but I'll bring it up to see what we can do.

**Comment by feywind** [comment]
We're moving this over to a more global request for consistent OpenTelemetry support across languages. That's being tracked over here: https://issuetracker.google.com/issues/183608476

For now, once the OT 0.18+ PR is merged, we'll be recommending this for Prometheus: https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-exporter-prometheus
