### ISSUE TITLE
Require error codes returned by the response

### ISSUE THREAD

**Issue by ibmappcon** [googleapis/nodejs-pubsub#1039]
Hi,

We are using nodejs-pubsub package for one of our connector and to handle errors we are supposed to map error.code to proper http status code.
Currently in the documentation we cannot find all the possible error codes available in this package.

Could you please give us all the error codes returning from different errors and if possible the mappings with http code?

**Comment by feywind** [comment]
There have been some discussions about making the samples and/or docs more clearly outline what sorts of things you could get back from the API calls. I don't think there's a concerted effort yet, but it's something I want to see too.

**Comment by feywind** [comment]
There was a discussion not long ago specifically about grpc vs http error codes. This might fall under that, so I've pinged people to see if there's something we can do here.

**Comment by feywind** [comment]
@ibmappcon I was given this link, maybe it'll help? https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/constants.ts#L18

**Comment by feywind** [comment]
You can also do this, apparently:

```
> const grpc = require('@grpc/grpc-js')
undefined
> grpc.status
{
  '0': 'OK',
  '1': 'CANCELLED',
  '2': 'UNKNOWN',
...
```

...which still isn't great, but it seems like at some point we might just directly add something to convert from gRPC codes to HTTP codes.
