### ISSUE TITLE
createSubscription("topic-name", ...).topic is undefined

### ISSUE THREAD

**Issue by psilospore** [googleapis/nodejs-pubsub#1046]
However `createSubscription("topic-name", ...).metadata.topic` contains the topic name

#### Environment details

Seen in the firebase emulator thing.

  - OS: Mac
  - Node.js version: v12.15.0
  - npm version: 6.13.4
  - `@google-cloud/pubsub` version: 2.1.0

#### Steps to reproduce

```
const sub = createSubscription("topicname", "subscriptionName", {
        pushEndpoint: `subscriber.com/api/mushroomFacts`,
})
sub.topic //undefined
sub.metadata.topic // projects/local-emulator/topics/topicname
```

**Comment by feywind** [comment]
@psilospore Thanks for the report! I _think_ maybe `sub.topic` is intended to be private, but I will look at it more in a bit.

**Comment by psilospore** [comment]
No problem!

**Comment by stephenplusplus** [comment]
The `metadata` object that's on our "ServiceObject" classes (such as a Topic or Subscription) is meant to be publicly accessible and reserved for data that comes from the API (not manipulated by us). The properties directly on the instance are sometimes leaked and useful, but not generally guaranteed to be reliably accessed by users.

**Comment by feywind** [comment]
@psilospore It looks like what the library is doing is copying Subscription.topic from the options passed into the Subscription constructor. You might be able to do that manually, but it looks like the intent is that you'd obtain the Subscription object by way of a Topic object. e.g.:

```
    if (!this.topic) {
      throw new Error(
        'Subscriptions can only be created when accessed through Topics'
      );
    }
```

So the answer for how it's written now is that you'd need to do something like:

```
pubsub.topic('foo').subscription('bar')
```

and you should get a Subscription with a valid `topic` member.

On the other hand, if that _is_ happening and `topic` is undefined, that might be a bug in the library.

If you want to retrieve the topic name from a standalone Subscription object, you might also try `getMetadata()` on it. It looks like we don't do that by default though.

**Comment by feywind** [comment]
Just checking in on this to see if anything else is needed here since it's been a while.

**Comment by psilospore** [comment]
Sorry for getting back late. I did find another workaround to get the topic name when I reported this but thought it was a bug that might be worth reporting. Based on the previous comments it seems that it is a bug, but feel free to close this if you would like.

**Comment by stephenplusplus** [comment]
@psilospore Thanks, good to hear. I'll close for now and let @feywind determine if there's a bug we need to address.
