### ISSUE TITLE
Documented ackDeadline configuration does not work

### ISSUE THREAD

**Issue by toots** [googleapis/nodejs-pubsub#105]
Hi,

I'm testing the code documented at: https://cloud.google.com/nodejs/docs/reference/pubsub/0.16.x/Topic#createSubscription

Here's my test code:
```
var PubSub = require('@google-cloud/pubsub');
var pubsub = new PubSub({projectId:  <...>});

var topic = pubsub.topic('test-topic');
var callback = function(err, subscription, apiResponse) {
  console.log("done",err);
};

// With options.
topic.createSubscription('newMessages', {
  ackDeadline: 90000 // 90 seconds
}, callback);
```

Once executed, I can see the new subscription but its `ackDealine` is `10` seconds.

**Comment by callmehiphop** [comment]
Looks like some stale documentation. The [example](https://github.com/googleapis/nodejs-pubsub/blob/master/src/topic.js#L180) has since been fixed. You should be able to set the deadline like so

```js
topic.createSubscription('newMessages', {
  ackDeadlineSeconds: 90
}, callback);
```

**Comment by toots** [comment]
If I run this code:
```
var PubSub = require('@google-cloud/pubsub');
var pubsub = new PubSub({projectId:  <...>});

var topic = pubsub.topic('test-topic');
var callback = function(err, subscription, apiResponse) {
  console.log("done",err);
};

// With options.
topic.createSubscription('newMessages', {
  ackDeadline: 90 // 90 seconds
}, callback);
```
I still see the subscription being created with a 10 sec ack deadline:
<img width="1014" alt="screenshot 2018-03-27 10 46 58" src="https://user-images.githubusercontent.com/871060/37978905-c85b87aa-31ac-11e8-9a72-688f6f55e7f5.png">

**Comment by toots** [comment]
Okay, my bad, version bump and `ackDeadlineSeconds` does indeed fix it.

**Comment by callmehiphop** [comment]
@toots no worries! Sorry about the documentation bug
