### ISSUE TITLE
Keep receiving messages while processing 

### ISSUE THREAD

**Issue by toots** [googleapis/nodejs-pubsub#106]
There does not seem to be a way to receive multiple messages in a subscription handler while processing one. If one doesn't `ack` or `nack` the last message then no more are delivered but in a reasonable use case, one should be able to process `n` messages according to the scaling capacities of the processing system and then start `nack`ing following messages while the first `n` messages are being processed.

**Comment by toots** [comment]
Code example:
```
var subscription = (..subscription with a 5 min ack deadline..);

var maxProcessing = 5;
var processing = 0;

function onMessage(message) {
  if (processing < maxProcessing) {
    processing = processing + 1;
    (..process message..)
    message.ack();
  } else {
    message.nack();
  }
}
subscription.on('message', onMessage);
```
This will result in handling only one message at a time, which isn't what was expected.

**Comment by toots** [comment]
This use-case should be possible according to the underlying API so this appears to be a limitation of the node client itself. The objective is to assure implicit message re-queueing for cases where e.g. the processing system has crashed or has been terminated while processing messages, which does happen in auto-scaled distributed systems.

**Comment by toots** [comment]
Just to make the use-case more clear. The Google cloud platform has auto-scaling capabilities based  on a number of messages pending in a pubsub queue. Without the functionalities above, if last instance `x` starts processing the last `n` messages in the queue but has to acknowledge them right way, this instance may get scaled down while processing its messages, rendering this scaling method useless.

**Comment by callmehiphop** [comment]
@toots you should be able to process as many messages as you like. You can specify the max number of messages to be processed at a given time by setting the flow control options. Only if you hit the `maxMessages` value should you see the behaviour you are describing.

```js
const subscription = topic.subscription('my-sub', {
  flowControl: {maxMessages: 5}
});
```

I attempted to run your code (although my ack deadline was only 10 seconds) and I did not encounter the issue you are describing. If possible could you put together a more complete example on how to replicate your issue?

**Comment by toots** [comment]
Yes, this works. I misunderstood the API. Thanks for your response.
