### ISSUE TITLE
Add OpenTelemetry Support

### ISSUE THREAD

**Issue by sethmaxwl** [googleapis/nodejs-pubsub#1061]
OpenTelemetry should be added to PubSub to provide OpenTracing and OpenCensus functionality as one API and SDK. It would be helpful to use it to trace a message throughout its life cycle. This is being added to the Python Pub/Sub client and would be useful to have in the node client as well.

https://github.com/googleapis/python-pubsub/pull/149

**Comment by feywind** [comment]
@sethmaxwl You're working on this, right? Just trying to get it assigned to the right person.

**Comment by sethmaxwl** [comment]
@feywind Yes I am.

**Comment by thespacedeck** [comment]
I cannot wait for this feature :) Thanks for working on this! It would be great to even pass through your own custom HTTP headers, from where you can set the traceparent property in order to propgate it manually. We're currently doing this with Cloud Tasks and it works great.

**Comment by CyberHippo** [comment]
Hi, 

Thanks for all the good work on supporting OpenTelemetry!

Is the tracing limited to the use of `BasicTracerProvider` and `ConsoleSpanExporter` or is it compatible with other tracers/exporters such as the [`NodeTracerProvider`](https://www.npmjs.com/package/@opentelemetry/node) tracer or the [`CollectorTraceExporter`](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-exporter-collector) exporter ?
