### ISSUE TITLE
GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found

### ISSUE THREAD

**Issue by Nyceane** [googleapis/nodejs-pubsub#1076]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

$ npm install @google-cloud/pubsub
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/pubsub@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

Getting this from log```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/nyceane/.nvm/versions/node/v13.11.0/bin/node',
1 verbose cli   '/home/nyceane/.nvm/versions/node/v13.11.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@google-cloud/pubsub'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v13.11.0
4 verbose npm-session bfa0337a64e4515e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@google-cloud%2fpubsub 57ms
8 http fetch GET 404 https://registry.npmjs.org/@google-cloud%2fpubsub 33ms
9 silly fetchPackageMetaData error for @google-cloud/pubsub@latest 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 111ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found
12 verbose stack     at /home/nyceane/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid @google-cloud/pubsub@latest
15 verbose cwd /home/nyceane/workspace/MixPose-Web
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/home/nyceane/.nvm/versions/node/v13.11.0/bin/node" "/home/nyceane/.nvm/versions/node/v13.11.0/bin/npm" "install" "@google-cloud/pubsub"
18 verbose node v13.11.0
19 verbose npm  v6.14.7
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@google-cloud%2fpubsub - Not found
22 error 404
23 error 404 '@google-cloud/pubsub@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

```

**Comment by chintansureliya** [comment]
Happening with most of the google cloud packages.

**Comment by damingerdai** [comment]
i also meet this issue when i want to install  firebase-tools by npm

**Comment by zhigang1992** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5

it's a npm issue with scope packages

**Comment by stephenplusplus** [comment]
Looks like it has all been resolved. Phew!
