### ISSUE TITLE
Synchronous Pull times out consistently with PubSub Emulator

### ISSUE THREAD

**Issue by sdcaulley** [googleapis/nodejs-pubsub#1088]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue?
Yes

2) Did someone already solve this?
 I have no found no similar issues.

3) Do you have a support contract?
No.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Debian 10
  - Node.js version: 12.18.2
  - npm version: 6.14.5
  - `@google-cloud/pubsub` version: 2.2.0

#### Steps to reproduce

 I have created a Pubsub client and am testing it against the Pubsub emulator.  My code currently is 
```
const { PubSub, v1 } = require('@google-cloud/pubsub');
const config = require('../config.js');
const pubsubClient = new PubSub({
  apiEndpoint: config.pubsub_url,
  projectId: config.project_id
});
const subClient = new v1.SubscriberClient({
  apiEndpoint: pubsubClient.options.apiEndpoint,
  port: pubsubClient.options.port,
  sslCreds: pubsubClient.options.sslCreds
});

async function pullMessages(subscriptionName) {
    const formattedSubscription = subClient.subscriptionPath(
      config.project_id,
      subscriptionName
    );

    const request = {
      subscription: formattedSubscription,
      returnImmediately: true,
      maxMessages: 10
    };

    const [response] = await subClient.pull(request);

    return response;
  }
```
When run, it just spins until a timeout is hit.

**Comment by feywind** [comment]
@sdcaulley Thanks for the report! I was going to say something about the v1 client not finding the emulator variables, but then I see that you've got that taken care of. :) I'll try to look at this in with some other emulator issues.

**Comment by hugorodrigues** [comment]
Same issue here! @sdcaulley did you found any workaround?

**Comment by hugorodrigues** [comment]
@sdcaulley This is working for me:

```js
import { PubSub, v1 } from "@google-cloud/pubsub";

const pubsubClient = new PubSub();
const subClient = new v1.SubscriberClient(pubsubClient.options);

async function pullMessages(subscriptionName) {
  const formattedSubscription = subClient.subscriptionPath(
    pubsubClient.options.projectId,
    subscriptionName
  );

  const request = {
    subscription: formattedSubscription,
    returnImmediately: true,
    maxMessages: 10,
  };

  const [response] = await subClient.pull(request);

  return response;
}
```
🥳

**Comment by feywind** [comment]
@hugorodrigues Thanks for that. It looks like the difference is in how the apiEndpoint and such are passed. Your workaround should be fine for now, but I'm going to roll this into the feature request for a more straightforward way to pass the options from `PubSub` into the `v1` GAPIC clients.

https://github.com/googleapis/nodejs-pubsub/issues/1091
