### ISSUE TITLE
Add formal support for propagating endpoint info from environment variables

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1091]
This is related to this issue: https://github.com/googleapis/nodejs-pubsub/issues/869

Right now, only the high level `PubSub` object is capable of doing things like parsing the emulator endpoint environment variables. This causes problems when testing with a raw v1 client, for synchronous pull or the like.

There is a workaround for this (posted in that issue above) but I can't say I like it as a long term solution. There needs to be something well-defined, like a helper class that's used by `PubSub` and available to users, that can consistently parse that info.

**Comment by stephenplusplus** [comment]
Instead of:

```js
const pubsub = new PubSub();
const rawSubscriberClient = new v1.SubscriberClient();
```

What if we tried exposing the raw clients through the PubSub instance:

```js
const pubsub = new PubSub();
const rawSubscriberClient = new pubsub.v1.SubscriberClient();
```

That way, it's easy for us to forward any settings that are relevant, such as auth settings, endpoint configuration, and maybe even others, like low-level gRPC options.

**Comment by feywind** [comment]
Yeah, interesting idea! I like the consistency that makes where the `PubSub` object is the one-stop shop for using the library.

**Comment by feywind** [comment]
https://github.com/googleapis/nodejs-pubsub/issues/1220 fixed this by adding the `PubSub#getClientConfig` method. You can await on that method to get a config that can be passed to the v1 constructors.
