### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined (line 45)

### ISSUE THREAD

**Issue by shubhamgupta-me** [googleapis/nodejs-pubsub#1113]
function getSFReportfromGmail(){

    var threads = GmailApp.search('Report results (All Accounts with Integration Fields) has:attachment newer_than:1d');

    var messages = threads[0].getMessages();
    var attach = messages[0].getAttachments();
    var timestamp = messages[0].getDate();
    
    for (var i = 0; i < attach.length; ++i) {
    
      var data = attach[i].copyBlob();
      var name = data.getName();
      
      var result = name.indexOf('All.csv');
   //   if (name == 'Search: Active Customers Integration Prep - EB - Copy.csv') {
      if (name.indexOf('All.csv')>-1) {
    //  var csvData = Utilities.parseCsv(data.getDataAsString(), ",");
          var csvData = Utilities.parseCsv(data.getDataAsString());
      } //end if
    
    } //end for
    
    
    return csvData;

}

// we get the gmail attachment of OA data and below code is writing Gmail attachment into SF-OA Comparison sheet
function updateNSSheet(){

    //Get OA Export Sheet
    var ss = SpreadsheetApp.getActive();
    var SFSheet = ss.getSheetByName('Sheet12');
    
    var SFData = getSFReportfromGmail();
     
     

//Write results to the OA Sheet
    var lastRow = SFSheet.getLastRow();
    Logger.log(lastRow);
    if (lastRow < 1) lastRow = 1;
    SFSheet.getRange(1,1,lastRow).clearContent();
    SFSheet.getRange(1,1,SFData.length,SFData[0].length).setValue(SFData);
    //OASheet.getRange(1,1).clearContent();
   // OASheet.deleteRow(1);
    
  }

**Comment by shubhamgupta-me** [comment]
I got a type error while running the above script, i was trying to get the CSV email attachment into an google sheet

**Comment by feywind** [comment]
I think this might've gotten directed to the wrong GitHub repo, but let me see if I can find someone to grab it.

**Comment by grant** [comment]
The code provided above is Apps Script, not Node.

Perhaps ask the question in this repo? https://github.com/gsuitedevs/apps-script-samples

We have a bunch of samples there.

---

I'm guessing that the `TypeError` provided is produced with the expression `SFData[0].length`, which is caused when the emails' first thread's attached Spreadsheet is empty.

**Comment by feywind** [comment]
I'm going to go ahead and close this, feel free to re-open if needed.
