### ISSUE TITLE
Better example in the Readme.md

### ISSUE THREAD

**Issue by fotoflo** [googleapis/nodejs-pubsub#1117]
Hello! 
 The current quickstart example is great but it would be so much better if you could see a full workflow
1.  instantiate a client
2. create a topic
3. publish a message
4. create a subscription to that topic
5. receive the message (pull or push, whatever's easier)

I think doing this wouldnt increase the documentation by more than a few lines, however it woudl reduce a lot of confusion and solve developer problems earlier than forcing them to crawl through the whole documentation,

Thank you!

```
Using the client library
// Imports the Google Cloud client library
const {PubSub} = require('@google-cloud/pubsub');

async function quickstart(
  projectId = 'your-project-id', // Your Google Cloud Platform project ID
  topicName = 'my-topic' // Name for the new topic to create
) {
  // Instantiates a client
  const pubsub = new PubSub({projectId});

  // Creates the new topic
  const [topic] = await pubsub.createTopic(topicName);
  console.log(`Topic ${topic.name} created.`);
}
```

**Comment by feywind** [comment]
Hmm, yeah, I have to agree that it's a bit lackluster. I mean, it would help you get your packages set up and such, but it's not a very good example of a simple workflow. Thanks for the note!

**Comment by feywind** [comment]
We're doing sample updates/audits right now anyway, so I went ahead and improved the quickstart as part of that too.
