### ISSUE TITLE
Consider making .publish() able to convert to a Buffer automatically

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1127]
This is in reference to this code review: https://github.com/googleapis/nodejs-pubsub/pull/1119#discussion_r501427286

Basically it seems a bit sad that the user has to `Buffer.from` on every `publish()` if it's not already a `Buffer`. I'm capturing this suggestion here for future consideration. Feel free to add a reaction if you'd like this.

**Comment by stephenplusplus** [comment]
@feywind are you able to see this or request access? https://docs.google.com/document/d/12QHQnF7ThXcNnFTOyQgsmygAYk8QiWvPjUfoYs_kKng. It’s from 2017, when this functionality was removed. I asked for an explanation of why the P/S team wanted this removed in a closed thread, which maybe could be re-examined from today’s perspective.

**Comment by feywind** [comment]
Oh, interesting. Thanks for the link. @JustinBeckwith here's some more info about it's the way it is?

**Comment by JustinBeckwith** [comment]
Removing it was a bad idea then, and remains a bad idea today (sorry if whoever made this call is on the thread).  Maybe we could revisit?

**Comment by stephenplusplus** [comment]
Is there a member of the P/S team we could tag here? 

This is the direct link to the convo: https://docs.google.com/document/d/12QHQnF7ThXcNnFTOyQgsmygAYk8QiWvPjUfoYs_kKng/edit?disco=AAAABEGnPOE

**Comment by feywind** [comment]
I'm closing this out since it hasn't seen any traction lately. Feel free to reopen later if we have the conversation about the whys and wherefors.
