### ISSUE TITLE
Different data incoming into local pubsub function

### ISSUE THREAD

**Issue by vongohren** [googleapis/nodejs-pubsub#1144]
So here is a list of pictures with explanatory text to it. My plea is in the bottom :D 

These three images explains the issue and outcome of what I struggle with understanding why is happening. Using the same local pubsub emulator, with two different methods of sending, results in different outcome.
<img width="430" alt="Screenshot 2020-10-29 at 16 52 03" src="https://user-images.githubusercontent.com/1012055/97598497-551d2a00-1a07-11eb-85eb-8d466499ca92.png">
<img width="646" alt="Screenshot 2020-10-29 at 16 50 29" src="https://user-images.githubusercontent.com/1012055/97598483-5189a300-1a07-11eb-9635-7011b552211c.png">
<img width="613" alt="Screenshot 2020-10-29 at 16 50 56" src="https://user-images.githubusercontent.com/1012055/97598488-53536680-1a07-11eb-868c-0dd17c7d3d4e.png">

The one that I think is proper also outputs this line as the context: <img width="571" alt="Screenshot 2020-10-29 at 16 51 32" src="https://user-images.githubusercontent.com/1012055/97598494-551d2a00-1a07-11eb-9058-a8e1b951f941.png">

The attempt that gives the proper result looks like this, directly copy paste from here: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/events.md
<img width="734" alt="Screenshot 2020-10-29 at 16 51 24" src="https://user-images.githubusercontent.com/1012055/97598493-54849380-1a07-11eb-94ad-dcfc3ba304f1.png">

The effort that results in the wrong result is through code and this is the following code.

```
const publish = async (topicName, data) => {
  try {
    const messageId = uuid();
    const customAttributes = {
      messageId,
    };
    const payload = Buffer.from(JSON.stringify(data));
    const topic = await getTopic(topicName);
    const pubsubMessageId = await topic.publish(payload, customAttributes);
    logger.info(`Message ${pubsubMessageId} published. Unique payload ID: ${messageId}`);
  } catch (err) {
    logger.error(err.message, { status: err.status, err: err, stack: err.stack, });
    throw err;
  }
};

const getTopic = async (name) => {
  try {
    const [ topic, ] = await pubsub.createTopic(name);
    return topic;
  } catch (err) {
    if (err.code === ErrorCodes.AlreadyExists) {
      return pubsub.topic(name);
    }
    throw err;
  }
};
```

# So my plea
What are the reasons this might happen, I cannot try to think that one way or the other the first variable can be undefined, so just wondering what is wrong

**Comment by feywind** [comment]
@vongohren I'll take a look at this in a bit and get back to you!

Completely unrelated: what's that font you're using in your terminal? That's really nice! :)

**Comment by vongohren** [comment]
@feywind that is great :D 
Yeah good question, I think its the default one coming with my theme: https://github.com/vongohren/.dotfiles/blob/master/.zshrc
Which is:
https://github.com/Powerlevel9k/powerlevel9k

**Comment by vongohren** [comment]
@feywind did you get to look at this? I cannot really deploy this uncertain what is the right variable to use :P

**Comment by feywind** [comment]
@vongohren Sorry for dropping this, it's hard not to miss notifications with 100s of repos. 😱 Excuses aside, I finally did look at this today, and I do see the same problem. I think this isn't an issue with the Pub/Sub client library, though. It seems to be some sort of mismatch between the expectations of the Functions framework and the Pub/Sub push callback. Let me see if I can find someone who would know where to look.

**Comment by vongohren** [comment]
@feywind hehe thanks for taking a look! I have been able to work around it, but it is not optimal :P So would be great to have a look at what shall be what

**Comment by feywind** [comment]
Looks like it's something that was recently fixed in the functions framework: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/272

**Comment by vongohren** [comment]
@feywind great! Then I pressume we can close this? I have not tested but trust the response :D

**Comment by feywind** [comment]
Yep! The other day when I wrote that comment, the new functions framework hadn't been released on npm, but it's in the pipeline.
