### ISSUE TITLE
[protobufjs] Error Cannot read property 'emptyArray' of undefined with rollup

### ISSUE THREAD

**Issue by vicb** [googleapis/nodejs-pubsub#1151]
This project has a dependency on [protobufjs](https://github.com/protobufjs/protobuf.js)

[protobufjs](https://github.com/protobufjs/protobuf.js) has a known issue with rollup: https://github.com/rollup/rollup/issues/2747

Which means that projects using rollups might have build errors when using nodejs-pubsub.

I am creating this issue for 2 purposes:
- To make it easier to debug the `Cannot read property 'emptyArray' of undefined with rollup` when it is generated,
- To suggest to switch with other proto alternatives. I have been using [protobuf-ts](https://github.com/timostamm/protobuf-ts) that generates type safe typescript code and look more robust that protobufjs.

Ref: https://github.com/protobufjs/protobuf.js/issues/1503

**Comment by vicb** [comment]
I have worked around the issue by not bundling the `@google-cloud` lib when using rollup, i.e.

```js
export default [
  {
    input: 'src/index.ts',

    // ...

    external: [/@google-cloud/],
  },
```

Maybe this issue should be closed now ? 
Hopefully it could still help some people.

**Comment by meredithslota** [comment]
Thanks for the report! Let's leave it open for now while we figure out the best path forward.

**Comment by feywind** [comment]
@vicb Thanks for the report! The question of the protobuf implementation is an ongoing topic of debate, as I think we might've actually taken over maintenance of that project not too long ago.

@alexander-fenster Sorry to rope you in on another one :D but maybe you have some comments on this?

@JustinBeckwith Does this fall under the webpack tag umbrella?

**Comment by JustinBeckwith** [comment]
@feywind generally if folks are using rollup, it's in pursuit of web (but not always).  @vicb are you trying to run this module in a  browser by chance?

**Comment by vicb** [comment]
@JustinBeckwith I am using this module on the server side (Google NodeJS app engine).

I use rollup to bundle all the dependencies (npm modules) and produce a standalone JS file to be executed on App Engine.

App Engine has a limitation of not being to deploy [more than 10000 files](https://stackoverflow.com/questions/42451607/gcloud-app-deploy-this-deployment-has-too-many-files) for a new version. Without creating a standalone JS bundle the limit is easy to reach as it is not unusual for a `node_modules` to reach that many file even for mid-size projects.

More context:

My project was working until at some point I got this errors (`Cannot read property 'emptyArray' of undefined with rollup
`). I am not sure of the root cause. It might be related to code changes on my side ? to updating nodejs-pubsub ? to updating [googleapis/nodejs-datastore](https://github.com/googleapis/nodejs-datastore) ?

Anyway I was able to track down the error to a circular dependency in protobuf-js so I created issues here and on [grpc/grpc-node](https://github.com/grpc/grpc-node/issues/1623) that both have a dependency on protobufjs.

I had used protobufjs before but switched to [protobuf-ts](https://github.com/timostamm/protobuf-ts) when I discovered that projet because the code looks more robust to me and protobufjs has a lot of opened issues on github.

I mainly created this issue to save other devs time trying to debug this obscure `Cannot read property 'emptyArray' of undefined with rollup` error.

I also mentioned [protobuf-ts](https://github.com/timostamm/protobuf-ts) because I like this project better but I understand it might not be easy to migrate to it.

**Comment by feywind** [comment]
So, acknowledging that this is a non-web use (and one that's probably useful to others too), we've been using the `web` tag for keeping track of users who want to use tools like rollup/webpack/etc... I'm going to switch this over to that category for the moment.

Let us know if you get anything useful on the rollup side? Thanks!

**Comment by vicb** [comment]
@feywind it seems like rollup is working on fixing this in https://github.com/rollup/plugins/pull/658

I'll update here when I have more info.
