### ISSUE TITLE
Allow passing partial config options into gapic methods

### ISSUE THREAD

**Issue by sdineshwaran** [googleapis/nodejs-pubsub#1168]
I've setup publishWithRetrySettings feature in one of my projects and been trying to validate whether the retrySettings is working fine, but I'm unable to check whether its working as expected.

I used the following code to publish the message. 

```
....
....
publisherClient.publish(
        request,
        {
          retry: {
            backoffSettings: {
              initialRetryDelayMillis: 200,
              initialRpcTimeoutMillis: 5000,
              maxRetryDelayMillis: 20000,
              maxRpcTimeoutMillis: 50000,
              retryDelayMultiplier: 1.3,
              rpcTimeoutMultiplier: 1,
              totalTimeoutMillis: 240000,
            },
            retryCodes: [
              10, // 'ABORTED'
              1, // 'CANCELLED',
              4, // 'DEADLINE_EXCEEDED'
              13, // 'INTERNAL'
              8, // 'RESOURCE_EXHAUSTED'
              14, // 'UNAVAILABLE'
              2, // 'UNKNOWN'
            ],
          },
        },
      );
....
....
```
 Stopped the emulator server and published this message, Didn't timeout after the given totalTimeoutMillis value instead it thrown timeout error after 10 mins (600000ms)

Tried with network traffic manager applications also to check whether any retry calls are made from the app to the server, also tried with disconnecting wifi and publishing message. None of them worked. 

Can you guys suggest a way to validate publishWithRetrySettings feature?

**Comment by xiaowei-routific** [comment]
Same here. We want to reset the value `totalTimeoutMillis` only but could not find a way. We end up doing similar things as @sdineshwaran did here. Is there a way to just change one field of the `backoffSettings` while let the rest be the default? 

Otherwise, is there a `RetryOptions.default()` or something to provide us with the default value?

**Comment by feywind** [comment]
@xiaowei-routific Yeah, the Java libraries have a similar thing to `RetryOptions.default()`. It seems like a good thing to have either way, though I think it's close to Node standard code to provide some sort of partial update method.

I do agree having to dig down deeper than the normal veneer layer is not a great experience. :|

**Comment by feywind** [comment]
I'm closing this out as part of cleanup, but will add a note to some in-progress design work on improving the API surface.
