### ISSUE TITLE
Not able to assign publisher role, subscriber role to the dead-letter topic

### ISSUE THREAD

**Issue by ishan123456789** [googleapis/nodejs-pubsub#1177]
#### Environment details

  - OS: Linux
  - Node.js version: 12.1.4
  - npm version: 6.13.4
  - `@google-cloud/pubsub` version: 2.5.0

#### Steps to reproduce

Create a subscription with a dead-letter you'll come to find that the newly created dead lettering doesn't have a subscriber/publisher role [image](https://i.stack.imgur.com/HxrhR.png)

From the [documentation](https://cloud.google.com/pubsub/docs/dead-letter-topics#assigning_the_publisher_role) we have to run CLI command for each dead-letter with its id but it won't be possible for us since we have too many subscriptions so want to do it using this package is there any way to do that.

**Comment by feywind** [comment]
@ishan123456789 I suspect that might be outside what the library currently does in its admin functions, but I will double-check.

**Comment by feywind** [comment]
I moved this to our internal backlog, hopefully I can find the right person to answer it finally. I am guessing you'd need to do something with IAM but I'm not very familiar with that side of the service.
