### ISSUE TITLE
User not authorized to perform this action

### ISSUE THREAD

**Issue by theromie** [googleapis/nodejs-pubsub#1180]
I am trying to pull pub sub messages but when I initially run function getting error
` 
  code: 7,
  details: 'User not authorized to perform this action.',
  metadata: Metadata { _internal_repr: {}, flags: 0 }
`

**Comment by feywind** [comment]
@theromie I'm guessing that there is a permissions issue there on the subscription setup. Let me see if I can find someone who can provide a better answer.

**Comment by theromie** [comment]
@feywind Yes, it was a permission issue.

**Comment by dharmeshgigs** [comment]
@theromie I'm facing the same error, could you please let me know what permission i'm missing to give?
