### ISSUE TITLE
Closing the PubSub client does not cleanup grpc connection

### ISSUE THREAD

**Issue by michaelwittig** [googleapis/nodejs-pubsub#1190]
#### Environment details

  - OS: MacOS 11.1 (20C69)
  - Node.js version: 14.15.3
  - npm version: 6.14.9
  - `@google-cloud/pubsub` version: 2.8.0

#### Steps to reproduce

I noticed the issue because jest complains about:

> Jest did not exit one second after the test run has completed.
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

But the issue can also be observed without a test runner:

```
import log from 'why-is-node-running'
import pubsub from '@google-cloud/pubsub';

(async () => {
  const client1 = new pubsub.PubSub({
    projectId: 'stub',
  });
  const [topic1] = await client1.createTopic('test');
  await topic1.delete();
  await client1.close();
  log();
})();
```

Output:

```
There are 10 handle(s) keeping the process running

# DNSCHANNEL
(unknown stack trace)

# TTYWRAP
/Users/michael/www/node_modules/supports-color/index.js:129 - stdout: getSupportLevel(process.stdout),

# SIGNALWRAP
/Users/michael/www/node_modules/supports-color/index.js:129 - stdout: getSupportLevel(process.stdout),

# TTYWRAP
/Users/michael/www/node_modules/supports-color/index.js:130 - stderr: getSupportLevel(process.stderr)

# Timeout
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/backoff-timeout.js:63 - this.timerId = setTimeout(() => {
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:189     - this.backoffTimeout.runOnce();
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:397     - this.startBackoff();
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:554     - if (!this.transitionToState([channel_1.ConnectivityState.IDLE], channel_1.ConnectivityState.CONNECTING)) {

# TCPWRAP
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:261 - return net.connect(this.subchannelAddress);
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:283 - const session = http2.connect(addressScheme + targetAuthority, connectionOptions);
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:361 - this.createSession(result);

# HTTP2SESSION
(unknown stack trace)

# Immediate
/Users/michael/www/node_modules/google-gax/build/src/call.js:70                    - setImmediate(this.callback, ...args);
/Users/michael/www/node_modules/google-gax/build/src/normalCalls/retries.js:82     - callback(null, response, next, rawResponse);
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/client.js:173              - callProperties.callback(null, responseMessage);
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334 - (_b = listener === null || listener === void 0 ? void 0 : listener.onReceiveStatus) === null || _b === void 0 ? void 0 : _b.call(listener, status);

# TickObject
(unknown stack trace)

# TickObject
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:411     - process.nextTick(() => {
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:441     - this.transitionToState([
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:496     - this.checkBothRefcounts();
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel.js:500     - this.unref();
/Users/michael/www/node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:56 - const refedSubchannels = subchannelObjArray.filter((value) => !value.subchannel.unrefIfOneRef());
```

while this works fine:

```
import log from 'why-is-node-running'
import pubsub from '@google-cloud/pubsub';

(async () => {
  const client1 = new pubsub.PubSub({
    projectId: 'stub',
  });
  /// nothing is done
  await client1.close();
  log();
})();
```

**Comment by feywind** [comment]
@michaelwittig Thanks for the report! This seems like it might be an issue with gax or grpc, looking at the list of handles, so I will defer to @alexander-fenster or @murgatroid99.

**Comment by tahsinature** [comment]
any other alternative way to solve this thing?

**Comment by murgatroid99** [comment]
That output shows that there is a pending `setImmediate` and a couple of pending `process.nextTick`. Those would be resolved very soon after that. So, what is the output if you run the same thing a couple of seconds later?

**Comment by michaelwittig** [comment]
If I await the close I expect the close to be done once the promise is resolved? and yes, I saw that thing close in the background.

**Comment by murgatroid99** [comment]
grpc-js does not provide a way to wait for all resources to be released, so whatever that close function is doing, it isn't that.

**Comment by feywind** [comment]
Looks like Pub/Sub is calling close() on each gax client it has a handle on.

**Comment by feywind** [comment]
@michaelwittig Just to clarify, is the issue that the test doesn't exist fast enough, or that it never exits? It would be ideal for close() to actually wait for all resources to close out, but given how much of the stack it looks like that would have to touch, it's something we'd probably rather say "increase the jest timeout" for the moment. If it never exits, that's something we should probably look at sooner.

**Comment by michaelwittig** [comment]
It's not only about jest (we only noticed it because of jest).

We have the same issue when we receive a SIGTERM from CloudRun. Our code listens to the signal and cleans up all resources (close db connections, close keep alive pools, ...). But, the pubsub client does not (at least within 10 seconds) do what it claims to do. Therefore, we get hard killed after 10 seconds by CloudRun.

My understanding of the problem: The resolved promise returned by close does not indicate that the close is done.

I still believe that is a bug.

**Comment by murgatroid99** [comment]
I have published a new version of grpc-js that might help with this. Can you update your dependencies and try again?

**Comment by ettancos** [comment]
@murgatroid99 thanks, I have tried with the latest (grpc-js 1.2.10), (pubsub 2.10.0), (google-gax 2.11.2)
one last timer remains

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Timers:
  - (298065 ~ 4 min) (anonymous) @ /home/ttancos/test/node_modules/@grpc/grpc-js/build/src/channel.js:304
  - (2000 ~ 2 s) (anonymous) @ /home/ttancos/test/main.js:23
```

**Comment by murgatroid99** [comment]
That timer is for a call to `Channel#watchConnectivityState`, which is generally called by `Client#waitForReady`. That intentionally keeps the process running, but it looks like there's supposed to be some special handling for calling that on a closed channel that currently isn't there. I can patch that, but there also isn't really a reason for it to be called at that point at all.

**Comment by ettancos** [comment]
I was testing the shutdown code for my process and admittedly without consuming anything, just setup the subscription handlers, then calling close on interrupt to remove the handlers and let the remaining events run out and expecting that node will exit soon.

Thanks for the quick action, I've tried your patch locally and it behaves as expected, no more timers. :smile:

**Comment by feywind** [comment]
It sounds like we can close this, then? This patch looks like it went into a recent `@grpc/grpc-js` release, so anyone having the problem should be able to pull in the newest version of that.

Please feel free to ping if it needs reopening.
