### ISSUE TITLE
feat request: pass in subscription options when auto-creating via subscription.get({autoCreate: true})

### ISSUE THREAD

**Issue by naseemkullah** [googleapis/nodejs-pubsub#1196]
Would like to configure expirationPolicy for autoCreated subscriptions (via `subscription.get({autoCreate: true})`).

Use case, many subscriptions (each with a subscriber) for one topic. When subscribers are gone their corresponding subscriptions should not linger around too long.

Subscribers are k8s pods and thus ephemeral.

Worth noting, every subscription is named after the k8s pod hostname.

**Comment by naseemkullah** [comment]
This is actually a feat request to allow for subscription options to passed in when auto-creating

**Comment by naseemkullah** [comment]
Here is the workaround:


```js
  const subscription = topic.subscription(`${os.hostname()}-${topicName}`, {
    enableOpenTelemetryTracing: true,
  });

  const [exists] = await subscription.exists();

  if (!exists) {
    await subscription.create({
      expirationPolicy: {ttl: {seconds: dayjs.duration(1, 'day').seconds()}},
    });
  }
  ```
  
  As seen `expirationPolicy` is being set, something that cannot be set with autoCreate today

**Comment by feywind** [comment]
I thought I'd added this somewhere already, but I'm moving it into our internal backlog just to make sure.
