### ISSUE TITLE
add Subscription#setOptions()

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-pubsub#12]
_From @tonila on November 5, 2017 6:40_

We are upgrading pubsub from 0.13.x to 0.14.x and current API documentation does not seem to answer our questions.

Documentation states that "subscription options do not persist across multiple instances". 

With current knowledge, I assume it means, that subscription, that you see at cloud console does not store subscription options, so you need to set them for each instance you receive from the cloud.

But how do you set options, since [subscription](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.5/pubsub/subscription) does not seem to have function for that?

Currently we are just always using topic.createSubscription() for new and existing subscriptions and it seems to work fine, but I am wondering, what is the intended way of doing this?

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2723_

**Comment by stephenplusplus** [comment]
You can set the options at the time of creating the Subscription reference object.

```js
topic.createSubscription('name', { /* options */ })
// or...
var subscription = topic.subscription('name', { /* options */ })
```

You do bring up a good question-- how can you set the options when you get a Subscription from `topic.getSubscriptions()`? @callmehiphop ?

**Comment by stephenplusplus** [comment]
_From @callmehiphop on November 5, 2017 19:46_

You currently can't, sounds like maybe we need to make a setter.

**Comment by callmehiphop** [comment]
We have a release coming up that will allow you to set options via `setOptions` method. We've also made some changes/additions to the available subscription options. Below is an example of using the setter with all the available options and their default values

```js
subscription.setOptions({
  ackDeadline: 10,
  batching: {
    callOptions: {}, // gax call options
    maxMessages: 3000,
    maxMilliseconds: 100,
  },
  flowControl: {
    allowExcessMessages: true,
    maxBytes: os.freem() * 0.2,
    maxExtension: Infinity,
    maxMessages: 100
  },
  streamingOptions: {
    highWaterMark: 0,
    maxStreams: 5, // formerly known as maxConnections
    timeout: 60000 * 5, // 5 minutes
  }
});
```
