### ISSUE TITLE
Default option `maxExtensionMinutes` is treated as seconds

### ISSUE THREAD

**Issue by novemberborn** [googleapis/nodejs-pubsub#1208]
The default options is set as 60 minutes:

https://github.com/googleapis/nodejs-pubsub/blob/ccebf72508ba9f410c539eedaa879ec6fa423c0b/src/default-options.ts#L29-L31

The value `60` is applied here:

https://github.com/googleapis/nodejs-pubsub/blob/74fc12e8d1e26939309748536bfecb751be0f079/src/lease-manager.ts#L188

However `maxExtension` is documented as being a value in seconds, defaulting to `60`:

https://github.com/googleapis/nodejs-pubsub/blob/74fc12e8d1e26939309748536bfecb751be0f079/src/lease-manager.ts#L39-L40

Arguably the default should be `1` and when that default is applied it needs to be modified by 60.

**Comment by feywind** [comment]
@novemberborn Dohh yes, that looks like a pretty straightforward bug.

**Comment by novemberborn** [comment]
Looking at the Go version of this SDK it seems like the default is supposed to be an hour?

**Comment by feywind** [comment]
Glancing at the Java library, it looks like it's defaulting to 60 minutes as well, so I'm going to assume this is a documentation error.
