### ISSUE TITLE
Expose PublishError

### ISSUE THREAD

**Issue by pkuczynski** [googleapis/nodejs-pubsub#1215]
`PublishError` class is not exported by the package. This blocks developer from pointing using it as a type for method signature in typescript:

What I would like to achieve is:

```js
import { PublishError } from '@google-cloud/pubsub'

export const onError = (error: PublishError): void => {
   ...
}
```

Currently, I can only achieve this by importing from module src, which is not ideal...

```js
import { PublishError } from '@google-cloud/pubsub/build/src/publisher/publish-error'
```

**Comment by feywind** [comment]
@pkuczynski This looks like a totally reasonable request, thanks for providing a pull request and all!

**Comment by pkuczynski** [comment]
Cool! Thanks! When do you think this could be released?

**Comment by feywind** [comment]
I'll go ahead and merge the release-please PR, so it should cut a release soonish. I'm trying to stick with the "release early and often" when there is stuff in the queue, so this is fine. (Also the change is small, so I'm not too worried about it.)

**Comment by pkuczynski** [comment]
Yeah, this change is pretty safe I think. I would be grateful if you could ping me whenever release happens...
