### ISSUE TITLE
Add support for Pub/Sub server schema to the Node client library

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1220]
This feature is currently in preview, and we need to get support for it in the library. Some things that need to be included (may expand):

* Support in the GAPIC layer (done)
* Support in the veneer (PubSub class) layer
* Added tests
* Added system-tests
* Added samples
* Added samples system-tests

**Comment by feywind** [comment]
It's looking like the PR for this will also address this issue, finally: https://github.com/googleapis/nodejs-pubsub/issues/1091

**Comment by gavingolden** [comment]
Is there an ETA on this?

**Comment by feywind** [comment]
@gavingolden It's mostly "asap" at this point, but I can't give a specific date. I _think_ the server side support is already turned on, on a preview basis, but client library support is still variable. Theoretically you should be able to do the basic schema operations using `gcloud` or the GCP web site, but I don't know a lot of the bigger project management picture.
