### ISSUE TITLE
Unhandled promise in message.ack() makes it hard for a terminating script to wait for ack

### ISSUE THREAD

**Issue by everhardt** [googleapis/nodejs-pubsub#1221]
#### Environment details

  - `@google-cloud/pubsub` version: 2.10.0

#### Steps to reproduce
```ts
const pubsub = new PubSub();
const subscription = pubsub.subscription(subscriptionName);
subscription.on('message', (m: Message) => {
  const dataUtf8encoded = m.data.toString('utf8');
  let event: unknown;
  try {
    event = JSON.parse(dataUtf8encoded);
  } catch (ex) {
    m.ack();
    console.log('Fail!');
    // ISSUE: the process will exit before the ack has been sent
    process.exit(1);
  }
  doSomethingWith(event);
  m.ack();
});
```

See the comment line starting with `// ISSUE: ` in the code above. An unexpected message will in this case not be cleared from the subscription. If my process would restart automatically, it would be in an infinite loop now. The problem is that `m.ack()` does not return a promise (while the underlying [subscriber ack function](https://github.com/googleapis/nodejs-pubsub/blob/master/src/subscriber.ts#L300) does). That seems to be a problem for others as well, see:
* https://github.com/googleapis/nodejs-pubsub/pull/428
* https://github.com/googleapis/nodejs-pubsub/issues/575

I read in  https://github.com/googleapis/nodejs-pubsub/pull/428:

> Unfortunately this isn't the first time this request has been made, but we've had some push back from the PubSub API team in the past.

I cannot find that push back discussion. If there's a good reason not to return a promise, an alternative would be to make `_waitForFlush` a public method. That I can `await` that before exiting the process.

ps. I can of course set an arbitrary timeout before exiting the process, but that's ugly.

**Comment by ettancos** [comment]
I would like an option to flush the acks and to be able to see a trace if there is a rejection there. Recently we run into the situation where we had to debug some occasional unhandled promise rejections, and we had to *patch* the ack/nack functions to use the underlying functions to be able to rule it out as the source.

**Comment by feywind** [comment]
That's pretty gross, yeah. I feel like this is probably related to this, work wise:

https://github.com/googleapis/nodejs-pubsub/issues/725

I'm going to add this issue to the internal backlog for that work.
