### ISSUE TITLE
Stops working when project is using opentelemetry-js 0.18+ packages

### ISSUE THREAD

**Issue by weyert** [googleapis/nodejs-pubsub#1233]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Yes, this is a client library issue

2) Did someone already solve this?
There renovatebot made a PR to solve this problem

3) Do you have a support contract?
No

#### Environment details

  - OS: macOS 11.2.3
  - Node.js version: 14.16.0
  - npm version: 6.x
  - `@google-cloud/pubsub` version: 2.10.0

#### Steps to reproduce

  1. Create new directory
  2. `npm init -y`
  3. Install the dependencies `npm install @google-cloud/pubsub @opentelemetry/core @opentelemetry/api`
  4. `npm ls @opentelemetry/tracing`
  5.  Notice that the installed version is 0.12 instead of the 0.18 version meets the Opentelemetry 1.0.0 tracing spec

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by feywind** [comment]
Oops, I didn't do the label triage. I'm going to consider it a bug since this has been broken for a while, and there is a fix in progress.

**Comment by weyert** [comment]
@feywind Can you please review the PR? All tests are passing 🥳
