### ISSUE TITLE
Emulator: `invalid_grant` and erratic error handling

### ISSUE THREAD

**Issue by lucasjohnston** [googleapis/nodejs-pubsub#1243]
#### Steps to reproduce

I can't get PubSub working at all locally with the emulator (all just going by the docs) - emulator runs fine with no errors, but doesn't look like its receiving anything.

`src/subscriptions.ts` defines a map of subscription names to consumer funcs, and after our express server has started running we asynchronously attempt to start listening to all subscriptions (including creating subscriptions/topics if they don't exist).
We're initialising the `SubscriberClient` for [Synchronous Lease Management](https://cloud.google.com/pubsub/docs/pull#synchronous_pull_with_lease_management) and PubSub for standard async consumption.
```
// Init v1 PubSub SubscriberClient and ensure it is initialised
const client = new v1.SubscriberClient()
await client.initialize().catch(e => {
  console.error(e)
  // sentry error handling goes here
  return
})

// Init v2 PubSub client and find/create topic
const pubsub = new PubSub()
let topic = pubsub.topic(consumer.topic)
let findTopicRsp = await new Promise(resolve => {
  topic.get((err, topic, apiResponse) => {
    console.log(JSON.stringify(apiResponse))
    if (err != null) throw err
    return resolve(topic)
  })
}).catch(e => {
  console.error(e)
  // sentry error handling goes here
  return
})
...
```

This function suddenly dies with no error or stacktrace at `topic.get()`.

Using `Promise.resolve()` is a bit messy with `findTopicRsp`, but I've found that every fews runs (randomly) I'll actually get an error back - `Failed to retrieve auth metadata with error: invalid_grant`.
I originally had it written as a typical await call but could never get any kind of error response (regardless of wrappers / try/catch / .catch() / etc).

To me, an `invalid_grant` error doesn't makes much sense connecting to a local emulator.
I decided to log the options which `new PubSub()` ends up collecting:
```
➜  backend git:(staging) ✗ $(gcloud beta emulators pubsub env-init)
➜  backend git:(staging) ✗ yarn start
$ some other build steps go here
$ npm run build
$ npx ts-node -r dotenv/config -r tsconfig-paths/register src/index.ts
process.env.PUBSUB_EMULATOR_HOST: ::1:8267
process.env.PUBSUB_PROJECT_ID: undefined
pubsub.isEmulator: true
pubsub.options: {"libName":"gccl","libVersion":"2.10.0","scopes":["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/pubsub"],"servicePath":"","sslCreds":{"callCredentials":{}}}
```

Even after onerously course-correcting the `servicePath` by initialising like this:
```
let port =
    process.env.PUBSUB_EMULATOR_HOST != null
      ? process.env.PUBSUB_EMULATOR_HOST.substring(
          process.env.PUBSUB_EMULATOR_HOST.length - 4,
          process.env.PUBSUB_EMULATOR_HOST.length,
        )
      : 8085
const pubsub = new PubSub({
    port,
    apiEndpoint: `https://localhost:${port}`,
})
```

I now get a response with the correct port/endpoint:
```
pubsub.options: {"libName":"gccl","libVersion":"2.10.0","scopes":["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/pubsub"],"port":8267,"apiEndpoint":"https://localhost:8267","servicePath":"localhost","sslCreds":{"callCredentials":{}}}
```

But the code still suddenly stops executing at `topic.get()`, and I've not had a single error caught by our local Sentry instance or in console or in the emulator.
When I use vscode's debugger, I manage to pry out the error: `Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: invalid_grant` error.

I can't find any resources on `invalid_grant`, so pointers here would be greatly appreciated. Also not sure what's happening with error handling - might be a stupid mistake I've made up the chain somewhere but I can't see anything atm. Thanks

#### Environment details

  - OS: macOS 11.2 
  - Node.js version: v14.15.5
  - npm version: 6.14.11
  - `@google-cloud/pubsub` version: 2.10.0

**Comment by lucasjohnston** [comment]
Bizarre how typing something up makes things more apparent. Doing an all nighter taking its toll.
1. Contrary to what I thought, `gcloud` hadn't actually been using my creds. `gcloud auth application-default login` solved that one.
2. Replaced my throws with `(resolve, reject)` + a uniform catch across all the PubSub fetching functions and now things are coming through uniformly. Not sure why `try { await new PubSub() } catch (e) { .. }` earlier wasn't catching anything though.

Leaving this open as some feedback / food-for-thought, though:
1. The docs should mention the emulator needs default credentials (ie. `gcloud auth application-default login`) locally to work.
2. `process.env.PUBSUB_EMULATOR_HOST` should produce `localhost` from `::` if gcloud is producing that as the env variable.
3. All of the examples in the docs are single functions that tear themselves down after a single message is processed. Having some better-documented examples + good practices for continuous listeners (ie. polling for new messages) and things like your NodeJS Stream functions would be really useful.

**Comment by feywind** [comment]
@lucasjohnston Thanks for the follow-up! It does sound like some improvements could be made in the docs here. For what it's worth, I think it would be nice to have some bigger end-to-end samples, too.

**Comment by lucasjohnston** [comment]
Have submitted a PR for one of these docs changed btw - https://github.com/googleapis/nodejs-pubsub/pull/1245

**Comment by feywind** [comment]
I'd like to get that in soon... there is some other weirdness going on with the build process though, might be next week.

**Comment by meredithslota** [comment]
That fix got merged, yay, so I think this can be closed? :)
