### ISSUE TITLE
Project Id should be taken from credentials.json

### ISSUE THREAD

**Issue by SrBrahma** [googleapis/nodejs-pubsub#1248]
**Is your feature request related to a problem? Please describe.**
Yes. If just using 

```ts
const credentials = require('./cred.json'); // cred from IAM service account key
new PubSub({credentials})
```

the following error will be thrown:

```
UnhandledPromiseRejectionWarning: Error: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
    at /home/hb/Dev/Contador-de-Clientes-Firebase/admin/node_modules/google-auth-library/build/src/auth/googleauth.js:87:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:216511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:216511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 **Describe the solution you'd like**
It should use the `project_id` from the service account credentials.json

 **Describe alternatives you've considered**
I am, as workaround, using `credentials.project_id`

**Comment by feywind** [comment]
@SrBrahma Thanks for the request! I think the generally recommended way of doing this is to feed in the path to the credentials file by way of an environment variable (`GOOGLE_APPLICATION_CREDENTIALS`). I'm curious to hear your use case for loading it by way of `require()` though.

**Comment by EyePulp** [comment]
Writing a secret to disk (even if it's ephemeral) feels like a bad move compared to having it sit in an environment variable along with all your other secrets, no?

**Comment by feywind** [comment]
I wonder if there has been a change in recommendation since this issue first opened. Last I heard, using a service key file was the right way to do it, but that may not be needed in e.g. GKE. I know with a recent test project I was able to use `gcloud auth login` and then `kubectl apply` to get a container running with access to my project.

I don't think many people are around today but I can post the question to see if anyone knows more.

**Comment by feywind** [comment]
This is probably most up to date: https://cloud.google.com/docs/authentication

I guess the answer is that it depends on where your services are hosted and what sort of access they need to other services.

**Comment by feywind** [comment]
There hasn't been much more traffic on this one (and I think the answers above are the right path), so I'm going to close it out.
