### ISSUE TITLE
[FEATURE REQUEST] Support for SubscriberClient to NACK a message

### ISSUE THREAD

**Issue by ckcr4lyf** [googleapis/nodejs-pubsub#1301]
It seems, when using Synchronous Pull with pubsub, received messages **cannot** be NACKd.

Going through documentation, there is a clear example on how to ack messages - https://github.com/googleapis/nodejs-pubsub/blob/master/samples/synchronousPull.js#L74

However in my case, on an error (within application), I would like to immediately NACK the message, so it may be picked up by another worker (rather than waiting for ~10s, as per the default ACK timeout).

Going through the definitions for `SubscriberClient` (https://github.com/googleapis/nodejs-pubsub/blob/master/src/v1/subscriber_client.ts), it does not seem like it is possible to NACK the message.

In comparison, for the Asynchronous Pull subscriber, which uses event handlers, the message object can be NACKd directly. Is it possible (or am I just missing) to add functionality to `SubscriberClient` to explicitly NACK messages?

**Comment by ckcr4lyf** [comment]
P.S., from my understanding, NACKing is the same as changing the acknowledgement deadline to 0 seconds (so it is immediately redelivered). For now I will send that request, wondering if it would be OK to add that as a `negativeAcknowledge` method on `SubscriberClient`.

**Comment by feywind** [comment]
@ckcr4lyf Thanks for the issue! In general the sync pull path is less well supported (from my experience, anyhow) because streaming pull is more efficient. That does seem kind of like basic, useful functionality though.

**Comment by feywind** [comment]
I'm moving this to our API v2 internal discussion doc.
