### ISSUE TITLE
subscription `ackDeadline` is not considered with `pubsub.subscription()`

### ISSUE THREAD

**Issue by madeindjs** [googleapis/nodejs-pubsub#1337]
#### Environment details

  - OS: Ubuntu 21.04
  - Node.js version: v14.15.4
  - npm version: v6.14.10
  - `@google-cloud/pubsub` version: v2.8.0

#### Steps to reproduce

Here a basic example

~~~js
const {PubSub} = require("@google-cloud/pubsub");

const pubsub = new PubSub({
  projectId: "mazen-158916",
  keyFile: "key.json",
});

const topicName = "alexandre-testing";

async function getTopic() {
  const [topic] = await pubsub.topic(topicName).get({autoCreate: true});
  return topic;
}

async function main() {
  const topic = await getTopic();

  const [subscription1] = await pubsub
    .subscription(`alexandre-testing-subscription-${new Date().getTime()}`, {
      topic,
      // not works
      ackDeadline: 60,
    })
    .get({autoCreate: true});
}

main().catch(console.error);
~~~

Here the result

![image](https://user-images.githubusercontent.com/11815139/123119539-e97b4780-d443-11eb-98a7-a1a8ecd3ab4d.png)

**Comment by madeindjs** [comment]
Please note that it works with `pubsub.createSubscription`

~~~js
const [subscription1] = await pubsub.createSubscription(
  topic.name,
  `alexandre-testing-subscription-${new Date().getTime()}`,
  { ackDeadlineSeconds: 60, }
);
~~~

**Comment by madeindjs** [comment]
Also please note that `setOptions` not works 

~~~js
let subscription1 = topic.subscription( `alexandre-testing-subscription-${new Date().getTime()}`);
subscription1.setOptions({ackDeadline: 600});
[subscription1] = await subscription1.get({autoCreate: true});
~~~

**Comment by feywind** [comment]
@madeindjs Thanks for the report! I was just looking at a related thing the other day, a test that was broken because it assumed that the metadata options could be passed in as part of the `topic.subscription` call. I've seen some other issues about the setOptions vs setMetadata thing too. This is honestly confusing as heck. The simplest workaround is to do something like this:

```
  const [subscription1] = await pubsub
    .subscription(`alexandre-testing-subscription-${new Date().getTime()}`, {
      topic
    })
    .get({autoCreate: true});
  await subscription1.setMetadata({
      ackDeadline: 60
  });
```

Let me know if that works for you, and I'll shift this over to a doc bug. Something really needs to be improved there.

**Comment by madeindjs** [comment]
@feywind I tried `setMetadata` solution but this does not works. Also this produce a typing error:

> Argument of type '{ ackDeadline: number; }' is not assignable to parameter of type 'SubscriptionMetadata'. Object literal may only specify known properties, and 'ackDeadline' does not exist in type 'SubscriptionMetadata'.ts(2345)

Currently, I found a workaround of this problem. I use `pubsub.createSubscription` (this one can set `ackDeadline`) and if ressource exists I fallback to `topic.subscription`. Here an example

~~~js
const { PubSub, Topic, Subscription, CreateSubscriptionOptions, SubscriptionOptions,} = require("@google-cloud/pubsub");

const pubsub = new PubSub({ projectId: "mazen-158916", keyFile: "key.json",});

async function getTopic(topicName = "alexandre-testing") {
  const [topic] = await pubsub.topic(topicName).get({autoCreate: true});
  return topic;
}

/**
 * @param {SubscriptionOptions} options
 * @returns {CreateSubscriptionOptions}
 */
function buildCreateSubscriptionOptions(options) {
  return {
    ackDeadlineSeconds: options?.ackDeadline,
    flowControl: options?.flowControl,
  };
}

/**
 * @param {Topic} topic
 * @param {SubscriptionOptions} options
 * @returns {Promise<Subscription>}
 */
async function getOrCreateSubscription(topic, options) {
  const RESSOURCE_ALREADY_EXISTS_ERROR_CODE = 6;
  const subscriptionName = `alexandre-testing-subscription-${new Date().getTime()}`;

  try {
    const subscriptionOptions = buildCreateSubscriptionOptions(options);
    const [subscription] = await pubsub.createSubscription(topic, subscriptionName, subscriptionOptions);

    return subscription;
  } catch (error) {
    if (error.code === RESSOURCE_ALREADY_EXISTS_ERROR_CODE) {
      const [subscription] = await topic
        .subscription(subscriptionName, options)
        .get({autoCreate: true});

      return subscription;
    } else {
      throw error;
    }
  }
}

async function main() {
  const topic = await getTopic();
  const subscription1 = await getOrCreateSubscription(topic, { ackDeadline: 600, });

  subscription1.on("error", console.error);
  subscription1.on("message", (message) => {
    console.log(`get message #${message.id} -- receive %o`,  JSON.parse(message.data.toString()) );
    message.ack();
  });
}

main().catch(console.error);
~~~

**Comment by feywind** [comment]
@madeindjs Sorry for taking a while to respond to this... I think the mistake in my example was `ackDeadline` instead of `ackDeadlineSeconds`. This test works for me:

```
  const [sub] = await pubsub
    .subscription('<...>')
    .get();
  const [old] = await sub.getMetadata();
  console.log('old ack deadline:', old.ackDeadlineSeconds);
  await sub.setMetadata({
      ackDeadlineSeconds: 60
  });
  const [newer] = await sub.getMetadata();
  console.log('new ack deadline:', newer.ackDeadlineSeconds);
```

With this result:

```
old ack deadline: 600
new ack deadline: 60
```

Also it's updated in the console:

![image](https://user-images.githubusercontent.com/57276408/134991043-bafb2553-5ed6-4b20-ab54-a389d1781350.png)

It's weird that there seem to be two different names in the typings though. :| I'll look at that more.

As far as creating with options, I'm planning to extend the work I did for `Topic.get()` to subscriptions:

https://github.com/googleapis/nodejs-pubsub/issues/1196

**Comment by feywind** [comment]
I was mistaken in my last comment. I was thinking of a different change I did... I'm intending to make `get()` on both `Topic` and `Subscription` able to pass creation parameters for `autoCreate`.

**Comment by SurferJeffAtGoogle** [comment]
@feywind This issue is now OoSLO.

**Comment by feywind** [comment]
I think, after reviewing this again, the functionality itself isn't really missing, it's that the names of the fields are really confusing (ackDeadline in the library vs ackDeadlineSeconds in gapic). I'm going to add this as an item for our API update doc and close out the GH issue for now.
