### ISSUE TITLE
webpack on the browser "cannot read property 'status' of undefined"

### ISSUE THREAD

**Issue by cdelguercio** [googleapis/nodejs-pubsub#1341]
References:

http://5.9.10.113/67017244/google-cloud-pubsub-typeerror-cannot-read-property-status-of-undefined
https://github.com/googleapis/nodejs-pubsub/issues/1011
https://github.com/googleapis/gax-nodejs/pull/554

// pull-retry.js
```
const google_gax_1 = require("google-gax");
/*!
 * retryable grpc.status codes
 */
exports.RETRY_CODES = [
    google_gax_1.grpc.status.DEADLINE_EXCEEDED,
    google_gax_1.grpc.status.RESOURCE_EXHAUSTED,
    google_gax_1.grpc.status.ABORTED,
    google_gax_1.grpc.status.INTERNAL,
    google_gax_1.grpc.status.UNAVAILABLE,
    google_gax_1.grpc.status.CANCELLED,
];
```

I understand that there isn't supposed to be support for webpack, but it seems like it shouldn't be that bad to hack a few libraries into working. I've tried the following just to hack past the errors that I've seen in browser:

// @google-cloud/pubsub/build/src/pull-retry.js : 20
```
const google_gax_1 = require("google-gax");
<NEW>
google_gax_1.grpc = {"status": {}};
</NEW>
```
The above fixes the original error, but then I get another error that I fix below

// google-auth-library/build/src/auth/googleauth.js : 415
```
resolve("my-project-id");
// child_process_1.exec('gcloud config config-helper --format json', (err, stdout) => {
//     if (!err && stdout) {
//         try {
//             const projectId = JSON.parse(stdout).configuration.properties.core.project;
//             resolve(projectId);
//             return;
//         }
//         catch (e) {
//             // ignore errors
//         }
//     }
//     resolve(null);
// });
```

I'm currently stuck at @google-cloud/pubsub/build/src/v1/publisher_client.js : 110
```
const google_gax_1 = require("google-gax");
...
this.iamClient = new google_gax_1.IamClient(this._gaxGrpc, opts);
```
google_gax_1.IamClient is undefined for some reason and it therefore says that google_gax_1.IamClient is not a constructor.

I this path of hacking through libraries likely to work for me in the end or am I doomed?

**Comment by cdelguercio** [comment]
Okay, I got a Publish command to work (which is all I need for my usecase) by doing the following:

@google-cloud/pubsub/build/src/v1/publisher_client.js : 110
```
// this.iamClient = new google_gax_1.IamClient(this._gaxGrpc, opts);
```

@google-cloud/pubsub/build/src/v1/publisher_client.js : ~145
```
// this.descriptors.batching = {
//     publish: new this._gaxModule.BundleDescriptor('messages', ['topic'], 'message_ids', gax.createByteLengthFunction(
//     // eslint-disable-next-line @typescript-eslint/no-explicit-any
//     protoFilesRoot.lookupType('google.pubsub.v1.PubsubMessage'))),
// };
```

This is a huge horrible disgusting hack, so any help finding another way to make it work would be awesome. I've seen references to people getting this to work, but I wasn't able to decode them and I'm not a very tight deadline, so sorry if the solution exists and I just missed it.

**Comment by feywind** [comment]
@cdelguercio Webpack actually should work now for the most recent versions of gax (or maybe it was rollup?) ... I reaaaallly can't recommend using Pub/Sub directly from a browser though, unless it's something like an Electron app. There are some not so great implications for the security of your service credentials. (The typical recommendation is to have your web app post to an HTTPS endpoint somewhere, and have _that_ do the push.)

That said, it looks like the problems are still mostly in gax/gapic... @alexander-fenster ?

**Comment by cdelguercio** [comment]
My use case is that I have give the browser (and therefore leak) credentials that can only Publish to one Pub/Sub topic. This topic counts U/I interactions and needs to support being called ~100,000 times per second. The results are then accumulated into totals via Apache Beam in real time. I don't authenticate the users in the browser, so any bad actor that wanted to spam my Pub/Sub topic would've been able to do so anyway. If someone really wants to hit us with false U/I interactions our system doesn't really care, it will just look like the site is really active.

**Comment by cdelguercio** [comment]
Also, for reference my code is almost identical to the example code for Publishing to a topic in Node.

https://cloud.google.com/pubsub/docs/publisher

The only difference being that I authenticate explicitly.

```
const topicName = 'interaction-input';
const data = JSON.stringify({interaction1: 1, interaction2: 2, interaction3: 3, interaction4: 4});

// Creates a client; cache this for further use
const googleAuth = new GoogleAuth({projectId: "nowunited-3ad26", credentials: {client_email: "my-publish-only-service-account@myapp.iam.gserviceaccount.com", private_key: "my-private-key"}});
const clientConfig = {auth: googleAuth};
const pubSubClient = new PubSub(clientConfig);

async function publishMessage() {
  // Publishes the message as a string, e.g. "Hello, world!" or JSON.stringify(someObject)
  const dataBuffer = Buffer.from(data);

  const messageId = await pubSubClient.topic(topicName).publish(dataBuffer);
  console.log(`Message ${messageId} published.`);
  console.log(data);
}

publishMessage().then(() => {
  done();
}).catch(error => {
  console.error(`Received error while publishing: ${error.message}`);
  throw(error);
});
```

**Comment by cdelguercio** [comment]
Last detail is that I'm using "vue-cli-service build" to build. So maybe I'm not doing some required webpack configuration that I don't know about?

**Comment by feywind** [comment]
@cdelguercio Thanks for the further info. There's a holiday in the US today because of the 4th, but I'm hoping @alexander-fenster can peek at this tomorrow.

**Comment by anujNetomi** [comment]
@alexander-fenster  any update on this issue ?

**Comment by feywind** [comment]
@summer-ji-eng is maintaining Node gax now... any thoughts?

**Comment by feywind** [comment]
@bcoe Maybe this is something we can add to a backlog doc in regards to SDK stuff? I feel like it's more a part of that work than a Pub/Sub problem in particular.

**Comment by feywind** [comment]
The latest feedback I've gotten re: using the library in a browser context is that we really don't support that at this point, but it's something that we're periodically revisiting.
