### ISSUE TITLE
Publisher.publishMessage does not allow null data

### ISSUE THREAD

**Issue by shaug** [googleapis/nodejs-pubsub#1363]
The [documentation for the message format](https://cloud.google.com/pubsub/docs/publisher#message_format) suggests that `data` is not required if attributes or an ordering key is specified (emphasis mine):

> A message consists of fields with the message data and metadata. Specify **at least one** of the following in the message:
> 
> * The message data
> * An ordering key
> * Attributes with additional metadata

The `Publisher.publishMessage` code, however, requires that `data` be a Buffer:

https://github.com/googleapis/nodejs-pubsub/blob/481f6af85c30cd4e1cdae37d0fef887f65dae9d2/src/publisher/index.ts#L157

```ts
  publishMessage(message: PubsubMessage, callback: PublishCallback): void {
    const {data, attributes = {}} = message;

    if (!(data instanceof Buffer)) {
      throw new TypeError('Data must be in the form of a Buffer.');
    }
```

Am I misinterpreting the documentation? Or is this code being overprotective?

Thanks!

-Scott

**Comment by feywind** [comment]
@shaug Thanks for the report! That is indeed kind of confusing. It might be a mismatch between the expectations in Node vs the other client libraries, but I'll ask them what they think we should do here. My hunch is that the documentation is actually wrong, and that you always have to supply a data buffer (even if it's empty).

**Comment by shaug** [comment]
Thanks, @feywind. I make use of the Python and Ruby libraries as well, so consistency across libraries (whatever the ultimate behavior) would be great. Currently, the Ruby library doesn't fail if a `nil` data is specified, but it does turn that into an empty string in the implementation before sending it out into the world. I'm not sure what the python library does, as I don't think I've tried to send empty or `None` data there.
