### ISSUE TITLE
Improve error messages 

### ISSUE THREAD

**Issue by Ginden** [googleapis/nodejs-pubsub#1385]
#### Environment details

  - OS: N/A
  - Node.js version: v16.5.0
  - npm version: N/A
  - `@google-cloud/pubsub` version: 2.16.6

#### Steps to reproduce

  1. Listen to subscription with no permission to subscribe.
  
  
**Actual result**: "User not authorized to perform this action" error. 
**Expected result**: descriptive error details - what kind of action I'm not allowed to perform? What part of my code triggered this error?

**Comment by meredithslota** [comment]
@feywind Have the error improvements been piped through yet? This might be addressed by that project; if not (or if that work won't solve that issue) let's file an internal issue with the Pub/Sub team on improving this.

**Comment by feywind** [comment]
Yeah, this won't be improved by that, because only a few of the server-side methods actually return extended error info. I'll add it to the client libraries team doc for next week.
