### ISSUE TITLE
Connection drop detection

### ISSUE THREAD

**Issue by sanssucre** [googleapis/nodejs-pubsub#140]
Seems that there is no easy way to monitor the validity of the subscription's connection pool.

#### Environment details

  - OS: OSX
  - Node.js version: 8.10.0
  - npm version: 5.6.0
  - `@google-cloud/pubsub` version: ^0.18.0

#### Steps to reproduce

  1. Start a subscription
  2. unplug the network (all of them)

The subscription remains alive and the connection pool reports all is well event though the computer is offline.  After the timeout period (5 minutes?) error messages about too many listeners added appear on the console

**Comment by callmehiphop** [comment]
@murgatroid99 is there any easy way to monitor this kind of state change with gRPC?

**Comment by murgatroid99** [comment]
I know that gRPC uses HTTP2 pings to keep the connection alive, and I'm not sure but I think it also ends active requests with an error if too many of those pings are unanswered. I don't recognize the "too many listeners" error from the original question; maybe something is going wrong with handling those errors.

**Comment by callmehiphop** [comment]
@sanssucre I believe this should be resolved as of `v0.23.0`, if you find thats not the case let me know and I'll re-open this issue. Thanks!
