### ISSUE TITLE
"Failed to connect before the deadline" error

### ISSUE THREAD

**Issue by AkioSarkiz** [googleapis/nodejs-pubsub#1408]
#### Environment details

  - OS: Debian GNU/Linux 9
  - Node.js version: v10.22.1
  - npm version: 6.14.10
  - `@google-cloud/pubsub` version: ^2.18.1

#### Steps to reproduce

  1. Create subscription
```js
import pb from '@google-cloud/pubsub';

const Pubsub = pb.PubSub;
const pubSubClient = new Pubsub();
// ***
const subscription = pubSubClient.subscription("some-name");
```
  2. Start worker `npm run start`
  3. After 30 hours. Errors appear "Failed to connect before the deadline"

[issue 2019 year](https://github.com/googleapis/nodejs-pubsub/issues/818)

**Comment by AkioSarkiz** [comment]
@feywind enough data?

**Comment by avalverdero** [comment]
Hi all, I have the same problem from some weeks ago with different nodejs and pubsub versions.

Currently I'm using nodejs `12.19.0` and pubsub nodejs library `v2.18.4`.

It happens after different time frames.

Do you have some fix to this behaviour?

Thanks in advance

**Comment by vk185065** [comment]
We are having same issue - within 24 hours window the subscription stops receiving new messages and those are messages we can find in logs...
We can't go to production with behavior :-(

**Comment by feywind** [comment]
I'm pretty sure this is related to the ongoing set of issues around the grpc stream disconnecting silently.

**Comment by feywind** [comment]
Linked to the meta-issue about transport problems: b/242894947

**Comment by feywind** [comment]
Ping, the meta-issue above is still under investigation.

**Comment by kamalaboulhosn** [comment]
We have not been able to find a general way to approach debugging these problems, but instead have required customer-specific investigations around their setup. Please enter a support case with all of the details of your clients and the environments in which they run in order to continue the investigation. Thanks!
