### ISSUE TITLE
Reference docs make it difficult to find basic info

### ISSUE THREAD

**Issue by HenrikJoreteg** [googleapis/nodejs-pubsub#1422]
I came looking for "What is full list of available options I can pass when creating a new subscription?"

I eventually found this:
https://googleapis.dev/nodejs/pubsub/latest/Subscription.html#create

Which, very subtly links off to this: https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions which seems to contain the actual info I'm looking for.

But there is quite a bit of noise and not much hierarchy. For example when you first land here: https://googleapis.dev/nodejs/pubsub/latest/index.html you just see a giant list of alphabetized classes, subscriptions and topics are buried at the bottom and `BatchError` gets top spot.

Would just be cool to have a bit more of an organized reference. To be clear I'm just trying to provide feedback, not just complain 😅 

Feel free to close this if it's not useful. Just providing my 2 cents.

**Comment by feywind** [comment]
@HenrikJoreteg I'm with you here. There are some doc reorganization efforts going on right now, not quite sure what I'm supposed to talk about publicly. 😹 But this sort of confusion and lack of linkage is something that's definitely being looked at, at a higher GCP level right now.
