### ISSUE TITLE
`subscription.exists()` promise never resolves on one specific subscription

### ISSUE THREAD

**Issue by phil-booth-qatalog** [googleapis/nodejs-pubsub#1430]
We have some code in an internal broker abstraction, which checks whether a subscription exists and then either creates one or uses the existing one if found. For most of our subscriptions that works fine, but on one particular subscription the returned promise is never resolved.

The code looks like this:

```js
const subscription = topic.subscription(name);
const [exists] = await subscription.exists();

if (exists) {
  subscription.setOptions(options);
} else {
  subscription = await createSubscription(topic, name, options);
}

// ...
```

We zeroed in on the call to `exists` using line-level logging, the problem is definitely there. The promise is not rejected and no errors are thrown. It's always the same subscription that it "hangs" on, but looking at it in the GCP console I can't see anything different or weird about that subscription. All of our subscriptions are created in code (using the code above), so they all get the same options.

Do you have any suggestions about what might be going on here? Or anything that might help us to debug it further?

**Comment by phil-booth-qatalog** [comment]
One more factoid we've discovered here, it seems like it might be related to the number of subscriptions we have open in the process? `git bisect` took us to a commit that added a new subscription and the one that's failing just happens to be the last subscriber to get opened. Removing any subscriber allows all of the others to succeed.

Is there any kind of explicit or implicit limit on the number of subscribers per process, or some other resource that's linked to subscriptions?

**Comment by phil-booth-qatalog** [comment]
Regarding subscriber limits, there is some interesting discussion here I notice: https://github.com/googleapis/nodejs-pubsub/issues/1276.

Seems like 2 suggestions from that thread are worth looking into: `maxStreams` and using multiple `PubSub` instances. Will try both and see how they pan out.

**Comment by phil-booth-qatalog** [comment]
Pooling our `PubSub` instances depending on subscriber count works nicely. Closing this, thanks for all your help! :joy:

**Comment by feywind** [comment]
@phil-booth-qatalog Sorry this ended up being a choose your own adventure issue 😂 It sounds like you got something worked out, but it seems like an odd problem. Maybe all of the grpc channels were taken up by subscribers doing streaming pull requests? It seems like if that's the issue, there should at least be some kind of warning.

**Comment by sherifbeat81** [comment]
@phil-booth-qatalog How did you manage to make it work?

I'm facing the same issue here. For one Pubsub instance, I can create max of 36 subscribers.
