### ISSUE TITLE
Documentation - Is function .publish() deprecated or not?

### ISSUE THREAD

**Issue by petrvecera** [googleapis/nodejs-pubsub#1434]
All the documentation "quick start" examples are showing usage with `.publish()` function. 
https://googleapis.dev/nodejs/pubsub/latest/index.html
```javascript
// Send a message to the topic
  topic.publish(Buffer.from('Test message!'));
```
https://cloud.google.com/pubsub/docs/quickstart-client-libraries
```javascript
  try {
    const messageId = await pubSubClient.topic(topicName).publish(dataBuffer);
    console.log(`Message ${messageId} published.`);
  } catch (error) {
    console.error(`Received error while publishing: ${error.message}`);
    process.exitCode = 1;
  }
```

However this function is deprecated as per the source code documentation https://github.com/googleapis/nodejs-pubsub/blob/main/src/topic.ts#L635 
But this commit has been done 2 years ago? https://github.com/googleapis/nodejs-pubsub/commit/b2f96ffe6c1db93741f40804786f8c294717676b#diff-8533605ceddda0b8f0fcbdc3dc3c443d289c4a50622e5562e069a01e202d8b84R613

At first I thought that the docs are just not updated but than it's already 2 years? So the question is, are the docs really just not updated and we should rewrite it to publishMessage() to get rid of all the warnings we are getting or is that deprecation warning wrong? 

Thanks

**Comment by EyePulp** [comment]
I just started trying to use this library and was very confused by the same thing.  I appreciate you opening the ticket @petrvecera

**Comment by meredithslota** [comment]
I ... do not have the correct historical context to why that decision was made. Let me see if @feywind knows. I agree, that is confusing.

**Comment by feywind** [comment]
Wow, I'd never noticed this before, either. I think it's just wrong, though I am going to guess that the reason it ended up there to begin with is that we've been angling towards users passing in data and attributes as part of a single parameter (which `publishMessage` does).

@hongalex @anguillanneuf Do either of you have thoughts re: other languages?

**Comment by meredithslota** [comment]
Ok, I did some more digging — it looks like our "quickstart" on cloud.google.com has been updated and does indeed use the `publishMessage()` version (https://cloud.google.com/pubsub/docs/quickstart-client-libraries#node.js) and those code samples have been updated more recently, here: https://github.com/googleapis/nodejs-pubsub/blob/HEAD/samples/publishMessage.js). I think there are some hardcoded code samples in the client library documentation that escaped our noticed. So I'm leaning toward the documentation being wrong in places but will leave it to @feywind to confirm. :)

**Comment by EyePulp** [comment]
That's helpful, thanks @meredithslota

**Comment by chronos1nside** [comment]
> 

Could you provide an example?

I followed the links posted by @meredithslota but it forwarded me to the old versions.

My current implementation is the following:

`const customAtt: Attributes = { ...metadata };`
`const message = await client.topic(topicName).publish(Buffer.from(JSON.stringify(payload)), customAtt);`


Am I suposed to do this?

`const customAtt: Attributes = { ...metadata };`
`const outboundMessage = { payload, customAtt };`
`const message = await client.topic(topic).publishMessage(outboundMessage);`

**Comment by EyePulp** [comment]
@chronos1nside here's what I did:
If you're sending a js object there's a `json` convenience key that takes care of the stringify steps:
```js
const json = { foo: 'bar', yo: 'ho' };  // converted to the base64 encoded message.data key
const attributes = { extra: 'value' };

const message = await client.topic(topicName).publishMessage({ json, attributes });

```
Here's the code in place for the `json` key:
https://github.com/googleapis/nodejs-pubsub/blob/a40a23ee43c6697000996e0ff7070f41610397f5/src/topic.ts#L835-L838

Here's the source for the attribute key: https://github.com/googleapis/nodejs-pubsub/blob/98840fcc38a05be07de6e7dc97d8a79616940df9/src/publisher/index.ts#L168-L173

**Comment by EyePulp** [comment]
@chronos1nside sorry, to adapt your example:

```js
const customAtt: Attributes = { ...metadata };
const outboundMessage = { json: payload, attributes: customAtt };
const message = await client.topic(topicName).publishMessage(outboundMessage);

```

**Comment by chronos1nside** [comment]
> @chronos1nside sorry, to adapt your example:
> 
> ```js
> const customAtt: Attributes = { ...metadata };
> const outboundMessage = { json: payload, attributes: customAtt };
> const message = await client.topic(topicName).publishMessage(outboundMessage);
> ```

Thanks! I'm gonna work with that :D

**Comment by feywind** [comment]
I'm going to add this to our internal backlog to fix the docs one way or another (docs or samples).

**Comment by feywind** [comment]
Moving back out to GitHub.

**Comment by feywind** [comment]
Apparently I didn't update here earlier: the determination we made is that publish() should indeed be deprecated, and the samples and docs should be updated. So this is a todo item for that now.

**Comment by feywind** [comment]
I'm actually not sure why this is still open, the docs have been fixed.
