### ISSUE TITLE
Should `PUBSUB_PROJECT_ID` be `GCLOUD_PROJECT`?

### ISSUE THREAD

**Issue by ple16** [googleapis/nodejs-pubsub#1444]
I was doing some tracing, and I noticed that the message in the trace still had a placeholder.

```
messaging.destination | projects/{{projectId}}/topics/...
```

duplicating the env `GLOUD_PROJECT` to `PUBSUB_PROJECT_ID` successfully replaced the placeholder, I tracked it down to this section of code. Which seems to be the only 2 lines that reference `PUBSUB_PROJECT_ID`
https://github.com/googleapis/nodejs-pubsub/blob/a40a23ee43c6697000996e0ff7070f41610397f5/src/pubsub.ts#L780

but should it be `GLOUD_PROJECT` or am I misunderstanding something?

**Comment by meredithslota** [comment]
Thank you for reporting this! We will take a look, although possibly not until after the holidays.

**Comment by feywind** [comment]
I'm adding this to my list of issues to bring up at our weekly meeting, I think we just need some clarification on what it's supposed to be doing.

**Comment by feywind** [comment]
The kind of annoying answer to this (sorry) is that Pub/Sub probably had that environment variable before GCLOUD_PROJECT was a thing. We'd definitely like to unify this across libraries, but it'll probably a 2.0 API thing.
