### ISSUE TITLE
Subscription messages takes a long time to return after errors

### ISSUE THREAD

**Issue by slavoroi** [googleapis/nodejs-pubsub#1450]
After Upgrading to `@google-cloud/pubsub": "2.18.4"` our messages gets read by the subscription after a long time if they error and don't get acked.
We created a new topic & subscrioption with an ack deadline of 15 seconds.

While debugging locally `handleMessage` gets called once an hour, while downgrading to `2.17.0` or `1.7.3`
it gets called once a ~60 sec (which is also not optimal as the queue has a 15 sec default ackDeadline, but still better than an hour).
```
const pubSub = new PubSub({projectId: GCP_PROJECT_ID});
const subscription = pubSub.subscription(name, options);
subscription.on('message', handleMessage);
subscription.on('error', onError);
```

#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 16.13.0
  - npm version: 6.14.15
  - `@google-cloud/pubsub` version: 2.18.4

#### Steps to reproduce

  1. Update your library to `@google-cloud/pubsub": "2.18.4"`
  2. Listen to a subscription that is not acked, gets called rarely.

**Comment by slavoroi** [comment]
This is what I think is happening
1. A message is delivered to the subscriber
2. The subscription's ack deadline is 15 seconds. So any message that is not acked or not having its deadline extended should be redelivered after 15 seconds.
3. However although the message is never acked, the subscriber library keeps extending the ack deadline. If there is an actual error in processing, it would be good for the code to exit so that the library is not allowed to do this.
4. The next question is for long the library will keep extending the deadline
Please see here: https://github.com/googleapis/nodejs-pubsub/blob/main/src/lease-manager.ts#L42
It will keep doing that for 60 minutes on the default configuration
5. In versions prior to 2.18.1, this number was being treated as seconds. That meant that, although it is a bug, the message would have got redelivered after 60 seconds.
This was fixed
https://github.com/googleapis/nodejs-pubsub/issues/1208
So now this will keep on going for an hour.

Solution:
Please see these two entries from people who faced the same issue
https://stackoverflow.com/questions/70465491/google-cloud-pubsub-not-resending-unacknowledged-messages/70472177
https://howtofix.io/google-cloud-pubsub-not-resending-unacknowledged-messages-id487870

They set maxExtensionMinutes: 0

This means no extensions, and thus if a message will get redelivered after 15 seconds in your case if it is not acked.

Please try this out to see if it helps.

thanks,
Libin
Google Cloud Support, Dublin (GMT)

**Comment by slavoroi** [comment]
Setting
```
 flowControl: {
          maxExtensionMinutes: 0,
 }, 
```
solves it although it's really not intuitive.

**Comment by feywind** [comment]
Hmm, okay. I wonder if this is a bug related to the backwards compatibility in https://github.com/googleapis/nodejs-pubsub/issues/1208

**Comment by feywind** [comment]
I'm going to bring this up in our weekly meeting to see if there's a more graceful way to handle this. I suspect you might also be able to get the 15 second behaviour by setting it to 0.25 minutes, but I haven't tried that yet.

**Comment by feywind** [comment]
@slavoroi The others agreed that what you probably want is to set maxExtensionMinutes to 1 (60 seconds, should be the normal behaviour) or 0.25 (15 seconds). I wanted to address one part of this in particular though:

`If there is an actual error in processing, it would be good for the code to exit so that the library is not allowed to do this.`

Can you clarify what you mean here by an actual error? Like, code error in the library, code error/exception in the user's .on() handler, or what? I'm asking because we're working on this 2.0 API project, and thought maybe calling nack() if the user's handler throws an exception might be a good way to go.

(closing but please feel free to keep commenting)

**Comment by modestaspruckus** [comment]
I was experiencing simillar issue until realised it is related to `maxExtensionMinutes` setting. 
I was using `exactlyOnceDelivery` subscription with flow control `maxMessages`. I noticed this is starts to happen when `exactly_once_warning_count` starts to increase. My subscribers just stops to pull new messages and I was wondering what is happening. Changing `maxExtensionMinutes: 0` solves the issue.
![image](https://user-images.githubusercontent.com/26200870/232131554-29af7ffc-9664-4fa2-a067-6aee93672206.png)
