### ISSUE TITLE
Property 'destroy' in type 'MessageStream' is not assignable to the same property in base type 'PassThrough'

### ISSUE THREAD

**Issue by sariroti** [googleapis/nodejs-pubsub#1451]
When we try to build our nestjs  application using npm run build there is error like this : 

![image](https://user-images.githubusercontent.com/30611849/148161518-88c13fd0-775a-40a1-89dd-1da72b5ad5e2.png)

Environment details
OS: Linux Alpine
Node.js version: 12.18.3
npm version: 6.14.8
@google-cloud/pubsub version: 2.18.4

Steps to reproduce
Update your library to @google-cloud/pubsub": "2.18.4"
docker build -t <your docker image name> -f <your docker file location> <your folder >
in docker file there is command RUN npm run build

**Comment by ypriyantoko** [comment]
we got the same issue :

![image](https://user-images.githubusercontent.com/29891495/148173160-4760f596-e513-41c4-9538-5ef0d94ce026.png)

@sariroti temporarily we fix it with using fixed old pubsub version, and remove package-lock.json from .gitignore

**Comment by sariroti** [comment]
Hi @ypriyantoko can you tell me which old version you use ? i try to use older version like 2.17.0 no luck.

**Comment by sariroti** [comment]
so we've fixed this by using this line in Dockerfile 

COPY ./package*.json ./

previously is : 


COPY ./package.json ./


without a star after package.

found by my colleauge.

thanks @ypriyantoko for commenting and helping

**Comment by dweekly** [comment]
FYI, seeing this issue also.

**Comment by dweekly** [comment]
Awesome. Can we get this pushed in a release soon?
