### ISSUE TITLE
PubSub Subscription randomly stops pulling messages from a topic

### ISSUE THREAD

**Issue by gothraven** [googleapis/nodejs-pubsub#1453]
For a while now, we noticed that the code just stops pulling new messages so randomly, sometimes it takes few weeks, sometimes days before that happens, and we always had to re-start the service for this to work again.

I have found a similar issue [.NET](https://github.com/googleapis/google-cloud-dotnet/issues/5231) repository, I don't know if that can help.

#### Environment details

  - OS: 16.5.0-alpine3.14
  - Node.js version: 16.5.0
  - npm version: 7.11.2
  - `@google-cloud/pubsub` version: 2.18.3

**Comment by feywind** [comment]
@gothraven Thanks for the note - do you think it might be related to https://github.com/googleapis/nodejs-pubsub/issues/1135 ?

**Comment by gothraven** [comment]
@feywind It might be related to `grpc` I have been reading few things about this but it does not happen 15 min after launching, it sometimes takes days, sometimes weeks, but never less than a day (in our case), I'm not sure if that helps !

**Comment by weyert** [comment]
Any news on this?

**Comment by robottheory** [comment]
This sounds just like https://github.com/googleapis/nodejs-pubsub/issues/1135, maybe we should consolidate the issue?

**Comment by mfarhat437** [comment]
We have the same problem. Is there any news? not after 15 min. it happens randomly

**Comment by feywind** [comment]
Yeah, I agree, I'm going to ref it again on #1135 and close this one.
