### ISSUE TITLE
Pipe through GoogleError objects from improved gax ErrorInfo handler

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1497]
This is in regards to @summer-ji-eng 's work on the gax ErrorInfo handling. We need to change the error types to GoogleError so that more methods/fields can be found on the returned errors in cases where ErrorInfo is returned (potentially available for testing: schema validation).

**Comment by summer-ji-eng** [comment]
Thank you Megan. The ChannelError is an [example](https://github.com/googleapis/nodejs-pubsub/blob/main/src/message-stream.ts#L90) that lose the beneficial from gax.GoogleError property. 

I would recommend to extend `gax.GoogleError` to get the parsed grpc.Metadata([statusDetails](https://github.com/googleapis/gax-nodejs/blob/main/src/googleError.ts#L25-L28)) from GoogleError and promote `reason`, `domain`, `errorInfoMetadata`.

**Comment by feywind** [comment]
Ah, I never ended up closing this out after the internal discussion. I have some concerns about making non-backwards-compatible changes to the error interfaces we're currently exposing (it's not a direct chain of inheritance). The GoogleError objects are being thrown properly, but there are only a couple of things in Pub/Sub that actually provide ErrorInfo:

- Schema validation methods: These should be throwing the correct error object, and users can dig out the parsed error info by passing it through `unknown`.
- Ack/ModAck/Nack: This appeared with exactly-once subscriptions, and support is being added explicitly to the library (the user won't see these errors).

For API 2.0 we're going to build with GoogleError from the ground up, so this shouldn't be an issue going forward.
