### ISSUE TITLE
admin operation default deadline should be 60s

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-pubsub#15]
_From @mdietz94 on December 12, 2017 21:44_

Right now the deadline defaults to 30s as declared by gRPC. We should set this to 60s so it can more quickly be retried by clients if a server is unreachable or unavailable. This also mirrors the deadlines set by Java/C#.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2772_

**Comment by mdietz94** [comment]
This is not an enhancement, we will soon consider operations made with deadlines shorter than 60s as out of SLO - this is a GA blocker and would cause users of the current client library to potentially suffer outages they would not with a higher deadline.

**Comment by stephenplusplus** [comment]
Thanks for providing that info.

**Comment by callmehiphop** [comment]
@mdietz94 currently all deadlines are configured to be 60s in our [client config](https://github.com/googleapis/nodejs-pubsub/blob/master/src/v1/subscriber_client_config.json). This leaves me wondering if this is an issue in our code or perhaps gax isn't honoring these configurations anymore.

**Comment by mdietz94** [comment]
I see, thanks, I was trying to follow this in the code and did not realize we had overrides - I did not actually see users' deadlines that were set shorter. Thanks for pointing out these configs.

**Comment by callmehiphop** [comment]
Awesome, glad to hear!
