### ISSUE TITLE
Does pubsub batch publishing support message publish with custom attributes?

### ISSUE THREAD

**Issue by nraj-willow** [googleapis/nodejs-pubsub#1523]
I am on v2.19.0 of gcp pubsub. I am trying to publish messages via batch publish. This message needs to have a custom attribute too.

When I am publishing the message is getting published fine but the attribute is getting lost.
I looked at the library code. It has a reference document for attribute params but when I looked at the code, I feel attribute param is not used/ declared in the method parameter.
Exact code link- https://github.com/googleapis/nodejs-pubsub/blob/ef2ec51e95c14ea4479a2abee1259e1e5f896717/src/publisher/flow-publisher.ts#L78

Please let me know if its possible to send attributes or not in flow-controlled batch publishes.

**Comment by feywind** [comment]
@nraj-willow Did you end up finding the answer to your question? The `PubsubMessage` interface actually has an `attributes` field, so you should be able to pass those in when calling `publish()`. It's derived from this:

https://github.com/googleapis/nodejs-pubsub/blob/main/protos/protos.d.ts#L551

**Comment by nraj-willow** [comment]
Hi @feywind ,
Thanks for letting me know. But that use-case is closed now.
I will definitely give this a try new time I come across the same.
