### ISSUE TITLE
Internal Server Error 500 / Fatal error: Trait 'description' not found...

### ISSUE THREAD

**Issue by caioricciuti** [googleapis/nodejs-pubsub#1525]
Hello All, I send messages from by backend using pub/sub. Today out of nowhere I got the following error: 

Code: 500
Level: 0 
Status: "Internal server Error"
text: "Fatal error: Trait 'description' not found"

Anyone is having this issue? Thank you all in advance!

**Comment by meredithslota** [comment]
Can you share any additional repro information? I took a look through the history of service issues, and it's possible this was caused by an internal issue that has since been resolved. Is this still occurring?

**Comment by feywind** [comment]
Having not heard anything new, I'm going to go ahead and close this, feel free to comment if it's needed.
