### ISSUE TITLE
INTERNAL error on stramingPull

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-pubsub#1534]
#### Environment details

  - OS: Windows
  - Node.js version: 16
  - npm version: 8
  - `@google-cloud/pubsub` version: 2.19.0

#### Steps to reproduce

  running this code snippet
  ```js
  function main(
    projectId = 'cmor-baas-dev',
    subscriptionNameOrId = 'projects/cmor-baas-dev/subscriptions/test-latency-pull'
) {
    const { v1 } = require('@google-cloud/pubsub');

    const subClient = new v1.SubscriberClient();

    async function streamingPull() {
        const formattedSubscription =
            subscriptionNameOrId.indexOf('/') >= 0
                ? subscriptionNameOrId
                : subClient.subscriptionPath(projectId, subscriptionNameOrId);

        const request = {
            subscription: formattedSubscription
        };

        const stream = subClient.streamingPull({});
        stream.on(
            'data',
            (response) => {
                console.log(response);
            }
        );
        stream.on('error', (err) => {
            console.error(err);
        });
        stream.on('end', () => {
            console.log('stream ended');
        });

        stream.write(request);
        // stream.end();

    }

    streamingPull().catch(console.error);
}

main(...process.argv.slice(2));
  ```
  then this is comming to output
  ```
  Error: 13 INTERNAL: A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]
    at Object.callErrorFromStatus (D:\projects\nodejs-pubsub\samples\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (D:\projects\nodejs-pubsub\samples\node_modules\@grpc\grpc-js\build\src\client.js:391:49)
    at Object.onReceiveStatus (D:\projects\nodejs-pubsub\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at D:\projects\nodejs-pubsub\samples\node_modules\@grpc\grpc-js\build\src\call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
stream ended
  ```

Note: 
If I uncomment `stream.end()` then the error goes away, but it ends the stream, my assumption is when using pullingStream we want to keep the stream open to recieve further requests.

also although I have some unaked messages nothing comes up in the error or data callbacks

**Comment by RezaRahmati** [comment]
Adding google support case number: 29821809

**Comment by feywind** [comment]
@kamalaboulhosn Is there something matching on the service end for this? I'd think any `INTERNAL` errors are coming from the service.

Aside from that: We don't recommend using the raw streaming pull API if possible - you won't get ack lease management or flow control.

**Comment by RezaRahmati** [comment]
@feywind Thanks for the reply, would you please provide best practice/example of streamingPull

**Comment by kamalaboulhosn** [comment]
@feywind It means something happened on the server, but it would really require debugging on the server side to see what the underlying error is. For that, you could enter a support ticket, @RezaRahmati.

**Comment by feywind** [comment]
@kamalaboulhosn Looks like there's a support ticket a few comments up?

@RezaRahmati [This is the sample for streaming pull](https://github.com/googleapis/nodejs-pubsub/blob/HEAD/samples/listenForMessages.js) the recommended way, which is adding a `.on()` handler for receiving messages in callbacks. There's more info on [the docs page for pull](https://cloud.google.com/pubsub/docs/pull#node.js).

**Comment by RezaRahmati** [comment]
@feywind Thank you for providing sample, but that is not streamingPull, that sample is pulling data every 1 second, I am working on an application that the latency needed to be less than 50ms, so I needed to really stream messages instead of pulling every x seconds

**Comment by kamalaboulhosn** [comment]
@feywind  Ah yes indeed, I missed it. @RezaRahmati is there a reason you can't use the client library that uses streaming pull internally? What is referred to as "asynchronous pull" in the documentation currently is streaming pull: https://cloud.google.com/pubsub/docs/pull#node.js. There will be an update to the documentation soon that makes this more clear.

**Comment by RezaRahmati** [comment]
@kamalaboulhosn I see what you are saying, let me try that.
I think the confusion comes from this part of documentation, it explicitly saying there are two different api for receiving the message, pull and streamingPull, so based on that I was only looking for streamingPull api.

![image](https://user-images.githubusercontent.com/10086092/167628031-8392b5e1-62fd-4257-b6de-855bfe2aee57.png)

**Comment by feywind** [comment]
Yeah, streaming pull is the one that is best to use if you're able. The one called "pull" in this is synchronous pull, where you basically ask the library to grab messages in a blocking way. Streaming pull opens a persistent connection and uses whatever runtime mechanism is appropriate (in the case of Node, an EventEmitter that sends "message" events) to get those to you as quickly as possible.

**Comment by RezaRahmati** [comment]
@feywind Thank you, so is there an example of how to use streamingPull with this library? there is a public method for it in this lib called `streamingPull` not sure how to use it.

**Comment by feywind** [comment]
> @kamalaboulhosn Looks like there's a support ticket a few comments up?
> 
> @RezaRahmati [This is the sample for streaming pull](https://github.com/googleapis/nodejs-pubsub/blob/HEAD/samples/listenForMessages.js) the recommended way, which is adding a `.on()` handler for receiving messages in callbacks. There's more info on [the docs page for pull](https://cloud.google.com/pubsub/docs/pull#node.js).

Responding to this real quick, the sample quoted above is correct, and the "1 second" aspect is just a timeout the sample itself uses before exiting. All messages should pull at maximum speed for that one second. (You can have other terminating conditions besides a timeout.)
