### ISSUE TITLE
Library is unavailable

### ISSUE THREAD

**Issue by dermasmid** [googleapis/nodejs-pubsub#1539]
the latest version was not properly published to npm
`npm install @google-cloud/pubsub@^2.19.0`
tries to install `2.19.2` but fails with
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.2.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@google-cloud/pubsub@https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.2.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```
interestingly 2.19.1 is available for download here https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.1.tgz
but https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-2.19.2.tgz gives a 404. while on npm 2.19.1 does not show up in the versions section

**Comment by GaneshBaronAloir** [comment]
BUMP I get the same error

**Comment by jilherme** [comment]
same here :(

**Comment by leonidasv** [comment]
Broke our CI pipeline here (when installing `firebase-tools`) :(

**Comment by daltonscharff** [comment]
Here's a temporary workaround that's working for our team:
`npm install --save-dev @google-cloud/pubsub@2.7.0 firebase-tools@9.23.2`

**Comment by martins20** [comment]
Same Here guys

**Comment by scrimmie** [comment]
BUMP I am receiving this issue as well

**Comment by Jacobsmi** [comment]
BUMP, seeing the same issue

**Comment by martins20** [comment]
Guys, the version 2.19.0 works !

`npm install @google-cloud/pubsub@2.19.0`

**Comment by leonidasv** [comment]
For those using `firebase-tools` as a global package: 
```bash
npm install --global @google-cloud/pubsub@2.19.0 firebase-tools
```

**Comment by purejgleason** [comment]
2.19.2 Is not working again, 2.19.0 still seems to work

**Comment by purejgleason** [comment]
https://www.npmjs.com/package/@google-cloud/pubsub/v/2.19.0 > fine
https://www.npmjs.com/package/@google-cloud/pubsub/v/2.19.2 > 404

**Comment by feywind** [comment]
The release machinery was having some trouble with flaky builds. 2.19.3 should be working:

https://www.npmjs.com/package/@google-cloud/pubsub/v/2.19.3

**Comment by feywind** [comment]
It looks like this is working for everyone? Please feel free to comment if it's still causing problems.

Also thanks to everyone for jumping in and giving workarounds :)
