### ISSUE TITLE
Typescript transpilation fails

### ISSUE THREAD

**Issue by vuesomedev** [googleapis/nodejs-pubsub#1548]
After upgrading the library from `2.19.0` to `2.19.3` the Typescript transpilation started to fail with the following error message

```
node_modules/@google-cloud/pubsub/build/protos/protos.d.ts:15:23 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

15 import * as Long from "long";
                         ~~~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:17:23 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

17 import * as Long from 'long';
                         ~~~~~~

node_modules/google-gax/build/protos/operations.d.ts:17:23 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

17 import * as Long from 'long';
                         ~~~~~~


Found 3 errors in 3 files.
```

#### Environment details

  - OS: macOS Monterey 12.3.1
  - Node.js version: 14.17.4
  - npm version: 6.14.14
  - `@google-cloud/pubsub` version: 2.19.3

#### Steps to reproduce

  1. Install `typescript` and `@google-cloud/pubsub` latest
  2. 
```
import { PubSub, Topic } from '@google-cloud/pubsub';
console.log(PubSub, Topic);
```
  3. Transpile the above code with latest Typescript

Created an [example repository](https://github.com/vuesomedev/pubsub-error-repro), just have to clone, install and run `npm run build`.
Setting the flag `esModuleInterop` to `true` doesn't solve the issue.

**Comment by angishen** [comment]
I'm also getting these compile errors after upgrading to `2.19.3`. However, I continue getting the errors even when I revert back to `2.19.0` and as far back as `2.18.4`. This is with TS version 4.6.4.

On versions `2.18.3` and earlier, I get a different compile error:
```
node_modules/@google-cloud/pubsub/build/src/message-stream.d.ts:83:5 - error TS2416: Property 'destroy' in type 'MessageStream' is not assignable to the same property in base type 'PassThrough'.
  Type '(error?: Error | null | undefined) => void' is not assignable to type '(error?: Error | undefined) => this'.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

83     destroy(error?: Error | null): void;
```

**Comment by angishen** [comment]
I'm able to get rid of the compile errors if I manually go into the listed files in my node_modules and change the erroring  imports into default imports:
```
import Long from "long"
```

**Comment by vuesomedev** [comment]
Maybe hardcoding the Long version to v4? https://github.com/dcodeIO/long.js/issues/109

**Comment by vuesomedev** [comment]
For a temporal solution, this worked in `package.json`:
```
"overrides": {
  "long": "4.0.0"
}
```

**Comment by feywind** [comment]
Hmm, this looks like it might be related to the effort to update from Node 10. @bcoe ?

**Comment by stevanmilic** [comment]
Looks fixed with https://github.com/googleapis/nodejs-pubsub/releases/tag/v2.19.4

**Comment by feywind** [comment]
Ah right, it was probably related to this: https://github.com/grpc/grpc-node/pull/2110
