### ISSUE TITLE
Can this be used for Pub/Sub Lite?

### ISSUE THREAD

**Issue by GordonCode25** [googleapis/nodejs-pubsub#1612]
Can this be used for Pub/Sub Lite?

There doesn't seem to be a separate lite library for node.

**Comment by feywind** [comment]
@GordonCode25 Sadly no, Lite has a completely different API, and the only libraries for it are for Python and Java. I did generate one a while back for Node, for testing, but it was really unfriendly to use. I'll mention in this week's meeting that you are interested, though.

**Comment by GordonCode25** [comment]
Thanks, seems like it would be a really good cost effective solution for talking between multiple instances.

**Comment by clieee** [comment]
any updates on this one?

**Comment by feywind** [comment]
Unfortunately I don't think this one is going to happen.

@kamalaboulhosn What's the official word on this stuff now?

**Comment by kamalaboulhosn** [comment]
At this point, it is not our intention to make a Pub/Sub Lite library for Node.
