### ISSUE TITLE
Topic.flush() returns immediately, before all items are published

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1620]
`Topic.flush()` is promisified, so it returns either a Promise or takes a callback, depending on how it's called. This calls `Publisher.flush()`, which likewise can deal with Promises. However, `MessageQueue.publish()`, which `Publisher.flush()` calls, does _not_ support Promises, only callbacks. But `Publisher.flush()` is expecting it to support Promises, so no callback is passed down, and `Publisher.flush()` gets back undefined, which passes through as a resolve, and no wait happens.

**Comment by feywind** [comment]
Relevant code bit: https://github.com/googleapis/nodejs-pubsub/blob/main/src/publisher/message-queues.ts#L162

**Comment by baeminbo** [comment]
A public issue tracker is created for this issue: https://issuetracker.google.com/issues/246207643

**Comment by feywind** [comment]
Actually, a related issue: https://github.com/googleapis/nodejs-pubsub/issues/1463

**Comment by feywind** [comment]
I think I was looking at the wrong branch or something, because this does actually promisify the calls: https://github.com/googleapis/nodejs-pubsub/blob/main/src/publisher/index.ts#L113

That was fixed by this PR: https://github.com/googleapis/nodejs-pubsub/commit/e494fb7303ae58b08f3f75aa87ea1f10c86f648e

...which would've been in release 2.9.0.

So I need to re-study the original problem and see if there's something else.

**Comment by feywind** [comment]
I found some possibilities. Please give this a try and see if it does what's needed, and if not, I'll reopen.
