### ISSUE TITLE
enableExactlyOnceDelivery doesn't work in the emulator

### ISSUE THREAD

**Issue by modestaspruckus** [googleapis/nodejs-pubsub#1646]
#### Environment details

  - OS: MacOs 12.6
  - Node.js version: 16.17.1
  - npm version: 8.19.1
  - `@google-cloud/pubsub` version: 3.2

#### Steps to reproduce
I've followed steps on https://github.com/googleapis/nodejs-pubsub/commit/998de35d4bffde4fcffd217347307c04031df3e2#diff-e94e8edef47e761ba16b40144b0f5b89f0a20de0a051500a50c43e4574178c80
  1. Create `PULL` subscription with enableExactlyOnceDelivery flag
  2. Variable `this._subscriber.isExactlyOnceDelivery` is undefined on `subscriber.js` file
  
  
![image](https://user-images.githubusercontent.com/26200870/195401861-a90503ab-135a-490f-aa24-11508c70fdd4.png)

![image](https://user-images.githubusercontent.com/26200870/195399856-323665a8-de30-4c64-8db1-beb9831d2904.png)

I'm using pub/sub emulator

**Comment by feywind** [comment]
@modestaspruckus Hi, thanks for the question. Unfortunately I don't think the emulator currently supports exactly-once delivery emulation. I'll put this on the agenda for tomorrow to ask if there are plans there.

Are you seeing the same issue against the real service, or is it just the emulator?

**Comment by modestaspruckus** [comment]
Hi,
Thanks for fast reply. Good to know that the problem is only on emulator.
I haven't tried yet without it on production environment.

**Comment by feywind** [comment]
It sounds like there's a new emulator release in the works.

**Comment by hongalex** [comment]
Confirmed that emulator now support exactly once.
