### ISSUE TITLE
Should we use "await message.ack()" instead of "message.ack()" in the normal usages?  

### ISSUE THREAD

**Issue by grimmer0125** [googleapis/nodejs-pubsub#1653]
I saw many example codes are just use `message.ack()`. But `ack` and `nack` are both promise based. So 
1. Should we use `await message.ack()` instead, or it depends on different use cases? 
2. If using it, what are the possible downsides? For example, will it take a longer time (e.g. 10s) to finish "await message.ack()" and get the callback after a while?

**Comment by feywind** [comment]
@grimmer0125 In the case of subscriptions that do not have exactly once delivery enabled, there is actually nothing to wait on. These will always return immediately with no Promise.

For ackWithResponse and friends, these do actually return useful info (or exceptions) when you have exactly once delivery enabled. But if it's not enabled, they basically do the same thing as the others, returning a no-op Promise:

```
  async ackWithResponse(): Promise<AckResponse> {
    if (!this._subscriber.isExactlyOnceDelivery) {
      this.ack();
      return AckResponses.Success;
    }
```
So the short version is to always go without the await when using ack(), and use Promises and `await` when you're using ackWithResponse() and exactly once delivery.

**Comment by grimmer0125** [comment]
Thank you for the kind and detailed introduction. @feywind

**Comment by feywind** [comment]
Going ahead and closing this out.
