### ISSUE TITLE
"createTopic" returns a Topic with no ProjectId

### ISSUE THREAD

**Issue by julienperrault** [googleapis/nodejs-pubsub#1676]
#### Environment details

  - OS: Mac OS 13.1
  - Node.js version: 18.13.0
  - npm version: 8.19.3
  - `@google-cloud/pubsub` version: 3.2.1

#### Steps to reproduce

  1. Use the `createTopic` function on a PubSub Client
  2. The returned value (CreateTopicResponse) contain the created Topic but the topic.name value don't have the `{{projectId}}` rendered.

Exemple :
- I use in local env. the PubSub Emulator (exposed at `localhost:8085`)
- `{{projectId}}` = `julienperrault`

```typescript
import {
  PubSub,
} from '@google-cloud/pubsub'

const client = new PubSub()

const main = async () => {
  const topicName = "test-topic"

  const createdTopic = await client
    .createTopic(topicName)
    .then(([topic]) => topic)
    .catch(err => {
      if (err.code === 6) {
        return client.topic(topicName)
      }
      return err
    }
  )
  console.log(createdTopic.name)

  const foundTopic = await client.topic(topicName)

  console.log(foundTopic.name)
}

main()
```

Console : 

1. Compile (`npx tsc`)
2. Run (`npm run start` launch `PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST:-localhost:8085} node index.js`)

```bash
npm run start

> start
> PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST:-localhost:8085} node index.js

projects/{{projectId}}/topics/test-topic
projects/julienperrault/topics/test-topic
```

**Comment by feywind** [comment]
@julienperrault Thanks for the report. This isn't exactly a bug behaviour, but I think it isn't very friendly. (The same problem exists in subscription names, too.) I have a fix for it in my OpenTelemetry branch, but it might be worth pulling out into a separate PR.
