### ISSUE TITLE
Cannot read property '@google-cloud/pubsub' of undefined

### ISSUE THREAD

**Issue by burhanahmeed** [googleapis/nodejs-pubsub#1677]
I am deploying my service to GCP cloud functions but somehow I got this issue after I updated the typescript version. I am not sure if the issue is caused by a typescript upgrade because it was fine on another service.

Previously it was working fine, I only change the ts and ts-node version then running prettier.

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: npm ERR! Cannot read property '@google-cloud/pubsub' of undefined
Step #2:
Step #2: npm ERR! A complete log of this run can be found in:
Step #2: npm ERR!     /www-data-home/.npm/_logs/2023-01-20T04_28_28_755Z-debug.log; Error ID: beaf8772
Finished Step #2
ERROR
ERROR: build step 2 "[gcr.io/cloud-builders/gcloud](http://gcr.io/cloud-builders/gcloud)" failed: step exited with non-zero status: 1
```

**Cloud Build Yaml**

```
steps:
  - name: node
    entrypoint: npm
    args: ['install']
    dir: functions
  - name: node
    entrypoint: npm
    args: ['run', 'build']
    dir: functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - [redacted_service_name]
      - --region= . .. . . 
      - --set-env-vars= . . . .
      - --runtime=nodejs12
      - --source=./functions
      - --allow-unauthenticated
      - --trigger-http
```

typescript: `"^4.4.3"`
ts-node: `"^10.8.1"`

**Comment by danidaryaweesh** [comment]
I'm having the same issue here. Any help is appreciated. 

PS. I'm using node v14.

**Comment by feywind** [comment]
Hmm, interesting. I'll try a sample to see if this is breaking for me too.

**Comment by feywind** [comment]
My test here looks like it's loading the function okay, so I wonder if there's something else going on. Can both of you post some info about what's in your package.json? I'm assuming if it's going through Cloud Build, it is doing some kind of compilation step with `tsc` rather than using `ts-node`.

**Comment by danidaryaweesh** [comment]
Thanks for taking the time to look at this @feywind. Yes it's correct, the file is going through cloud build. This is my package.json file: 

`{
    "name": "xxxx",
    "description": "xxxxx",
    "scripts": {
        "lint": "eslint .",
        "test:offline": "mocha --recursive --reporter spec ./**/test.*.js --exit",
        "test:watch": "mocha --recursive --reporter spec ./**/test.*.js --watch --exit",
        "coverage": "nyc --reporter=text-summary npm run test:offline",
        "serve": "env.sh firebase emulators:start --only functions",
        "shell": "firebase functions:shell",
        "start": "env.sh && npm run shell",
        "deploy": "firebase deploy --only functions",
        "logs": "firebase functions:log"
    },
    "engines": {
        "node": "12"
    },
    "dependencies": {
        "@google-cloud/pubsub": "^3.1.0",
        "@mapbox/timespace": "^2.0.4",
        "axios": "^0.21.1",
        "bankid": "^2.0.1",
        "bcrypt": "^5.0.1",
        "body-parser": "^1.19.0",
        "busboy": "^0.3.1",
        "camelcase": "^6.0.0",
        "cookie-parser": "^1.4.5",
        "cors": "^2.8.5",
        "express": "^4.17.1",
        "firebase-admin": "^10.3.0",
        "firebase-functions": "^3.21.2",
        "geo-tz": "^7.0.1",
        "glob": "^7.1.6",
        "nanoid": "^3.1.15",
        "node-fetch": "^2.6.1",
        "node-geocoder": "^3.27.0",
        "nodemailer": "^6.4.11",
        "promise-mysql": "^4.1.3",
        "shopify-api-node": "^3.11.3",
        "shopify-token": "^4.0.4",
        "stripe": "^8.186.0",
        "uuid": "^8.3.0"
    },
    "devDependencies": {
        "chai": "^4.2.0",
        "chai-as-promised": "^7.1.1",
        "eslint": "^5.12.0",
        "eslint-plugin-promise": "^4.0.1",
        "firebase-functions-test": "^0.3.2",
        "mocha": "^8.0.1",
        "nyc": "^15.1.0",
        "sinon": "^9.0.2",
        "sinon-chai": "^3.5.0"
    },
    "private": true
}
`

**Comment by feywind** [comment]
@danidaryaweesh Oh, am I right in saying that your project isn't even using TypeScript and getting this error upon deploy?

**Comment by danidaryaweesh** [comment]
Yes that is correct @feywind

**Comment by feywind** [comment]
Hmm, I'm still not able to repro, my test that imports `@google-cloud/pubsub` seems to be deploying and running. Maybe it's a firebase problem in the deploy/build process? I'm not very familiar with that. If you have a support agreement, they could probably help better. I'm happy to try other ideas since I got my test set up.

**Comment by danidaryaweesh** [comment]
@feywind Appreciate the time you are taking to resolve the issue. It was working without issues last week. I tried removing node-modules and lock files but it still dosen't work.

**Comment by burhanahmeed** [comment]
@feywind this's not a typescript issue. I updated to the latest typescript version and it was deployed successfully.

The issue appears when I switch to node v14 (prev v12) locally and run `npm i` then deploy.

My node runtime in `cloudbuild.yaml` was `--runtime=nodejs12`. I tried to change it to `--runtime=nodejs14` but still got the same issue.

I had to move back to node 12 locally and in `--runtime=nodejs12` to get it deployed successfully.

The weird thing is that I have 3 services with very similar `package.json` and this issue only happened in one service

**Comment by feywind** [comment]
@burhanahmeed That's indeed pretty strange... maybe there was something weird going on with package-lock.json between the two Node/npm versions? If something Node 14 wrote in there confused the Node 12 `npm i`, I could see that.

**Comment by danidaryaweesh** [comment]
I was able to successfully deploy my cloud functions when I updated to node16. So it seems that the issue was node14 as @burhanahmeed pointed out

**Comment by feywind** [comment]
Can I go ahead and close this out, then? It sounds like it was something weird with the package-lock, after all.

If it's still a problem, I can try to find someone on Cloud Run to look. It sounds like the problem might be there rather than Pub/Sub.
