### ISSUE TITLE
setting promise implementation does not seem to work

### ISSUE THREAD

**Issue by bkw** [googleapis/nodejs-pubsub#17]
If I understand [the docs](https://googleapis.github.io/gax-nodejs/CallSettings.html) correctly, the following should work:

```js
const PubSub = require('@google-cloud/pubsub');
const Promise = require('bluebird');

const pubsubClient = PubSub({
  projectId: 'some-project-1234',
  promise: Promise
});

pubsubClient.createTopic('test')
  .tap(console.log);
```

... but it throws with `TypeError: pubsubClient.createTopic(...).tap is not a function`, since the returned promise is a native one and not by bluebird.

Setting `global.Promise` to bluebird makes this example work, but that's besides the point.

I also tried setting it in the option object of  the call to `createTopic()`, but that also fails.

Looking at [common/utils](https://github.com/googleapis/nodejs-common/blob/master/src/util.js#L757-L759), the promise option does not make it into the context of promisfy() there.

#### Environment details

  - OS: macOs 10.13.2
  - Node.js version: 9.2.1
  - npm version: 5.6.0
  - @google-cloud/pubsub version: 0.16.0

**Comment by stephenplusplus** [comment]
Sorry about this. For now, `global.Promise` seems to be the only workaround. I opened an issue on the repo that can help us: https://github.com/googleapis/gax-nodejs/issues/162

**Comment by callmehiphop** [comment]
@stephenplusplus I think gax actually supports custom promise libraries, but because we supply a callback in every function, I don't think it would matter even if we did set it.

**Comment by stephenplusplus** [comment]
Interesting. How can we solve this?

**Comment by callmehiphop** [comment]
I think if we just localized a `Promise` property on each object that has a callback accepting method, that would do the trick.

**Comment by stephenplusplus** [comment]
Can you show an example of that? Then I can run with it and try to implement it.

**Comment by callmehiphop** [comment]
Sure, in the `PubSub` constructor we would need something like

```js
function PubSub(options) {
  this.Promise = options.promise;
}
```

Then in all other classes, we would need to reference that property like so.

```js
function Topic(pubsub, options) {
  this.Promise = pubsub.Promise;
}
```

**Comment by stephenplusplus** [comment]
And how does that get recognized? I was thrown, because Pub/Sub isn't a GrpcService/Service.

**Comment by callmehiphop** [comment]
Well technically our promisification helper is ignorant to what base classes we use. It's just looking for a `Promise` property.

Alternatively we could update said helper to accept a Promise argument instead of looking for one on the object.

**Comment by stephenplusplus** [comment]
Ah, I see now. I'll PR shortly with the instance property solution.
