### ISSUE TITLE
latency in message publish to pubsub

### ISSUE THREAD

**Issue by ak-org** [googleapis/nodejs-pubsub#170]
Hi, 
     I am using cloud function to publish a message from cloud function to pub/sub service using node.js library. 

The package version is as following:

{
  "name": "talk2Slack6",
  "version": "0.8",
   "dependencies": {
    "@google-cloud/pubsub": "^0.19.0"
  }
}

My cloud function received the data in JSON at 20:22:00 PST but reported successful publish to pub/sub topic at 20:23:20 PST. A delay of 1 and 1/2 minute seems unusually high. 

Here is the snipped of the cloud function logs.

2018-07-08 20:23:20.572 PDT
talk2Slack6
e22x91c3qli8
Message 134376084919428 published Successfully!!

2018-07-08 20:22:00.782 PDT
talk2Slack6
e22x91c3qli8
Function execution took 281 ms, finished with status code: 200

2018-07-08 20:22:00.692 PDT
talk2Slack6
e22x91c3qli8
User : U212BDYKD posted this message - It was that which gave promise that in due time the weights should be .....

2018-07-08 20:22:00.501 PDT
talk2Slack6
e22x91c3qli8
Function execution started

Thank you for looking into it.

Ashish Kumar

**Comment by pmcnr-hx** [comment]
I've also observed one order of magnitude increase in subscription latencies going from `0.18` to `0.19`. With `0.18` we had highly predictable latencies which we lost when moving to `0.19`. I am pretty sure there was a regression somewhere in this regard. We had to pin `0.18` in our dependencies since we require low predictable latencies.

**Comment by callmehiphop** [comment]
@stephenplusplus I haven't been keeping up with Cloud Functions, but we've seen a lot of latency issues there, do you think this is related?

**Comment by stephenplusplus** [comment]
It could be, however, it sounds likes 0.19 could have introduced a regression. Are there any commits you think that could have been a factor?

**Comment by pmcnr-hx** [comment]
The unpredictable high latency is for subscriptions is still an issue several months and releases later (I've just tested with 0.22.1). This means that we're stuck with version 0.18.0 because our application requires predictable low latency. Is this issue being looked at all?

**Comment by callmehiphop** [comment]
@JustinBeckwith do we have an issue or anything to track GCF cold start performance? I think this is mostly the same as #397 otherwise.

**Comment by pmcnr-hx** [comment]
*Update*: with latest (`0.24.1`) Node.js PubSub module we're no longer having issues with high and unpredictable subscription latency.

**Comment by callmehiphop** [comment]
@pmcnr-hx that is great news, thanks for letting us know! I'm going to close #397 and we can keep this around as a GCF specific issue.

**Comment by stephenplusplus** [comment]
@ak-org just wanted to check on this since we've made some changes as the client has evolved. Is this still an issue?

**Comment by ak-org** [comment]
Hi, I haven't used the service in past few weeks. You can go ahead and close the issue. If I find something, I will report back.
