### ISSUE TITLE
Subscription maxMessages documented incorrectly

### ISSUE THREAD

**Issue by richardnias** [googleapis/nodejs-pubsub#1744]
The [docs](https://cloud.google.com/nodejs/docs/reference/pubsub/latest/pubsub/subscription) say:

> By default Subscription objects allow you to process 100 messages at the same time.

However, digging into the source code, I can see that [elsewhere](https://github.com/googleapis/nodejs-pubsub/blob/bc7e915d5afb6b0b95250324d219067928bd07f6/src/lease-manager.ts#L44) `maxMessages` is documented as being 1000:

```
 * @property {number} [maxMessages=1000] The desired number of messages to allow
 *     in memory before pausing the message stream.
 ```

And checking in [`src/default-options.ts`](https://github.com/googleapis/nodejs-pubsub/blob/bc7e915d5afb6b0b95250324d219067928bd07f6/src/default-options.ts), I can see that 1000 is indeed the correct number:

```
export const defaultOptions = {
  subscription: {
    // The maximum number of messages that may be queued for receiving,
    // with the default lease manager.
    maxOutstandingMessages: 1000,
```

So I think the docs should be updated. Happy to open a PR.

**Comment by feywind** [comment]
@richardnias Thanks for the issue. You're welcome to make a PR for the 100 comment if you like, otherwise we'll get to it in a bit. I do want to make sure what the correct number is, though.

@kamalaboulhosn This should indeed be 1000?

**Comment by danmichaelo** [comment]
Also, is this number *per stream*? When I sat it to 20, I got 100 messages unless I also set `maxStreams: 1`.

**Comment by kamalaboulhosn** [comment]
Yep, it should be 1000.

**Comment by mete89** [comment]
> Also, is this number _per stream_? When I sat it to 20, I got 100 messages unless I also set `maxStreams: 1`. Never mind, probably because `allowExcessMessages` is true by default.

When I don't set maxStreams, I get nearly 5 times of maxMessages at peak times although allowExcessMessages is false. So I wonder is this number per stream?
