### ISSUE TITLE
Update google-gax to 4.0.0?

### ISSUE THREAD

**Issue by SimonSchick** [googleapis/nodejs-pubsub#1768]
Wondering when you plan to update, we are trying to slim down dependencies and google-gax 3.6 ships a bunch of bloat, see https://github.com/googleapis/gax-nodejs/releases/tag/v4.0.0

**Comment by feywind** [comment]
Unfortunately, we can't for now:

`drop Node 12 & decouple development dependencies (https://github.com/googleapis/gax-nodejs/issues/1439)`

The wheels are in motion for dropping Node 12 here too, so once the next major happens, this upgrade will probably follow shortly.

**Comment by SimonSchick** [comment]
Given that nodejs v16 is EOL in october I find it surprising that v12 is still officially supported, unsure why you won't just release just a new major version?

**Comment by feywind** [comment]
If it were up to me, I'd happily jump straight to 16 minimum and 20 standard, but there are a bunch of deprecation and support policies we have to work with. I'm kind of frustrated about it, too -- the Node community at large has moved on already, which makes maintenance a pain.

We are in the process of [dropping 12](https://github.com/googleapis/nodejs-pubsub/pull/1774) now in our main branch, which will pull in gax 4 (which is still baking a little in spite of the `@next` version). But I don't want to cross too many wires until that's done. I'm going to see about 3.6.1 in Pub/Sub at least.

**Comment by SimonSchick** [comment]
I don't understand how releasing a new major version, which _generally_ doesn't violate support policies, is an issue, but I'm not going to pretend to know your support contracts either :)

Thank you for the explanation and for communicating this so clearly, I don't get to see this a whole lot recently!

**Comment by feywind** [comment]
Here is that Medium post, if anyone is curious: https://feywind.medium.com/major-versions-in-the-node-cloud-sdks-d5267180f429

**Comment by feywind** [comment]
This is done with the new major, yay :)

**Comment by The-Don-Himself** [comment]
Thanks @feywind 👍 , I was actually blocked by this. I know its a separate repo, but fingers crossed this follows suit soon
https://github.com/googleapis/nodejs-firestore/pull/1867
