### ISSUE TITLE
calling setOptions on subscriber does not take effect

### ISSUE THREAD

**Issue by dermasmid** [googleapis/nodejs-pubsub#1879]
if changing flowControl settings after calling .on they dont not get into effect

```
const subscription = pubSubClient.subscription(subscriptionNameOrId);
const messageHandler = message => {

  message.ack();
};

subscription.on('message', messageHandler);

// does not have any effect on flow control
subscription.setOptions({
flowControl: {
          maxMessages: 1,
          allowExcessMessages: true,
 }
})

```

**Comment by swarmiakimmo** [comment]
I was able to confirm the bug by testing the client with a local script.

**Comment by feywind** [comment]
Looks like it's not passing it down to the streaming pull subscriber stream. I'll verify what we want this to do, behaviour-wise.

**Comment by theabhinavdas** [comment]
Have the same issue. `maxMessages` doesn't work for me when using streaming pulls. Any alternative till this is fixed or would we have to do unary pulls?

**Comment by theabhinavdas** [comment]
@feywind What's also quite peculiar is that when I use options with subscriptions, it seems to square the number of `maxMessages` specified. For me, if I set this to `1`, it does in fact seem to pull only one message (as noticed in my handler). When I set `maxMessages` to `2`, it seems to pull 4 messages. When I set `maxMessages` to `3`, it seems to pull 9 messages!

```
const subscription = pubSubClient.subscription(subscriptionNameOrId, {
    flowControl: {
      maxMessages: 1
    }
});
```

**Comment by theabhinavdas** [comment]
@dermasmid from [this](https://github.com/googleapis/nodejs-pubsub/issues/1213) other issue, it seems setting `allowExcessMessages: false` in your options fixes the issue like so:

```
const subscription = pubSubClient.subscription(subscriptionNameOrId, {
    flowControl: {
      maxMessages: 1,
      allowExcessMessages: false
    }
});
```

It may additionally have something to do with you instantly ack-ing in your `messageHandler` where you'd expect StreamingPull to pull the next message?
