### ISSUE TITLE
Latest version of pub/sub library has authentication issues

### ISSUE THREAD

**Issue by vizsatiz** [googleapis/nodejs-pubsub#1887]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
No

3) Do you have a support contract? - No
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Mac OS intell
  - Node.js version: 20
  - npm version:
  - `@google-cloud/pubsub` version: 4.0.0 and above till 4.3.1

#### Steps to reproduce

  1. Integrate and try to create a topic

```
TypeError: this.auth.getUniverseDomain is not a function
    at GrpcClient.createStub (/Users/<....>/node_modules/google-gax/src/grpc.ts:418:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by feywind** [comment]
There's another issue about this, going to close this one in favour of that one:

https://github.com/googleapis/nodejs-pubsub/issues/1884

As a workaround, try `npm update` or removing node_modules and package-lock.json and `npm i` again. There is some sort of issue with minimum versions in the chain that we're working out. 4.3.1 was supposed to fix it, but it seems not to have.

**Comment by feywind** [comment]
Fixing status.
