### ISSUE TITLE
Improve retry docs. How to just enable retry with default values?

### ISSUE THREAD

**Issue by AkselAllas** [googleapis/nodejs-pubsub#1907]
[This retry sample docs](https://github.com/googleapis/nodejs-pubsub/blob/main/samples/typescript/publishWithRetrySettings.ts#L71-L102) has us "overwriting" default values.

How can I just enable retry without overwriting?

E.g. shouldn't we be using something like this in order to refrain from violating DRY?

```
import { Status } from 'google-gax'

const retrySettings = {
  retryCodes: [
    Status.ABORTED,
    Status.CANCELLED,
    Status.DEADLINE_EXCEEDED,
    Status.INTERNAL,
    Status.RESOURCE_EXHAUSTED,
    Status.UNAVAILABLE,
    Status.UNKNOWN,
  ],
```

And something similar for Backoff settings?

@feywind? 🤔

**Comment by hongalex** [comment]
Retry and backoff is enabled by default, defaults here: https://github.com/googleapis/nodejs-pubsub/blob/aba9aee0c8ecc840c150aa077892b7bb88f18eca/src/v1/publisher_client_config.json#L56
