### ISSUE TITLE
Subscriber/Subscription.close does not support promises

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [googleapis/nodejs-pubsub#212]
#### Environment details

  - OS: Linux
  - Node.js version: 7.5.0
  - npm version: 6.3.0
  - `@google-cloud/pubsub` version: 0.19.0

#### Steps to reproduce

  1. Call `subscription.close()` without a callback argument
  2. Expect to receive a promise per documentation
  3. No promise is returned

UTSL: The code for the Subscription class calls `promisifyAll` on its members, but `Subscriber`, where `close` is implemented, does not, and so close doesn't actually adhere to its JSdoc.

**Comment by stephenplusplus** [comment]
Thanks for reporting!

@callmehiphop - I can't find this method in the [public-facing docs](https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/Subscription). Is this intended to be a public method?

P.S. What's "UTSL"?

**Comment by mgabeler-lee-6rs** [comment]
> What's "UTSL"?

[Use The Source, Luke!](http://www.catb.org/jargon/html/U/UTSL.html)

**Comment by callmehiphop** [comment]
@stephenplusplus it is, I think when I moved the Subscriber code into a separate class it got lost. So my take away is that we need to promisify the Subscriber object and include a JSDoc tag to make `close` (and any other public method) show up on the docs.
