### ISSUE TITLE
Allow synchronous pull in nodejs client

### ISSUE THREAD

**Issue by kevinmstephens** [googleapis/nodejs-pubsub#214]
We are experiencing what is described in "Dealing with large backlogs of small messages" section of this doc https://cloud.google.com/pubsub/docs/pull#synchronous-pull.  

Many small messages don't get redistributed to new subscribers that are brought online and the original subscriber creates a bottleneck for getting through a large set of messages.

We would like to work around this by using synch. pull as described in the docs.

Is this something the team would consider? Is there another workaround besides moving to a client library in Java, etc that does support synch. pull?

  - OS: Linux Ubuntu
  - Node.js version: 8.9.4
  - npm version: 5.6.4
  - `@google-cloud/pubsub` version: 0.18.0

#### Steps to reproduce

  1. Start a nodejs pull subscriber.
  2. Create several million small messages on the topic.
  3. Bring on 10 other subscribers and see how messages are not evenly distributed between the old and new subscribers. The new subscribers aren't fully utilized. 
  4. Restart all subscriber processes and they will get an even distribution of messages.

**Comment by stephenplusplus** [comment]
Thanks for the issue!

@callmehiphop was this something the team originally asked us to remove? Is there a reason we cannot support this?
