### ISSUE TITLE
Single Message per Worker Default Configuration Issue

### ISSUE THREAD

**Issue by seriallos** [googleapis/nodejs-pubsub#222]
When trying to handle a single message at a time on a subscriber (flowControl.maxMessages = 1), the default maxConnections configuration results in confusing and unbalanced processing.

My use case is that I'm trying to migrate away from Kue (a job processor using Redis) onto PubSub. My application runs CPU-intensive jobs that can take minutes to run and requires pretty fast pick up of new work (I ensure I have enough workers to not have anything more than a trivial backlog).

When using `{flowControl: {maxMessages: 1}}` without changing `maxConnections`, it looks like additional messages can be queued on a worker that is already in the middle of doing work. It took me a couple of days to even realize `maxConnections` existed and changing that to 1 finally results in the expected behavior (workers are effectively load balanced).

I think this either needs to be documented a bit better and/or the default `maxConnections` should be `min(flowControl.maxMessages, 5)`

#### Environment details

  - OS: Debian / MacOS
  - Node.js version: 8.9.4
  - npm version: yarn 1.6.0
  - `@google-cloud/pubsub` version: 0.19.0

#### Steps to reproduce

Basic example app: https://github.com/seriallos/gcp-pubsub-latency-test

I ran some tests on a single machine with 1 publisher and 4 subscribers.

With the default maxConnections of 5, the behavior on the subscribers usually looks like this:

```
SUBSCRIBER: PKB_h9b8H/188674635458559: Received job, message latency: 5ms
SUBSCRIBER: o0bBtu178/188670357679290: Received job, message latency: 1,118ms
SUBSCRIBER: 0wtvY7hJv/188671534559618: Received job, message latency: 1,226ms
SUBSCRIBER: pMSV2Lj6h/188676486470813: Received job, message latency: 2,348ms
SUBSCRIBER: oOFVFxxIx/188670495080538: Received job, message latency: 6,474ms
SUBSCRIBER: Qs21_5b0O/188679745481304: Received job, message latency: 5ms
SUBSCRIBER: SjfAMLuMz/188675468823327: Received job, message latency: 1,116ms
SUBSCRIBER: z6_oKyWDm/188671761567719: Received job, message latency: 1,232ms
SUBSCRIBER: 3UxYERnDC/188670989134377: Received job, message latency: 2,349ms
SUBSCRIBER: RgHhPpbN8/188672115966615: Received job, message latency: 6,481ms
```

When explicitly setting `maxConnections: 1`, you get the desired load-balanced behavior:

```
SUBSCRIBER: OtvzUmJE0/188680302925787: Received job, message latency: 5ms
SUBSCRIBER: c0w-vwNq7/188671439883239: Received job, message latency: 5ms
SUBSCRIBER: WlRmye-LF/188674613449352: Received job, message latency: 5ms
SUBSCRIBER: S-WvXkixz/188684008038186: Received job, message latency: 4ms
SUBSCRIBER: nmfX-_P5K/188684135013259: Received job, message latency: 4ms
SUBSCRIBER: -YovuKOuw/188684983686746: Received job, message latency: 5ms
SUBSCRIBER: PvG3r-6xN/188680814166336: Received job, message latency: 5ms
SUBSCRIBER: T3ac0budI/188675074785575: Received job, message latency: 5ms
SUBSCRIBER: JSK9ObmNQ/188680007907905: Received job, message latency: 4ms
SUBSCRIBER: Gxr7z1fDn/188680854291692: Received job, message latency: 5ms
SUBSCRIBER: AKqYcTRQd/188676566596427: Received job, message latency: 5ms
SUBSCRIBER: QmfRWbxrg/188680571149504: Received job, message latency: 5ms
SUBSCRIBER: QyuvDWjiY/188679754779764: Received job, message latency: 5ms
```

**Comment by callmehiphop** [comment]
I'm going to close this issue, as this has been [implemented](https://github.com/googleapis/nodejs-pubsub/blob/master/src/subscriber.ts#L345) and should be released within the next day or two!
