### ISSUE TITLE
API response objects shouldn't use arrays to represent structured data

### ISSUE THREAD

**Issue by jganetsk** [googleapis/nodejs-pubsub#245]
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/global

Many response types are arrays rather than objects. For example: CreateTopicResponse is an array of size 2 where the first element is a Topic and the second element is "The full API response"

These should be members of an object rather than elements of array.

**Comment by stephenplusplus** [comment]
We have an issue for this, discussing what to do for all of our libraries: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2556

**Comment by JustinBeckwith** [comment]
👋 We're going to track this up at the master issue for now, and take this on as part of a larger all-up effort across all libraries in Q4.
