### ISSUE TITLE
Publisher class is incomplete

### ISSUE THREAD

**Issue by jganetsk** [googleapis/nodejs-pubsub#246]
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/Publisher
Publisher has 1 method: publish (which supports batching)

https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/v1.PublisherClient
v1.Publisher client has over a dozen methods, including publish (which does not support batching)

Can these APIs be combined? It would be ideal if v1.PublisherClient's publish method just supported batching, and the Publisher class could just be removed from the API

**Comment by callmehiphop** [comment]
@jganetsk what if we were to just have our Topic class extend the Publisher instead? Most of the v1.PublisherClient functionality already exists on the Topic object and I believe this is where the publishing functionality lived prior to our last major refactor.

**Comment by jganetsk** [comment]
I think I would need more details about what you are proposing to make a judgement, but sounds plausible. @theacodes What do you think?
