### ISSUE TITLE
No method for delete subscription and topic

### ISSUE THREAD

**Issue by timcash** [googleapis/nodejs-pubsub#28]
No methods for
* Deleting a topic
* Deleting a subscription
* Getting a subscription info (e.g. queue depth and messages in flight)

**Comment by stephenplusplus** [comment]
* Deleting a topic
> [topic.delete()](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.15.0/pubsub/topic?method=delete)

* Deleting a subscription
- [subscription.delete()](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.15.0/pubsub/subscription?method=delete)

* Getting a subscription info (e.g. queue depth and messages in flight)
- [subscription.getMetadata()](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.15.0/pubsub/subscription?method=getMetadata), but it won't have those metrics. @callmehiphop do we expose a way to get that stuff?

**Comment by jonparrott** [comment]
See https://github.com/googleapis/nodejs-pubsub/issues/8#issuecomment-364242782 for more details on queue depth and messages in flight.

Closing this
