### ISSUE TITLE
Publisher attempts pushing empty payload when first message published larger than maxBytes

### ISSUE THREAD

**Issue by Legogris** [googleapis/nodejs-pubsub#280]
Even if all our messages seemed to be publishing successfully and our logs looked fine, but every now and then we were seeing instances of `INVALID_ARGUMENT` for publish requests Stack Driver.
After a lot of digging it turned out that if a single message hits `maxBytes`, the publisher will attempt to publish queued messages, even if there are no queued messages.

This was made worse by the fact that when using the promise version of `publish`, errors in sending of batched messages are silenced (this is another issue that would be great to have addressed, perhaps by allowing attaching an event handler on the publisher).

I have a PR ready for this.

#### Environment details
  - OS: NixOS / ubuntu
  - Node.js version: v8.11.3
  - npm version: 5.6.0
  - `@google-cloud/pubsub` version: 0.20.1

#### Steps to reproduce
  1. Instantiate a publisher on a topic
  2. Publish single message that is larger than `maxBytes` when no messages are already queued.
  3. Publisher first attempts publishing empty payload before actually publishing message
  4. PubSub API responds with `HTTP 400` but this error is silenced.

**Comment by callmehiphop** [comment]
Closing per #281. Thanks again @Legogris!
