### ISSUE TITLE
running pm2 spikes cpu and memory

### ISSUE THREAD

**Issue by binarytracer** [googleapis/nodejs-pubsub#288]
using with
```
pm2: 3.2.2
node: 8.12.0
npm : 6.4.1
@google-cloud/pubsub: 0.20.1
os: Ubuntu 16.04.3 LTS
subscription type: pull
```

file: **subscription.js**
```js
const path = require('path');
const logger = require('debug')(`job:${path.basename(__dirname)}: `);
const PubSub = require('@google-cloud/pubsub');
const messageHandler = require('./handler');
const settings = require('../settings');

const keyFilePath = path.resolve(__dirname, './key-file.json');

// Creates a client
const pubsub = new PubSub({
  keyFilename: keyFilePath,
});

const { subscriptionName } = settings.google;

// References an existing subscription
const subscription = pubsub.subscription(subscriptionName);

logger('listening to any publication to any Businesses Notification');

subscription.on('message', messageHandler);
```

running this in pm2 initially

first
![start-1](https://user-images.githubusercontent.com/8814442/47061677-1abc0800-d205-11e8-81b6-bba8cde29632.png)

second
![second](https://user-images.githubusercontent.com/8814442/47061716-4e972d80-d205-11e8-9f2d-e104ec345f3e.png)

third
![third](https://user-images.githubusercontent.com/8814442/47061754-75556400-d205-11e8-9b8e-a6724a09f4e2.png)

fourth
![fourth](https://user-images.githubusercontent.com/8814442/47061768-88683400-d205-11e8-8834-a415ec9b2e29.png)

is there other debugging environment i should use to deepen the debugging?

thanks.

**Comment by binarytracer** [comment]
@JustinBeckwith, hold your horses. :D, in version v.0.19.x the cpu is behaving smoothly. 

It appears the v0.20x. is not sending 'message' event to the publishers, but confirmed to work on 0.18 and 0.19. Or do i have to create another issue for this one?

**Comment by callmehiphop** [comment]
@binarytracer would you mind re-testing this against our latest release (`v0.23.0`)?

**Comment by callmehiphop** [comment]
@binarytracer I just made a [release](https://github.com/googleapis/nodejs-pubsub/pull/452) (`0.24.0`) that should resolve the issue you're seeing. If you continue to encounter this issue, please let us know! Thanks again for the detailed report!
