### ISSUE TITLE
Subscriber stops acknowledging messages after running for a few minutes

### ISSUE THREAD

**Issue by benhunt29** [googleapis/nodejs-pubsub#29]
I have sort of a weird issue and explaining it is somewhat difficult so please bear with me. It sounds very similar to an issue I read on the python pubsub github page (https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4274). 

I have a worker service on App Engine that I'm using to pull messages off of a PubSub topic, it is just listening to the topic and when it receives a message, it pushes it to an ElasticSearch instance that I have. I have set the minimum number of instances of the worker to a high number (20) to attempt to process a large number of records in the queue. The issue is that it seems on initial startup of the instances, they process and acknowledge a bunch of records but after a while stop acknowledging them (see the images below, the large spikes in the acknowledge graph seem to correspond to deployments/restarts of the worker instances).

<img width="1917" alt="screen shot 2018-01-03 at 4 06 32 pm" src="https://user-images.githubusercontent.com/6341431/34571255-a429e8cc-f133-11e7-9281-6c019de01b36.png">
<img width="1910" alt="screen shot 2018-01-03 at 4 05 13 pm" src="https://user-images.githubusercontent.com/6341431/34571256-a43d2220-f133-11e7-9c7c-73d6f4c9df31.png">

I have attached my code, the subscription listener is invoked by calling the subscribe method in PubSubSerice.js in worker.js, I've attached the relevant portions of worker.js.

Any help is greatly appreciated!

// worker.js
```
pubSubService.subscribe('driver-log-sync', 'driver-log-sync', pubSubService.syncDriverLog)
pubSubService.subscribe('driver-log-sync-delete', 'driver-log-sync-delete', pubSubService.syncDriverLogDelete)
pubSubService.subscribe('hos-event-history-sync', 'hos-event-history-sync', pubSubService.syncHosEventHistory)
```

// PubSubService.js
```
const Pubsub = require('@google-cloud/pubsub')
const LoggingService = require('./loggingService')
const DriverLogsService = require('./driverLogsService')
const path = require('path')
const PQueue = require('p-queue')

let config = {
  projectId: process.env.GCLOUD_PROJECT
}

const pubsub = Pubsub(config)

const queue = new PQueue({concurrency: 4})

function subscribe (topicName = '', subscriptionName = '', cb) {
  function handleMessage (message) {
    message.data = message.data.toString('utf-8')
    cb(null, message)
  }
  function handleError (err) {
    console.log('ERR')
    LoggingService.error(err)
  }
  if (subscriptionName !== '' && topicName !== '') {
    let topic = pubsub.topic(topicName)
    let subscription = topic.subscription(subscriptionName)
    subscription.on('message', handleMessage)
    subscription.on('error', handleError)
    LoggingService.info(`Listening to topic ${topicName} via subscription ${subscriptionName}`)
  } else {
    cb(new Error('Missing topic name and/or subscription name.'))
  }
}

async function syncDriverLog (err, message) {
  try {
    if (err) {
      throw new Error(err.message)
    }
    let { dotNumber, logDate, driverId } = message.attributes
    if (!dotNumber) {
      throw new Error('Missing DOT number for driver-log-sync')
    }
    if (!logDate) {
      throw new Error('Missing Log Date for driver-log-sync')
    }
    if (!driverId) {
      throw new Error('Missing Driver Id for driver-log-sync')
    }
    queue.add(async () => {
      try {
        await delay(25)
        await DriverLogsService.syncDriverLogToElasticSearch(dotNumber, logDate, driverId, (new Date(message.publishTime).getTime()))
        message.ack()
        LoggingService.log(`Successfully synced log for driver: ${driverId}, dotNumber: ${dotNumber}, logDate: ${logDate}`)
      } catch (err) {
        message.ack()
        LoggingService.error(`Error syncing log to ElasticSearch for driver: ${driverId}, dotNumber: ${dotNumber}, logDate: ${logDate}`, err)
      }
    })
  } catch (err) {
    message.ack()
    LoggingService.error(`Error syncing log to ElasticSearch for message: ${message.attributes}`, err)
  }
}

async function syncDriverLogDelete (err, message) {
  try {
    if (err) {
      throw new Error(err.message)
    }
    let { dotNumber, logDate, driverId } = message.attributes
    if (!dotNumber) {
      throw new Error('Missing DOT number for driver-log-sync')
    }
    if (!logDate) {
      throw new Error('Missing Log Date for driver-log-sync')
    }
    if (!driverId) {
      throw new Error('Missing Driver Id for driver-log-sync')
    }
    queue.add(async () => {
      try {
        await delay(25)
        await DriverLogsService.deleteDriverLogFromElasticSearch(dotNumber, logDate, driverId)
        message.ack()
        LoggingService.log(`Successfully deleted log for driver: ${driverId}, dotNumber: ${dotNumber}, logDate: ${logDate}`)
      } catch (err) {
        message.ack()
        LoggingService.error(`Error deleting log for driver: ${driverId}, dotNumber: ${dotNumber}, logDate: ${logDate}`, err)
      }
    })
  } catch (err) {
    message.ack()
    LoggingService.error(`Error syncing log to ElasticSearch for message: ${message.attributes}`, err)
  }
}

async function syncHosEventHistory (err, message) {
  try {
    if (err) {
      throw new Error(err.message)
    }
    let { hosEventHistoryNodeId, driverId } = message.attributes
    let { hosEvent } = JSON.parse(message.data)
    if (!hosEventHistoryNodeId) {
      throw new Error('Missing HOS Event History Node Id for hos-event-history-sync')
    }
    if (!hosEvent) {
      throw new Error('Missing HOS Event for hos-event-history-sync')
    }
    if (!driverId) {
      throw new Error('Missing User Id for hos-event-history-sync')
    }
    queue.add(async () => {
      try {
        await delay(25)
        await DriverLogsService.syncHosEventHistoryToElasticSearch(hosEventHistoryNodeId, hosEvent, driverId, (new Date(message.publishTime).getTime()))
        message.ack()
        LoggingService.log(`Successfully synced history for driver: ${driverId}, historyNodeId: ${hosEventHistoryNodeId}`)
      } catch (err) {
        message.ack()
        LoggingService.error(`Error syncing log to ElasticSearch for message: ${message.attributes}`, err)
      }
    })
  } catch (err) {
    message.ack()
    LoggingService.error('Error syncing log to ElasticSearch', err)
  }
}

function delay (dur) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, dur)
  })
}

module.exports = {
  subscribe,
  syncDriverLog,
  syncDriverLogDelete,
  syncHosEventHistory
}
```

#### Environment details

  - OS: App Engine (Linux Debian Jessie)
  - Node.js version: 8.4.0
  - npm version: 5.3.0
  - @google-cloud/pubsub version: 0.14.2

**Comment by stephenplusplus** [comment]
@callmehiphop any ideas?

**Comment by callmehiphop** [comment]
We've seen similar reports in the past and the Python team recently identified an issue with gRPC that can max out CPU usage to 100% which can cause it to become unresponsive. We can keep this open, but I would suggest tracking https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4600

**Comment by jonparrott** [comment]
@benhunt29 are you able to reproduce this with the latest version of grpc?

**Comment by ctavan** [comment]
> The issue is that it seems on initial startup of the instances, they process and acknowledge a bunch of records but after a while stop acknowledging them (see the images below, the large spikes in the acknowledge graph seem to correspond to deployments/restarts of the worker instances).

@benhunt29 I've seen exactly this behavior with a node process that consumes from PubSub and writes to BigQuery, in my case running on Kubernetes Engine. If I allow it to consume PubSub messages too quickly, it will use 100% of available CPU and become unresponsive.

Have you checked whether your process consumes the entire available CPU?

I suggest running node processes at a maximum of 80% of available CPU, otherwise they tend to become unreliable and show unexpected IO-behavior.

Have you tried setting `flowControl.maxMessages` to a moderate value in the subscriber options? I was able to tune this value such that my process was using around 80% of the available CPU yielding optimal throughput. In my case I yield optimal results with `maxMessages = 500`. Setting the value higher would result in the behavior you describe here (i.e. start with a higher throughput but then quickly drop to zero), setting the value lower results in lower throughput (and less CPU usage).

I doubt that there's anything this library could do. I believe it's up to the application using this library to ensure the node processes don't get overloaded.

**Comment by benhunt29** [comment]
@ctavan Thanks for your suggestion, it doesn't look like my instances were getting over 40% CPU Utilization so I doubt that's the problem.

@jonparrott I upgraded to the latest version of this package and it seems to be working as I expect now. Thanks for your help!

**Comment by callmehiphop** [comment]
@benhunt29 thanks for the update! Please let us know if you start to experience any more issues.
