### ISSUE TITLE
Error: keys that don't end with '-bin' must have String values

### ISSUE THREAD

**Issue by ils-sapnaj** [googleapis/nodejs-pubsub#308]
#### Environment details

  - OS: windows 10
  - Node.js version: 6.11.2
  - npm version: 3.10.10
  - `@google-cloud/pubsub` version: 0.20.1

#### Steps to reproduce
Here is my package.json

```json
"dependencies": {
    "@google-cloud/storage": "^2.0.3",
    "@google-cloud/pubsub": "0.20.1",
    "google-distance-matrix": "^1.1.1",
    "async": "^0.2.9",
    "babel-core": "*",
    "babel-istanbul": "*",
    "base-64": "^0.1.0",
    "base64url": "2.0.0",
    "bluebird": "^3.5.1",
    "body-parser": "~1.15.1",
    "chai": "^4.2.0",
    "connect-flash": "~0.1.1",
    "cookie-parser": "~1.4.3",
    "crypto": "^1.0.1",
    "debug": "~2.2.0",
    "ejs": "~2.5.7",
    "express": "~4.13.4",
    "express-session": "~1.14.2",
    "fs": "0.0.1-security",
    "mysql": "~2.11.1",
    "mocha": "*",
    "mocha-logger": "^1.0.5",
    "nyc": "^11.2.1",
    "properties-reader": "0.0.16"
  },
```

Here is code which to create a topic : 

```js
Object.prototype.addTopic = function(req, callback) {
	var constant = req.app.get('constants');
	const project_id = constant.GCP_PROJECT_ID;

  	// Creates a client
  	const pubsub = new PubSub({
  		projectId: project_id
  	});

  	var topicname = "test123455";

	// Creates a new topic
  	pubsub
   	.createTopic(topicname)
    .then(results => {
     	const topic = results[0];
      	console.log(`Topic ${topicName} created.`);
      	callback(null, results);
    })
    .catch(err => {
      	console.error('ERROR:', err);
      	callback(err);
    });
}
```

After calling this function in your route to add any topic, I am getting following errors :

```
ERROR: Error: keys that don't end with '-bin' must have String values
    at validate (D:\Code Library\node_modules\google-gax\node_modules\grpc\src\metadata.js:55:13)
    at Metadata.set (D:\Code Library\node_modules\google-gax\node_modules\grpc\src\metadata.js:74:3)
    at GrpcClient.metadataBuilder (D:\Code Library\node_modules\google-gax\lib\grpc.js:181:18)
    at GrpcClient.constructSettings (D:\Code Library\node_modules\google-gax\lib\grpc.js:225:28)
    at new SubscriberClient (D:\Code Library\node_modules\@google-cloud\pubsub\src\v1\subscriber_client.js:143:28)
    at PubSub.getClient_ (D:\Code Library\node_modules\@google-cloud\pubsub\src\index.js:806:17)
    at PubSub.request (D:\Code Library\node_modules\@google-cloud\pubsub\src\index.js:827:8)
    at PubSub.createSubscription (D:\Code Library\node_modules\@google-cloud\pubsub\src\index.js:241:8)
    at PubSub.wrapper [as createSubscription] (D:\Code Library\node_modules\@google-cloud\common\src\util.js:755:29)
    at Topic.createSubscription (D:\Code Library\node_modules\@google-cloud\pubsub\src\topic.js:192:15)
```

Please help me to sort it out.

**Comment by stephenplusplus** [comment]
I think what's causing the weird error is putting the `addTopic` method on the `Object` prototype. If you take that part out, can you see what happens?

**Comment by ils-sapnaj** [comment]
I have removed and updated code like this : 

app.post('/addTopic', function(req, res) {
    var response;
    var jresp;
    var fs = require("fs");
    const PubSub = require(`@google-cloud/pubsub`);
    if(req.body.data) {
        
            var util = req.app.get('util');
                var constant = req.app.get('constants');
                const project_id = constant.GCP_PROJECT_ID;

                // Creates a client
                const pubsub = new PubSub({
                    projectId: project_id,
                    keyFilename: './GCP_credential.json'
                });

                var topicname = "test";

                // Creates a new topic
                pubsub
                .createTopic(topicname)
                .then(results => {
                    const topic = results[0];
                    console.log(`Topic ${topicName} created.`);
                })
                .catch(err => {
                    console.error('ERROR:', err);
                });

            
                response = {
                    "status": prop.get('Success'),
                    "data" : "",
                    "msg" : prop.get('pub_sub_topic_created')
                }               
                jresp =response;
                res.json({"res":jresp});
                        
        }

})

Still I am getting same error

**Comment by stephenplusplus** [comment]
Would you mind putting together a small reproduction test case, that I can clone and install? Something consistent that can reproduce the error, with the minimum amount of dependencies necessary (preferably, just `@google-cloud/pubsub`).

**Comment by callmehiphop** [comment]
@ils-sapnaj are you still experiencing this issue?
