### ISSUE TITLE
Enable noImplicitAny in the tsconfig

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-pubsub#313]
The goal here is to provide perfect TypeScript types for customers using the module.  Generally when doing this work I like to:

1. enable `noImplicitAny` in the tsconfig
2. Choose a single file to get passing, and fix all errors in that file (using VSCode here is really useful)
3. disable`noImplicitAny`
4. Get all the tests passing
5. Submit a PR for just the single file I updated
6. Repeat until finished

It's *a lot* easier if we do a PR per file on this one.

**Comment by praveenqlogic** [comment]
#https://github.com/googleapis/nodejs-pubsub/pull/457
