### ISSUE TITLE
API Documentation link broken

### ISSUE THREAD

**Issue by joemanfoo** [googleapis/nodejs-pubsub#33]
The link for [Cloud Pub/Sub Node.js Client API Reference](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/latest/pubsub)

redirects to 
https://cloud.google.com/nodejs/docs/reference/libraries

**Comment by stephenplusplus** [comment]
cc @jmdobry @alexander-fenster

**Comment by jmdobry** [comment]
It may take some time for folks' caches to update, but https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/latest/pubsub works for me now

**Comment by ncjones** [comment]
It's broken again.
