### ISSUE TITLE
PubSub Emulator Error With pubsub.v1.SubscriberClient()

### ISSUE THREAD

**Issue by watsab** [googleapis/nodejs-pubsub#346]
Hi !

I'm trying to pull the messages from a PubSub topic using the PubSub Emulator.
At first I used the asynchronous method which worked fine but was not what I really wanted.
So I switched to synchronous pull of messages as explained in the documentation here: https://cloud.google.com/pubsub/docs/pull?hl=FR#synchronous-pull

However I can't get it to work. It keeps throwing the followin error:

```
node:261) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
at GoogleAuth.<anonymous> (/var/code/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
at step (/var/code/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
at Object.next (/var/code/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
at fulfilled (/var/code/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```

Is it not possible to use the pubsub.v1.SubscriberClient component with PubSub Emulator without specifying credentials?
Thanks!

Below are all the technical details

#### Environment details

  - OS: Linux/Docker
  - Node.js version: 8.12
  - npm version: 6.4.1
  - `@google-cloud/pubsub` version: 0.20.1

#### Steps to reproduce
  1. Launch PubSub Emulator
  2. Call pubsub.v1.SubscriberClient();

**Comment by watsab** [comment]
Hi ! 
Update: I have the same issue with the v1.PublisherClient. Are the v1 modules not compatible with Pubsub Emulator ? If not, it would be great to work on this to allow development on local machines. Thanks !

**Comment by callmehiphop** [comment]
Hi @watsab I believe all the v1 modules are compatible with the PubSub emulator. However IIRC both the Subscriber and Publisher clients will need to be configured to use the emulator like so

```js
const sub = pubsub.v1.SubscriberClient({
  servicePath: 'path.to.your.emulator',
  port: 8080, // port your emulator is running on (default is 443)
});
```

**Comment by watsab** [comment]
Hi @callmehiphop ! 

Thanks for your answer !
I noticed these two options but I still can't make it work with these, as it keeps asking for my credentials. FYI, I am using Docker Compose to run the app in one container and the emulator in another; so I set "servicePath" to my PubSub service name, and "port" to 8085 as it is the one used but maybe I misconfigured these options... I'll keep digging and see if I can find a way to solve this. 
What would be great, however, is for the v1 components to use the env variable "PUBSUB_EMULATOR_HOST", so we don't need to specify these options, just as the non-v1 components do ;)

Thanks again !

**Comment by watsab** [comment]
Update:
I created a service account just to try if it would work with credentials. However I have errors raising in both my PubSub container and my app Container:

> pubsub_1     | [pubsub] Dec 04, 2018 3:31:24 PM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
> pubsub_1     | [pubsub] INFO: Adding handler(s) to newly registered Channel.
> pubsub_1     | [pubsub] Dec 04, 2018 3:31:24 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
> pubsub_1     | [pubsub] INFO: Detected non-HTTP/2 connection.
> pubsub_1     | [pubsub] Dec 04, 2018 3:31:24 PM io.gapi.emulators.netty.NotFoundHandler handleRequest
> pubsub_1     | [pubsub] INFO: Unknown request URI: /bad-request
> app          | error: E1204 15:31:24.987311276     134 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.

**Comment by watsab** [comment]
Hi @callmehiphop !

do you have an idea of how I could solve the credentials issue ? I'm wasting a lot of time not being able to have a proper local dev environment :disappointed: 
Thanks !

**Comment by callmehiphop** [comment]
Sorry about that @watsab, I forgot that you also need to provide some credentials as well. I *think* the following should work

```js
const grpc = require('grpc');

const subscriber = new pubsub.v1.SubscriberClient({
  servicePath: 'path.to.your.emulator',
  port: 8080, // port your emulator is running on (default is 443)
  sslCreds: grpc.credentials.createInsecure()
});
```

**Comment by watsab** [comment]
Thanks a million @callmehiphop ! It works fine now ! Thanks so much !!!!!! :smiley:

**Comment by andykellr** [comment]
The above solution didn't work for me. Here is what I used, borrowed from the `nodejs-firestore` repo.

```
import { GrpcClient } from 'google-gax';

const grpc = new GrpcClient({} as any).grpc;
const SSL_CREDENTIALS = (grpc.credentials as any).createInsecure();

const subscriber = new pubsub.v1.SubscriberClient({
  servicePath: 'path.to.your.emulator',
  port: 8080, // port your emulator is running on (default is 443)
  sslCreds: SSL_CREDENTIALS,
});
```

**Comment by lucasalexandre-cc** [comment]
> Sorry about that @watsab, I forgot that you also need to provide some credentials as well. I _think_ the following should work
> 
> ```js
> const grpc = require('grpc');
> 
> const subscriber = new pubsub.v1.SubscriberClient({
>   servicePath: 'path.to.your.emulator',
>   port: 8080, // port your emulator is running on (default is 443)
>   sslCreds: grpc.credentials.createInsecure()
> });
> ```

If you got ```TypeError: Channel credentials must be a ChannelCredentials object```, try this code:

```js
const {v1} = require('@google-cloud/pubsub');
const grpc = require('@grpc/grpc-js');

const subClient = new v1.SubscriberClient({
  servicePath: 'localhost', //path of your emulator
  port: '8085', //port of yout emulator
  sslCreds: grpc.credentials.createInsecure()
});
```

**Comment by confiq** [comment]
> What would be great, however, is for the v1 components to use the env variable "PUBSUB_EMULATOR_HOST", so we don't need to specify these options, just as the non-v1 components do ;)

Amen!

**Comment by feywind** [comment]
The internals of that stuff have changed a lot over time. I do agree that it would be more user-friendly for the v1 classes to just use the emulator variable, but they are uniformly generated from protos by a piece that works across all the libraries, so we can't really do it without a lot of effort specific to Pub/Sub. There are a couple of mitigating factors for now:

* I added `pubSub.getClientConfig()` that you can await on, to get a config object you can just pass in to the v1 constructor. That takes care of all the same setup as the `PubSub` class.
* I've been gently pushing for a while for us to have unified emulator / auth / etc environment variables, which _could_ theoretically work with v1 classes across all the libraries, but it hasn't gotten a lot of traction at this point.
