### ISSUE TITLE
Add proper types interface for PubSub constructor options

### ISSUE THREAD

**Issue by SkeLLLa** [googleapis/nodejs-pubsub#363]
PubSub constructor should have proper interface for options instead of `any`.

Also it will be good if `noImplicitAny` options will be set to `true` in `tsconfig.json` in order to avoid having low quality code.

**Comment by JustinBeckwith** [comment]
Greetings!  This is doable, and not terribly well documented.  Here are all of the options for auth that can go into the constructor:
https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L55

The easiest way to do this is to pass in the path to the keyfile:

```js
const pubsub = new PubSub({
  keyfileName: 'path/to/keyfile'
});
```

If you want to pass the individual fields in on your own, you can do that too!

```js
const pubsub = new PubSub({
    credentials: {
      client_email: 'your-client-email',
      private_key: 'your-private-key'
    },
    projectId: 'your-project-id'
});
```

Hope this helps!

**Comment by SkeLLLa** [comment]
Thanks.

**Comment by stephenplusplus** [comment]
@JustinBeckwith I think we're good?
