### ISSUE TITLE
Way to provide credentials through constructor

### ISSUE THREAD

**Issue by SkeLLLa** [googleapis/nodejs-pubsub#367]
There is no documentation and no examples about way how credentials could be provided to PubSub constructor. Is it available like in other googleapis projects?
E.g.:
```
const ps = new PubSub({
    projectId,
    credentials,
  });
```
Where `credentials` contain `private_key` and `client_email`.

So if there's such option, then it should be documented properly. If there's no such option, then it should be a new feature.

**Comment by stephenplusplus** [comment]
What path did you take for docs? We have this section on the PubSub constructor on the API docs page: https://cloud.google.com/nodejs/docs/reference/pubsub/0.20.x/PubSub. It lists `options` and links to [`ClientConfig`](https://cloud.google.com/nodejs/docs/reference/pubsub/0.20.x/global.html#ClientConfig), which shows `projectId`, `keyFilename`, etc.

**Comment by SkeLLLa** [comment]
@stephenplusplus I've just followed you link and didn't find anything that tells that there's a way to provide credentials object just like I showed in example in the 1st message:
```
const ps = new PubSub({
  projectId,
  credentials: {
    private_key: 'my_key',
    client_email: 'my_email',
  },
});
```

So I've asked exactly about `credentials`, not `keyFilename` because providing jsons is not an option for me.

**Comment by stephenplusplus** [comment]
`credentials` is documented here: https://cloud.google.com/nodejs/docs/reference/pubsub/0.20.x/global#ClientConfig

**Comment by SkeLLLa** [comment]
Ah, ok thanks.

**Comment by ReefBuddy** [comment]
@stephenplusplus I see the link you shared points to legacy docs. Does it still apply? Do you have an updated link for the latest?

**Comment by feywind** [comment]
@ReefBuddy I think all of that has been moved over to the .dev site now:

https://googleapis.dev/nodejs/pubsub/latest/global.html#ClientConfig

Hope that helps!

**Comment by wspringer** [comment]
I keep getting "User not authorized to perform this action." This is my ClientConfig:

```javascript
{
  projectId: <project id from service account json>,
  credentials: {
    client_email: <client email from service account json>,
    private_key: <private key from service account json>,
  },
}
```

It works fine if I relace all of that with this:

```javascript
{  keyFilename: <location of service account json> }
```

But because of some deployment restrictions, I can't use files.
