### ISSUE TITLE
Constructor does not normalize arguments in all cases

### ISSUE THREAD

**Issue by jmdobry** [googleapis/nodejs-pubsub#38]
The `PubSub` constructor function contains

```js
if (!(this instanceof PubSub)) {
  options = common.util.normalizeArguments(this, options);
  return new PubSub(options);
}
```

but that code is only activated when `PubSub` is used as a factory function. This is a problem when `PubSub` is used as a constructor, i.e. `new PubSub()`. `common.util.normalizeArguments` performs inference of the `projectId`, so when doing `new PubSub()`, it no longer recognizes your `GCLOUD_PROJECT` environment variable.

The problem of not calling `normalizeArguments` for all cases can be found in a bunch of Google Cloud Node libraries.

**Comment by jmdobry** [comment]
Here's an example:

```js
process.env.GCLOUD_PROJECT = 'my-project';
const PubSub = require('@google-cloud/pubsub');
PubSub().topic('my-topic').name; // projects/my-project/topics/my-topic
(new PubSub()).topic('my-topic').name; // projects/{{projectId}}/topics/my-topic
```

**Comment by stephenplusplus** [comment]
@callmehiphop it seems that there was a reason we didn't normalize the arguments outside of that block. Do you remember if there was one?

**Comment by callmehiphop** [comment]
If I had a guess I would say it was because at one time we only had a single module in which the only accessors for services, like PubSub, were via factory patterns. I think the ability to instantiate clients is more recent than this code and it simply got overlooked.
