### ISSUE TITLE
High and jittery subscriber latency

### ISSUE THREAD

**Issue by pmcnr-hx** [googleapis/nodejs-pubsub#397]
#### Environment details

  - OS: Alpine Linux
  - Node.js version: 10
  - npm version:
  - `@google-cloud/pubsub` versions: `0.19.0` to `0.22.0`

#### Problem description

Our applications require low, predictable, consistent message latencies. With `@google-cloud/pubsub` `0.18.0` we got exactly that: low double digit millisecond latencies (`< 20 ms` when the publisher is configured with `batching.maxMilliseconds = 10`). However, since version `0.19.0` the subscriber latencies become much more jittery, frequently jumping to over 100 milliseconds and the average latency nearly doubled. Because of this we are unable to update to any version more recent than `0.18.0` which is increasingly a problem and would like very much to be able to get the same behaviour we had with `0.18.0` with the more modern versions.

**Comment by callmehiphop** [comment]
I spent some more time digging into this and I think this might be a cold start issue. When I set `maxMilliseconds=0` and publish 5 messages, the first message almost always takes 100~200ms to complete. However subsequent requests have consistently been around 50~100ms.

@JustinBeckwith @stephenplusplus I did a little testing to see if the grpc-js would give us any gains here, but the results are pretty similar. Do we know if any of the other clients have received similar complaints?

**Comment by JustinBeckwith** [comment]
@theacodes @jadekler @jskeet @blowmage @jdpedrie

**Comment by jadekler** [comment]
I've not seen reports of this in Go. @kolea2 in java?

**Comment by jskeet** [comment]
cc @chrisdunelm who has more experience with the .NET client than I do.

**Comment by callmehiphop** [comment]
Got an update from the reporter and it looks like this issue has since been resolved (https://github.com/googleapis/nodejs-pubsub/issues/170#issuecomment-465569147). I'm going to close this, thanks for the help everyone!
