### ISSUE TITLE
Messages are retrieved before modifyAckDeadline time expires

### ISSUE THREAD

**Issue by TraxRetail** [googleapis/nodejs-pubsub#413]
modifyAckDeadline doesn't work as expected.
We are able to retrieve messages before the lock is expired:

@google-cloud/pubsub 0.22.2 (reproducible in lower versions)
nodejs 8.12.0
npm 6.5.0
linux mint 17.3
The queue default AckDeadline is 30 seconds in our code and in the cloud.

Our mocha test:
0 - send a message
0 - pulldown 1 message from subscription with 30 second deadline and it's received.
0 (later) - modifyAckDeadline by 30 seconds
25 sec  - pulldown 1 message, it is retrieved though it should be locked.

It happens with smaller numbers as well.
```
           const cp = CloudProvider({type: GCP, env: 'INT'});
            const rand = Math.random().toString(16);
            await cp.queue.sendMessage(GCP_TOPIC_QUEUE, {test: rand});

            const messages = await cp.queue.receiveMessage(GCP_QUEUE, {maxMessages: 10, waitTimeout: 2});
            const message = messages.find(m => m.data.test === rand);

            // Retrieving the message
            assert.ok(message);

            await cp.queue.extendMessageLock(GCP_QUEUE, message, {lockTimeout: 30});
            await delay(25000);
            const messages2 = await cp.queue.receiveMessage(GCP_QUEUE, {
                maxMessages: 10,
                waitTimeout: 2
            });
            const message2 = messages2.find(m => m.data.test === rand);

            // Message should not be not be here, but is retrieved (it usually don't work but sometimes it
            // does), fails here.
            assert.ok(!message2);
            // wait for the lock to be done
            await delay(5000);

            const messages3 = await cp.queue.receiveMessage(GCP_QUEUE, {maxMessages: 10, waitTimeout: 2});
            const message3 = messages3.find(m => m.data.test === rand);

            // Message should be here because `lockTimeout` is over
            assert.ok(message3);
```
extendMessageLock function
```
async function extendMessageLock(queue, message, options = {}) {
        const client = new pubSubHelper.v1.SubscriberClient({});
        const subscription = client.subscriptionPath(GCP_PROJECT_ID, queue);
        const ackDeadlineSeconds = isFinite(options.lockTimeout) ? options.lockTimeout : MESSAGE_LOCK_TIMEOUT;
        const ids = messagesToIdArray(message);

        return await client.modifyAckDeadline({subscription, ackIds: ids, ackDeadlineSeconds});
    }
```

**Comment by callmehiphop** [comment]
@TraxRetail does the rest of your `CloudProvider` class use the `v1.SubscriberClient` client?

**Comment by callmehiphop** [comment]
You might consider adjusting the `maxConnections` option. This controls the number of `StreamingPull` streams we establish with the backend. My concern is that the message might actually be redelivered before the lock is put in place

```js
const subscription = pubSub.subscription(queue, {maxConnections: 1});
```

**Comment by TraxRetail** [comment]
Tried it now, it's still inconsistent, it gets retrieved before the lock expires.
Also tried without the modifyAckDeadline and it didn't work.

**Comment by callmehiphop** [comment]
So by default the handwritten client attempts to lock messages based on the 99th percentile of acknowledge times. It is very likely that your `modifyAckDeadline` call is getting stomped on by this feature which would make the message deadline much shorter, although this does not explain the redelivery itself, just the time at which it happens.

If you want to manage the lock yourself, I would suggest using the `v1.SubscriberClient#streamingPull` method in place of the handwritten client. 

Alternatively we have a PR (https://github.com/googleapis/nodejs-pubsub/pull/388) that aims to give a finer level of control for locking messages if you'd like to give that a test run.

**Comment by TraxRetail** [comment]
The pr #388 doesn't run. 'Cannot read property '_readableState' of undefined'.
I will try streamingPull

**Comment by TraxRetail** [comment]
Are we supposed to use just v1 subscriber client OR subscriber but not both?

**Comment by callmehiphop** [comment]
@TraxRetail I think in most cases the handwritten client should fit most needs, however if you wanted to manage locks yourself then you definitely want to use `v1.Subscriber`. If you're looking for more control while receiving messages there's also a `v1.Subscriber#pull` method that you can use to poll the server for messages.

**Comment by callmehiphop** [comment]
Not with the hand written client, no. We lock all messages until they are either ack'd or nack'd. Its possible that they will be redelivered if the backend sends the messages again or if we encounter some unexpected latency.

**Comment by callmehiphop** [comment]
I agree, we could do a better job of documenting it and I believe there are efforts underway to revamp our documentation, so I'll ask that you bare with us in the mean time. I'm going to close this out, but please feel free to re-open if something else comes up!

**Comment by kir-titievsky** [comment]
@callmehiphop -- what would be the appropriate change in the docs here?  Perhaps we could contribute a PR.  I know you've got a lot going on.

**Comment by slavoroi** [comment]
1) please explain the difference between v1 code and the rest, that one is
just calling api and the other one is manual control over connections,
optimizations and cet...
2)if you want to use extend message lock (modify ack deadline) dont use the
manual subscription.on because it does it by itself and the users will
experience race conditions.
those are the most important for me.
