### ISSUE TITLE
How to define timeout?

### ISSUE THREAD

**Issue by gaastonsr** [googleapis/nodejs-pubsub#436]
Sorry for the question if this is not the appropriate place. I couldn't find an example.

How do I define a timeout? I'm using it with the emulator and I had specified the wrong port for the emulator and using `publish` wasn't working but it never timed out either. This can potentially cause `promises` to wait forever or at least a really long time. How can I define a timeout?

Thanks!

**Comment by callmehiphop** [comment]
With the latest version of PubSub you should be able to do this

```js
const topic = pubsub.topic('my-topic', {
  gaxOpts: { timeout: 1000 }
});

await topic.publish(Buffer.from('Hello, world!'));
```

Earlier version of PubSub would look like this

```js
const publisher = topic.publisher({
  gaxOpts: {timeout: 1000}
});

await publisher.publish(Buffer.from('Hello, world!'));
```

This might not resolve your issue as I believe what you're experiencing is the same as https://github.com/googleapis/gax-nodejs/issues/208. I'm going to close this as a duplicate, but feel free to subscribe to that issue. Thanks!
