### ISSUE TITLE
FlowControl MaxMessages not minded 

### ISSUE THREAD

**Issue by robertjchristian** [googleapis/nodejs-pubsub#46]
Reported this first on s/o and waited a couple days.  

https://stackoverflow.com/questions/48326756/google-cloud-pubsub-client-does-not-mind-flowcontrol-settings-as-advertised

#### Environment details

  - OS:  macOS 10.13 High sierra
  - Node.js version: 8.1.4
  - npm version: 5.0.3
  - @google-cloud/pubsub version: 0.16.2

#### Steps to reproduce

  1. Clone nodejs bookshelf example app
  2. Run local, then deploy, see that all seems to work as expected
  3.  Change background.js so that topic.createSubscription is done with {flowControl: {maxMessages: 1}}
 4.  Submit a hundred requests
 5.  See that worker tries to handle a hindred requests at once despite max messages 1 having been set.

My understanding is that one message should be let through, and a subsequent message should not be processed unless one of these conditions is met:  acked/nacked, time-out, error.  This is not the case however.

**Comment by callmehiphop** [comment]
@robertjchristian thanks for reporting! Looking at the bookshelf app's [depdenencies](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/6-pubsub/package.json#L60) it looks like they've pinned a slightly older version of PubSub. Can you verify that

1. I am referencing the correct project
2. That your installed version is >= 0.16.0

I ask because at some point there was a bug with `maxMessages`, but I believe it has since been resolved.

**Comment by robertjchristian** [comment]
You are correct.  I was using the older version.  Same issue in both versions.

Note - I mention Google Bookshelf app for easy repro.  I am using something more sophisticated but started with same background.js and pubsub lib from example.

When I debug, the “current messages” seems to always be 0, occasionally 1, despite the number of messages currently processing.  Also, not sure what is popping that message queue - I see “push” and “splice” in there, but no removal.  Emitters make it a little harder to debug… may have to add a watch later and dig a little deeper.  

In the meantime, this bug is a dealbreaker for anyone who needs to throttle messaging.

**Comment by callmehiphop** [comment]
@robertjchristian would you mind putting together a minimal example that reproduces your issue? I've tried locally but `maxMessages` appears to be functioning correctly in my tests. I should also mention we had a significant rewrite at `0.15.0`, so `maxMessages` will definitely **not** be honored on any version previous to it.

**Comment by robertjchristian** [comment]
@callmehiphop - you are right.  Upon creating a repro, I found it was an early ACK after some async calls that was causing this.  MaxMessages works as advertised.  My apologies for the red herring.
