### ISSUE TITLE
Project not using Semantic Versioning

### ISSUE THREAD

**Issue by mikesparr** [googleapis/nodejs-pubsub#467]
RE: https://github.com/googleapis/nodejs-pubsub/blob/master/CHANGELOG.md#v0230

The product docs claim to use Semantic Versioning, but you are introducing breaking changes in `MINOR` and `PATCH` releases, thus breaking people's NPM module dependencies downstream. You need to bump the `MAJOR` version if ever introducing breaking changes according to SemVer.

 * https://semver.org/

From `0.21.x` on you broke both the `topic` and the import `{PubSub}` interfaces requiring projects globally to refactor their code even though they followed best practices with locked `package.json` files.

Please follow SemVer properly and bump `MAJOR` versions if you are introducing breaking changes to libraries, especially ones you publish to NPM. Please also pass along to other cloud project teams so they can follow the rules. ;-)

Thanks gang!

**Comment by stephenplusplus** [comment]
We intend to bump to 1.0 soon enough. We're still trying to get the API to make the most sense. In the meantime, we are semver-compliant while we are pre-stable.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> \- https://semver.org/#spec-item-4

Did you run into an issue where the 0.23.0 was automatically installed in a project that was supposed to depend on 0.22.x? It could be a matter of what is in your package.json. npm respects the y of 0.y.z as a breaking change for pre-1.0 releases, so depending on `^0.22.0` is equivalent to `>=0.22.0 && <0.23.0`.

**Comment by mikesparr** [comment]
Thanks for reply. 

## Config
```
  "dependencies": {
    "@google-cloud/pubsub": "^0.21.1",
```

## Error on deploy
 * `TypeError: PubSub is not a constructor`

## Changelog
 * the changelog said you made these breaking changes in `0.23.x` but `package.json` was configured as above

## Solution
 * update code to import `{PubSub}` and drop class instantiation
 * update code and omit `.publisher()` in topic function

## Summary
If semver was followed, the config above should never have broken with that error or the changelog is incorrect. Regardless, looking forward to `1.0` soon and please make sure any breaking changes in future follow the semver `MAJOR` bump practice.

**Comment by stephenplusplus** [comment]
I understand the frustration that suddenly the app crashes in a version you didn't ask for.

@callmehiphop @JustinBeckwith can you think of a way these changes could have been made in 0.23.x, but picked up by ^0.21.1 in GCF?

**Comment by mikesparr** [comment]
If helpful, this was the output in our CI build that failed:
```
Updated property [core/project].
Updated property [container/cluster].
WARNING: Property [zone] is overridden by environment setting [CLOUDSDK_COMPUTE_ZONE=us-central1-b]
Updated property [compute/zone].
WARNING: Accessing a Kubernetes Engine cluster requires the kubernetes commandline
client [kubectl]. To install, run
  $ gcloud components install kubectl
Fetching cluster endpoint and auth data.
kubeconfig entry generated for microservice1-cluster.
===> Path: src/lead/addCampaignData
===> Function changed!
===> Function name: addCampaignData
===> Getting trigger for addCampaignData
===> Deploying trigger lead-edit
You do not currently have this command group installed.  Using it 
requires the installation of components: [beta]
Your current Cloud SDK version is: 233.0.0
Installing components from version: 233.0.0
+---------------------------------------------+
|     These components will be installed.     |
+----------------------+------------+---------+
|         Name         |  Version   |   Size  |
+----------------------+------------+---------+
| gcloud Beta Commands | 2019.01.19 | < 1 MiB |
+----------------------+------------+---------+
For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes
#============================================================#
#= Creating update staging area                             =#
#============================================================#
#= Installing: gcloud Beta Commands                         =#
#============================================================#
#= Creating backup and activating new installation          =#
#============================================================#
Performing post processing steps...
..done.
Update done!
Restarting command:
  $ gcloud beta functions deploy addCampaignData --env-vars-file ./deploy/.env.yml --source https://source.developers.google.com/projects/jacl-clienthub/repos/clienthub-cloud-functions/moveable-aliases/master/paths/src/lead/addCampaignData --memory 128MB --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource lead-edit
Deploying function (may take a while - up to 2 minutes)...
......................failed.
ERROR: (gcloud.beta.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: TypeError: PubSub is not a constructor
    at Object.<anonymous> (/user_code/lib/util.js:5:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:1:134)
    at Module._compile (module.js:577:32)
Script failed with status 1
failed to deploy
```

**Comment by callmehiphop** [comment]
Looking at our releases it looks like [`v0.21.0`](https://github.com/googleapis/nodejs-pubsub/releases/tag/v0.21.0) actually contained the breaking change you are describing, so I would think the issue you're seeing is expected.

**Comment by callmehiphop** [comment]
No breaking changes were introduced via `PATCH` as far as I can tell, you can check out the [commits](https://github.com/googleapis/nodejs-pubsub/commits/6e420e7e07cdd04ee916de329e4e533cc106bb71) here if you like.

As far as adding a disclaimer, we actually list one on the repository README

> This library follows Semantic Versioning.
>
> This library is considered to be in beta. This means it is expected to be mostly stable while we work toward a general availability release; however, complete stability is not guaranteed. We will address issues and requests against beta libraries with a high priority.

I understand dealing with a `0.x` library can be frustrating since both breaking changes and features come in the form of `MINOR` releases (per SemVer's official guidelines). Hopefully we'll make it to `1.x` soon and be able to avoid issues like this in the future 😃
