### ISSUE TITLE
Include types definitions (*.d.ts) in published package

### ISSUE THREAD

**Issue by Kilimangaro** [googleapis/nodejs-pubsub#480]
This library is builded in typescript, but the types definitions files (*.d.ts) are actually  excluded from the published package. 

The solution is to simply remove the exclusion line from the package.json

actual package.json
```json
...
   "files": [
    "build/protos",
    "build/src",
    "!**/*.d.ts",
    "!**/*.js.map",
    "AUTHORS",
    "CONTRIBUTORS",
    "LICENSE"
  ]
...
```

proposed package.json
```json
...
   "files": [
    "build/protos",
    "build/src",
    "!**/*.js.map",
    "AUTHORS",
    "CONTRIBUTORS",
    "LICENSE"
  ]
...
```

I can follow with a PR if you wish.

Regards

**Comment by callmehiphop** [comment]
@Kilimangaro for the moment we've been excluding them intentionally. Originally this client was written in pure JavaScript but we've been putting forth a solid effort to convert a number of our clients to TypeScript. I think we're still a little ways off from where we want to be with our types, but I'm optimistic that we'll have a fully typed release out this quarter. I would subscribe to https://github.com/googleapis/nodejs-pubsub/issues/141 and https://github.com/googleapis/nodejs-pubsub/issues/313 if you're interested in updates on our progress.

**Comment by SachaCR** [comment]
Is there any news on that topic somewhere?

**Comment by feywind** [comment]
@SachaCR The library is fully TypeScript now, and as far as I can tell, the types aren't being excluded anymore, so this should be good.
