### ISSUE TITLE
Unflake the system tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-pubsub#483]
The system tests are currently hella flaky.

**Comment by callmehiphop** [comment]
@kir-titievsky I've been noticing lately that sometimes when I fetch a list of snapshots, I get more than I am expecting. In my testing I create a branch new topic/subscription, so I would assume that there would be no pre-existing snapshots. After creating 1, if I list the snapshots I'm often surprised to see that there might be 2 or 3. Any ideas why this might be happening?

**Comment by callmehiphop** [comment]
Nevermind! I forgot Snapshots were global to the project, so now that we run system-tests multiple times per PR, I think what I'm seeing makes sense.
