### ISSUE TITLE
Release gRPC 1.8.x

### ISSUE THREAD

**Issue by nikkatalnikov** [googleapis/nodejs-pubsub#49]
Please, do NPM release along with 
https://github.com/googleapis/gax-nodejs/issues/173

for Alpine images support.

thank you!

**Comment by jonparrott** [comment]
@stephenplusplus @nikkatalnikov I'm taking this to mean that we need to release a new version of this package that accepts the latest version of grpc. If so, this should be done ASAP.

**Comment by stephenplusplus** [comment]
We have used 1.8.x, but have been reverting to 1.7.x in the GAX repo and common-grpc: https://github.com/googleapis/nodejs-common-grpc/pull/10

@alexander-fenster where do we stand on this? What version do we want?

**Comment by nikkatalnikov** [comment]
@jonparrott 
yes, it is correct. thank you.

@stephenplusplus 
for Alpine containers, any of 1.8.x works.

**Comment by alexander-fenster** [comment]
We still have the auth issue in 1.8.x as for now, @schmidt-sebastian was going to look at it.

**Comment by schmidt-sebastian** [comment]
GitHub issue for auth: https://github.com/grpc/grpc-node/issues/173

**Comment by stephenplusplus** [comment]
Consolidating issues to: https://github.com/googleapis/gax-nodejs/issues/188
