### ISSUE TITLE
Invalid typings

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-pubsub#507]
#### Environment details

  - OS: irrelevant
  - Node.js version: irrelevant
  - npm version: irrelevant
  - `@google-cloud/pubsub` version: 0.26.0

It looks like the typings shipped with 0.26.0 are incorrect. I can't see any difference in actual implementation nor the changelog that would explain these changes:
- `Topic.exists` has a required parameter - a callback. It should return void if provided with a callback, a promise otherwise.
- `Topic.get` returns a `Topic`, not `[Topic]` as it used to. Although I'd gladly welcome this change to the interface, it seems that it actually didn't change and still returns an array.

There might be more, I just pointed out the ones I've came across and tested.

**Comment by merlinnot** [comment]
@callmehiphop could you please reopen? Still invalid in v0.27.0

I'll make a PR to fix it, at least the parts that I use. I don't have time to go through all of the types myself.

**Comment by callmehiphop** [comment]
Sure thing, sorry about that @merlinnot, I'll make another pass through today.
