### ISSUE TITLE
API Documentation link broken - again

### ISSUE THREAD

**Issue by joemanfoo** [googleapis/nodejs-pubsub#51]
Didn't want to resurrect a zombie so creating a new issue that's the same as closed issue#33.

https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/latest/pubsub

is redirecting back to

https://cloud.google.com/nodejs/docs/reference/pubsub/0.16.x/

**Comment by jmdobry** [comment]
This is the correct behavior. https://googlecloudplatform.github.io/google-cloud-node is deprecated.
