### ISSUE TITLE
I just tried to upgrade and I am getting many cannot find type "Long" error

### ISSUE THREAD

**Issue by richtera** [googleapis/nodejs-pubsub#526]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Mac OS X
  - Node.js version: node v10
  - npm version: yarn 1.13.0
  - `@google-cloud/pubsub` version: Current 0.24.1  Tried to Upgrade to 0.27.0

#### Steps to reproduce

  1. Setup existing project using typescript
  2. Upgrade from 0.24.1 to 0.27.0

I don't know if there are other causes or setups I need to do. I have tried to add "types: ['Long']" into the compiler configuration but that didn't help. I found references to some other projects also using protobuf with similar problems, but I was unable to find a place where it presented a good solution.
I tried quite a few different approaches, but didn't get anywhere, sorry.

**Comment by callmehiphop** [comment]
Thanks for the report @richtera! Unfortunately this is an issue that can be found in a couple our libraries. I'm going to leave this issue open to make sure the fix lands in PubSub, but anyone running into this issue should subscribe to https://github.com/googleapis/nodejs-datastore/issues/345 for now.

**Comment by JustinBeckwith** [comment]
@callmehiphop can you pull over the test I added to datastore along with this fix?  Would be nice to make sure we don't mess this up again lol.

**Comment by callmehiphop** [comment]
@richtera I just cut a new release (0.28), would you mind upgrading and testing to see if your issue is resolved? Thanks!
