### ISSUE TITLE
Prettier - formatting

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-pubsub#530]
I've noticed that this library uses `gts` for formatting, but Prettier is listed as a `devDependency`. I personally prefer Prettier, so I'd be happy to contribute and introduce full support for it. Anyway, we have two options:

1) Remove Prettier and related packages from `devDependencies`.
2) Start formatting the source code using Prettier.

Let me know WDYT and I'll make a PR.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the offer!  I have some good news here.  We use a module called [`gts`](https://github.com/google/gts) for all of our TypeScript formatting.  The 1.0.0-0 release (master branch) actually switches from `clang-format` to `prettier`!  We are just waiting for Node.js 6 to go EOL next month, then all our modules will get this for free :) .

**Comment by merlinnot** [comment]
Nice! Shall we then remove explicit dependency on it? And what about ESLint config?

We might also do it altogether in a month and just keep this issue open so we don’t forget.

**Comment by JustinBeckwith** [comment]
We're going to just wait for the node 6 EOL, and cover this as part of the gts 1.0 update.

**Comment by JustinBeckwith** [comment]
Since this is a cross-cutting issue, closing this in favor of https://github.com/googleapis/google-cloud-node/issues/2842
