### ISSUE TITLE
Samples do not show best practices

### ISSUE THREAD

**Issue by mdietz94** [googleapis/nodejs-pubsub#54]
The samples that demonstrate flow control use them in a CreateSubscription RPC. This is not the recommended pattern, as users only have 1 QPS limit. It is preferred that users attempt to subscribe, and user the error handler to create the subscription if they receive NOT_FOUND from the server. Please correct samples to show this, since we have had users running this in production hit their limits when restarting or trying to scale up their jobs.

**Comment by stephenplusplus** [comment]
Please take a look at #56.
