### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-pubsub#540]
I believe [this line in message-stream.ts](https://github.com/googleapis/nodejs-pubsub/blob/955ef5f37c32334707878969f3532c843b035bf8/src/message-stream.ts#L198) could hang onto the `stream` reference longer than it needs to, causing `stream` to remain in memory.

Here's the code:

```ts
private _addStream(stream: PullStream): void {
  this._setHighWaterMark(stream);
  this._streams.set(stream, false);

  stream.on('error', err => this._onError(stream, err))
      .once('status', status => this._onStatus(stream, status))
      .pipe(this, {end: false});
}
```

The `stream` reference variable is required for the error and status event handlers to function properly. I believe the `status` event always fires, but if `error` doesn't, we end up demanding that `stream` stick around anyway.

As far as a fix, I believe we could call `stream.removeAllListeners()` after the stream ends. Alternatively, we could find a way to not require that stream reference from within the error handler.

*Note: this is all un-tested. Node's internal memory management could be smarter than my conceptualization skills. Putting this out there in case anyone can confirm there is or isn't an issue with this code.*

**Comment by callmehiphop** [comment]
@bcoe any thoughts here?

**Comment by bcoe** [comment]
@stephenplusplus @callmehiphop to validate your hypothesis, give this a shot:

```
node --prof reproduction.js
node --prof-process isolate-*.log
```

Maybe I'm telling you something you already knew? but I didn't learn until fairly recently that you could profile a script without enabling the inspector.

**Comment by callmehiphop** [comment]
I've spent some time today profiling memory usage in regards to this. My test setup involved 1 empty subscription with a `streamingPull` timeout of 15 seconds. This configuration creates 600 `streamingPull` requests after 30 minutes, which roughly translates to a subscription with the default configuration running for about 30 hours.

I tested against master and a modified version in which all `error` events get removed via stream `end` event. The memory usage in all my test runs was consistent, with no signs of a memory leak and each run peaking around 70MB by its end.

I'm happy to expand on this if anyone feels additional profiling/configurations/etc. is needed. Any thoughts @bcoe @stephenplusplus ?

**Comment by bcoe** [comment]
@callmehiphop, to me it sounds like you've proven that @stephenplusplus's sample code does not cause an immediate issue on current versions of Node.js.

@callmehiphop for when we have to perform similar profiling, is there anything that might be worth throwing into a `gist` we can use for digging into similar issues?

@stephenplusplus are you comfortable closing this?

**Comment by callmehiphop** [comment]
My code for this test case was pretty barebones really, I leaned pretty hard on other tools to collect performance metrics.

```js
const pubsub = new PubSub();
const topic = pubsub.topic('mem-test-topic');
const subscription = topic.subscription('mem-test-sub', {
  streamingOptions: {pullTimeout: 15000}
});

const duration = 60000 * 30;

async function init() {
  await topic.get({autoCreate: true});
  await subscription.get({autoCreate: true});

  setTimeout(() => subscription.close(), duration);

  return new Promise((resolve, reject) => {
    subscription
      .on('error', reject)
      .on('message', () => {})
      .on('close', resolve);
  });
}

init().catch(err => console.error(err));
```

**Comment by stephenplusplus** [comment]
@callmehiphop thanks for running the tests!

@bcoe It's probably safe, although maybe give me one more shot to test this out before we close it.

**Comment by callmehiphop** [comment]
@stephenplusplus I'm going to close this one out, but if you're test results show different results please re-open and let me know!
