### ISSUE TITLE
pubsub messages take 30 seconds to publish

### ISSUE THREAD

**Issue by fabianrindlisbacher** [googleapis/nodejs-pubsub#578]
I've created a cloudfunction which transforms a xml request into json entities and then publishes the entites to pubsub one by one. The problem is that it takes around 30 seconds (sometimes more) to publish the first entity. after the first entity is published the others are published instantly. In our dataflow we depend on fast communication times which makes this a big problem for us. I already tried to disable the batching but it had the same behaviour as before. Also i tried the same thing with python in it worked without any delay.

```
const topic = pubsub.topic("topic", {
        batching: {
            maxMessages: 1
        },
    });

    const attributes = {
        operation: operation
    };

    jsonEntities.forEach((entity) => {
        const publisher = topic.publisher;
        publisher.publish(Buffer.from(JSON.stringify(entity), attributes));

    });
    console.log(`after ${new Date().toLocaleString()}`);

    res.status(200);
```

#### Environment details

  - Node.js version: 8
  - `@google-cloud/pubsub` version: 0.28.1

Thanks!

**Comment by callmehiphop** [comment]
This is a well known issue with cold starts in cloud functions.

@JustinBeckwith for some reason I want to say there is a tracking issue for this?

**Comment by JustinBeckwith** [comment]
We have a few issues laying around to improve cold start by an order of ~1s, but nothing on the order of 30 seconds.  If we're trending that high, it's either:
a. A pure infrastructure problem with cloud functions and start time or
b. Something we're doing very wrong in the library

@callmehiphop can you try to repo this and see what happens? Even if it's a simple benchmark.

**Comment by fabianrindlisbacher** [comment]
> We have a few issues laying around to improve cold start by an order of ~1s, but nothing on the order of 30 seconds. If we're trending that high, it's either:
> a. A pure infrastructure problem with cloud functions and start time or
> b. Something we're doing very wrong in the library
> 
> @callmehiphop can you try to repo this and see what happens? Even if it's a simple benchmark.
The function is executed instantly and also manual logs are written without any delay so i think the cloudfunction isn't the problem.

**Comment by JustinBeckwith** [comment]
Oh fascinating! If the cloud function is loaded, and the library has been require'd, I don't think we have a bug or have done any investigation here.  Sounds like an adventure @callmehiphop!

**Comment by callmehiphop** [comment]
@fabianrindlisbacher could you share with us how you're authenticating the PubSub client?

**Comment by fabianrindlisbacher** [comment]
@callmehiphop not doing any custom authentication in the code. all done automatically. i've seen that this could be a problem. but then it worked with python so i thought this shouldn't be the issue.

**Comment by fabianrindlisbacher** [comment]
@callmehiphop any hints or suggestions?

**Comment by fabianrindlisbacher** [comment]
if i it like that it works just fine for some reason.

```
const topic = pubsub.topic("topic", {
        batching: {
            maxMessages: 1000
        },
    });

    const attributes = {
        operation: operation
    };

    var itemsProcessed = 0;
    messages.forEach((message) => {
        const publisher = topic.publisher;
        publisher.publish(Buffer.from(JSON.stringify(message), attributes)).then((publishRes) => {
            console.log(stockRes, new Date().toLocaleString());
            itemsProcessed++;
            if (itemsProcessed === messages.length) {
                console.log(`after $s{new Date().toLocaleString()}`);

                res.status(200).send(JSON.stringify(messages));
            }
        });
    });
```
I guess it's no issue of your library. I'll close this Issue.
