### ISSUE TITLE
feat: do not require projectId to be set in emulator

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#582]
It can be [confusing](https://github.com/googleapis/nodejs-pubsub/issues/571) for folks that `projectId` needs to be explicitly set, given that `project_id` is populated in generated credentials for a service.

It would be nice if when running in the emulator behavior was the same.

**Comment by ctavan** [comment]
This has actually been the case in earlier versions of this library. When I was upgrading from `0.18.0` to `0.28.1` (pretty big gap, I know…) I had to start configuring a `projectId` again when running with the emulator. With the ancient version I could simple leave the `projectId` undefined and that felt much more right in the local emulator setup which is meant to work without any connection to the cloud.
