### ISSUE TITLE
revert the grpc-js related type change in src/pubsub.ts

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-pubsub#595]
This change will be merged in #590 to `src/pubsub.ts`:

```
  // TODO: sslCreds is supposed to be of type ChannelCredentials.
  // Using any until google-gax changes to @grpc/grpc-js by default.
  // tslint:disable-next-line no-any
  sslCreds?: any;
```

Please don't forget to rollback when new gax with grpc-js releases.

**Comment by callmehiphop** [comment]
The PR that would have caused this ended up getting closed, so I think this is actually a non-issue now.
