### ISSUE TITLE
Switch from grpc to @grpc/grpc-js

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-pubsub#627]
**Is your feature request related to a problem? Please describe.**

`@grpc/grpc-js` has multiple advantages over `grpc`. All Google libraries are now switching to `@grpc/grpc-js`. This is the only library left that I still see a dependency on `grpc`, which is use only in tests and as a source of type definitions.

 **Describe the solution you'd like**

I'd like to see the dependency dropped and the source code to either use type definitions from `google-gax` or `@grpc/grpc-js`.

 **Describe alternatives you've considered**

I don't see alternatives.

 **Additional context**

Not applicable.

**Comment by sduskis** [comment]
Thanks for raising this issue.  We used it at one point, and then reverted in #595.  I'll follow up with @alexander-fenster and @bcoe to figure out timing of using `grpc-js` once again.

**Comment by sduskis** [comment]
@callmehiphop, would you be able to test out `grpc-js` with large messages (i.e. publish a 9MB message, and then subscribe and see the value)?  If that works, then I think we can proceed with this.  Otherwise, I think we need to create a bug for the grpc team.
