### ISSUE TITLE
Why is the default FlowControlOptions.maxExtension = Infinity?

### ISSUE THREAD

**Issue by katmatt** [googleapis/nodejs-pubsub#637]
After taking a closer look at the source code, I found that the default value for `FlowControlOptions.maxExtension`is `Infinity`: https://github.com/googleapis/nodejs-pubsub/blob/master/src/lease-manager.ts#L189

This looks very strange to me and we experienced that our javascript service consumed a lot of message without moving forward. And this default value looks very starnge to me. May be I'm missing the point here?

**Comment by callmehiphop** [comment]
Hi @katmatt, that is an excellent question! When we originally implemented the lease feature in the PubSub client, we didn't offer a `maxExtension` option at all. When the feature was later added, we felt it made sense to set the default to `Infinity` so we didn't disrupt applications that were already expecting messages to be locked forever.

**Comment by katmatt** [comment]
@callmehiphop Thanks a lot for your quick response. I almost expected this answer😄 We have similar "issues" with beta versions of our API/SDK and I can relate a lot to your reasoning😄 Never break a public beta😉
