### ISSUE TITLE
lint/docs tests appear to be breaking

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#645]
See:

https://github.com/googleapis/nodejs-pubsub/pull/641
https://github.com/googleapis/nodejs-pubsub/pull/639

It would be good to get these PRs green, so that we can star working through the backlog of open issues.

**Comment by sduskis** [comment]
@bcoe, my understanding is that "type: bug" is for customer issues, which is why I changed the category.  This is definitely a problem, and needs to be fixed.  We'll work on them

**Comment by JustinBeckwith** [comment]
👋 Regardless, master being broken is a P1 in my book.   We should address this today.

**Comment by callmehiphop** [comment]
I believe this is a duplicate of #642

**Comment by callmehiphop** [comment]
Quick fix is to just update the regex in synth.py
