### ISSUE TITLE
doc: missing link and confused by the guide

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/nodejs-pubsub#685]
Is **Pubsub#getSubscriptions** supposed to link to something on this [page](https://googleapis.dev/nodejs/pubsub/latest/Subscription.html)? 

What's the distinction here? Why would Topic#createSubscription retrieve a subscription? It sounds like it would create a subscription. 
>  Subscriptions are sometimes retrieved when using various methods:
> - Pubsub#getSubscriptions
> - Topic#getSubscriptions
> - Topic#createSubscription
> 
> Subscription objects may be created directly with:
> - Topic#subscription

**Comment by callmehiphop** [comment]
@anguillanneuf looks like a mistake to me, we should just remove it from that list entirely.

**Comment by anguillanneuf** [comment]
Topic#subscription also creates a subscription if `autoCreate` is set to `true`. 
Does the PR add the missing link? @callmehiphop

**Comment by callmehiphop** [comment]
@anguillanneuf actually `subscription.get({autoCreate: true})` creates it, `Topic#subscription` is a factory for creating Subscription objects but it doesn't create it on the backend or make any requests.

**Comment by anguillanneuf** [comment]
@callmehiphop Last I looked, `Pubsub#getSubscriptions` and `Pubsub#createSubscription` still seem to be missing hyperlinks. Might worth double-checking.
