### ISSUE TITLE
TypeError: function name.indexOf

### ISSUE THREAD

**Issue by hamptonwalker01** [googleapis/nodejs-pubsub#690]
I recently began to dive into Google Cloud Storage, and when I deploy functions with a build trigger, I receive the same error multiple times after deploying the function:
 `TypeError: function 'name.indexOf' is not a function at Function.formatName_ (/srv/functions/node_modules/@google-cloud/pubsub/build/src/subscription.js:828:18)
    at new Subscription (/srv/functions/node_modules/@google-cloud/pubsub/build/src/subscription.js:157:34)
    at PubSub.subscription (/srv/functions/node_modules/@google-cloud/pubsub/build/src/pubsub.js:698:16)
    at myFunction (/srv/functions/index.js:58:22)`. 
My code works fine locally, as I can call my functions and they run properly by sending messages to topics and subscribers, but I am not sure as to why I continue to receive this error.

#### Environment details
  - OS: Windows 10 Home x64
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/pubsub` version: 0.30.1

#### Steps to reproduce

  1. Create a function that sends a JSON message from one topic to another topic and subscriber in said topic (decodes JSON before sending message)
  2. Deploy the function with a basic build trigger (just name, args, large timeout, and allow logging)
  3. Run the function in gcp

Thanks!

**Comment by stephenplusplus** [comment]
That function (`formatName_`) is called by the constructor when trying to figure out how to translate the user's input of a Subscription name into the format the API expects. Is there a chance you are using an environment variable locally to define the subscription name, that does not exist when published? Or any other reason why when you create a Subscription object, it wouldn't have the name?

**Comment by hamptonwalker01** [comment]
Yes, I am using an environment variable locally for the subscription name and it probably does not exist when published. Is this the reason for the error occurring?

**Comment by stephenplusplus** [comment]
Yeah, it sounds like when you are trying to access the Subscription object, you're not providing a name. We usually have an error handler to catch that though. I'll take a look to see if we can throw something more helpful.

Let me know if you can get it to work when you set the subscription name when deployed.

**Comment by hamptonwalker01** [comment]
Setting the subscription name fixed the issue. Thanks!
