### ISSUE TITLE
question / suggestion about flow control

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#696]
I can't figure out from the docs, perhaps someone could clarify.

I'm trying to use flowControl to limit the number of concurrent messages that are delivered to my subscriber to 1.  It seems that I can use `flowControl` options in the creation of the subscription AND in the creation of the subscriber.  

Q1) Which do I use? (Does it matter?)  

From reading the source code I noticed the `allowExcessMessages` option, which looks useful.  But I can't see it documented [here](https://googleapis.dev/nodejs/pubsub/latest/global.html#CreateSubscriptionRequest).

Q2) Am I looking at the wrong docs!?  Or could it please be added.

There is an `ackDeadline` option, and a `timeout` option.  Whats the difference?

Q3) Can't see in the docs what time unit the `messageRetentionDuration` option is expressed in. Could this be added?

My code currently looks like this:

        const options = {
            flowControl: {
                maxMessages: 1,
                messageRetentionDuration: 10
            },
            allowExcessMessages: false,
            ackDeadline: 60
        };

        await pubsub.createSubscription(topicName, subscriptionName, options);

        const subscription = pubsub.subscription(subscriptionName, options);
        const [newSubscription] = await subscription.get({
            autoCreate: true,
            timeout: 50,
        });

        newSubscription.on(`message`, async (message) => {
            const data = JSON.parse(message.data);

It _feels_ wrong, any suggestions on a way to clean it up?

Thanks

**Comment by callmehiphop** [comment]
So I think an important distinction to make is that flow control options do not persist on the server side of things, so I might recommend only passing what is needed to create the subscription on the backend to `createSubscription`. You can see a list of available options [here](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscription).

Unfortunately there is a quirk related to TypeScript that removed the actual docs for configuring client subscriptions and the object you're looking at isn't the right one. Here's a complete list of available options with their defaults

```js
const options = {
  ackDeadline: 10,
  batching: {
    // https://googleapis.github.io/gax-nodejs/CallSettings.html}
    callOptions: {...},
    maxMessages: 3000,
    maxMilliseconds: 100
  },
  flowControl: {
    allowExcessMessages: true,
    maxBytes: os.freemem() * 0.2,
    maxExtension: Infinity,
    maxMessages: 100
  },
  streamingOptions: {
    highWaterMark: 0,
    maxStreams: 5,
    timeout: 300000
  }
};
```

I would suggest configuring a subscription with the desired flow control settings by either using the [`pubsub.subscription`](https://googleapis.dev/nodejs/pubsub/latest/PubSub.html#subscription) factory method or calling [`subscription.setOptions`](https://googleapis.dev/nodejs/pubsub/latest/Subscription.html#setOptions).

```js
const subscription = pubsub.subscription(options);
subscription.setOptions(options);
```

**Comment by anguillanneuf** [comment]
@npomfret I'm sorry for the confusion 😞 

Q1) If you want to limit the number of concurrent messages to 1, the right thing is to set `maxMessages=` like this:

```node
const subscriberOptions = {
  flowControl: {
    maxMessages: maxInProgress,
  },
};
```

Q2) There is a distinction between a Pub/Sub subscription and a Pub/Sub subscriber, which isn't quite explained the same in the Node.js client library (versus the Pub/Sub client libraries in other languages). Unlike options set on the subscription on the server side, `subscriberOptions` let us decide *how* we want to subscribe to that subscription, and `flowControl` settings are part of these `subscriberOptions`. 

Ack deadlines are 10s by default when we create a subscription. It means that Cloud Pub/Sub will try to redeliver a message (duplicate redelivery) if it hasn't gotten a message acknowledgement from us. I'm not sure if the subscriber has the power to modify this on the subscription. @callmehiphop, could you confirm? 

Subscribers have the power to modify ack deadlines for individual messages given their IDs in case it takes more than x amount of time to process those messages. If we don't modify the ack deadline on those messages, it could result in Pub/Sub sending them to us again and again. 

Q3) As @callmehiphop has shown, `messageRetentionDuration` isn't a valid `flowControl` setting. It belongs properly to subscription options, not subscriber options. 

Hope to make things clearer when we push out some updates in our documentation! And thanks for your patience!

**Comment by callmehiphop** [comment]
@anguillanneuf users can provide an ack deadline through the options that will get sent when making the initial `StreamingPull` call

```js
const options = {ackDeadline: 11}; // 11 seconds
```
