### ISSUE TITLE
Docs: `ClientConfig` not linked + bad formatting in `PubSub` examples

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/nodejs-pubsub#697]
[This code block](https://github.com/googleapis/nodejs-pubsub/blob/master/src/pubsub.ts#L207-L234) is messing up the documentation [here](https://googleapis.dev/nodejs/pubsub/latest/PubSub.html). 

- need a proper link for `Client Config` that points to its definition [here](https://googleapis.dev/nodejs/pubsub/latest/global.html#ClientConfig).
- fix hyperlinked text in the examples

**Comment by JustinBeckwith** [comment]
This should be fixed in #704
