### ISSUE TITLE
v0.16.3 comes with incompatible grpc versions

### ISSUE THREAD

**Issue by ctavan** [googleapis/nodejs-pubsub#70]
When using yarn, v0.16.3 introduced the following error for me:

```
TypeError: Channel's second argument must be a ChannelCredentials
    at ServiceClient.Client (/app/node_modules/grpc/src/client.js:472:19)
    at new ServiceClient (/app/node_modules/grpc/src/client.js:884:12)
    at /app/node_modules/google-gax/lib/grpc.js:251:12
```

The reason is that `@google-cloud/pubsub` now defines `grpc@^1.8.4` as a direct dependency   as well as `google-gax@^0.14.2`.

`google-gax@^0.14.2` however currently pins its grpc dependency to `grpc@~1.7.2`, see https://github.com/googleapis/gax-nodejs/pull/178

This altogether breaks `v0.16.3` of `@google-cloud/pubsub` and provokes the above error. Pinning `grpc@~1.7.2` back in `@google-cloud/pubsub` works as a workaround for now.

Related:
* https://github.com/googleapis/gax-nodejs/issues/173
* https://github.com/googleapis/nodejs-pubsub/issues/49

**Comment by cmdshepard** [comment]
I can confirm this as well.
This is related to issue [#31](https://github.com/googleapis/nodejs-pubsub/issues/31)
