### ISSUE TITLE
Error Handling in the Subscription MessageHandler

### ISSUE THREAD

**Issue by stoked10** [googleapis/nodejs-pubsub#727]
The Subscription extension of the EventEmitter class appears to ignore errors that happen within the messageHandler. The EventEmitter listener for 'error' and 'uncaughtException' on Subscription seems to be eaten or ignored. To test this:

```
const messageHandler = (message) => {
  throw new Error('always an error');
};

const errorHandler = (err) => {
  logger.error('caught an error, continuing on');
};

subscription.on('message', messageHandler);
subscription.on('error', errorHandler);
```

'error' doesn't catch and the app crashes, we found the only way around this is to emit the error to the app instead of throwing, then handle it at the app layer, but that is undesirable for being able to handle the errors gracefully from our pubsub codebase and is really hacky passing the app down to our subscription service.

**Comment by callmehiphop** [comment]
This seems pretty specific to @stoked10's implementation, so I don't think we need to add any samples for it.
