### ISSUE TITLE
How do I use PubSub with react native?

### ISSUE THREAD

**Issue by sombizbuzzz** [googleapis/nodejs-pubsub#742]
Hi ,
I am using @google-cloud/pubsub in react native , 
yarn add @google-cloud/pubsub 
when trying to use getting error , 

node_modules/@google-cloud/pubsub/build/src/subscription.js`: Module `events` does not exist in the Haste module map

**Comment by callmehiphop** [comment]
👋 @sombizbuzzz this module was built specifically for Node.js, so I'm not too sure how difficult it would be to get running in a react native application. It would appear that it does not have support for core Node.js modules (like `events`) so you'll probably need to shim it.

**Comment by saeromCho** [comment]
Yes, I understand your comment. Thank you guys for comment for my issue :)

**Comment by feywind** [comment]
@saeromCho This was brought up today during a meeting. I'm not sure if the specific suggested architecture in this is useful for you, but it's an example of how you might use Pub/Sub from mobile?

https://cloud.google.com/solutions/setting-up-a-pubsub-proxy-for-mobile-clients-on-gke

(Would also apply to a downloaded client on a PC, I'd guess.)

**Comment by feywind** [comment]
I'm going to go ahead and close this out, because I think the actual answer is that we don't really officially support it, and the proxy is probably the encouraged solution. Feel free to add comments though, if you find a better solution!
