### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-pubsub#752]
Noticed this happening during our system tests run. I also remember user @evilive3000 pointing out to this warning in nodejs-vision [here](https://github.com/googleapis/nodejs-vision/issues/427). 

This Node.js [issue](https://github.com/nodejs/help/issues/1051) says the default limit of the number of listeners is 10, so it might make sense to use the tracing options discussed in that issue to see where the extra listeners are coming from, and either increase the limit, or fix the problem if there is a problem.

```
  pubsub
(node:357) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    Topic
      ✓ should be listed (8399ms)
      ✓ should list topics in a stream (7639ms)
      ✓ should allow manual paging (174ms)
      ✓ should be created and deleted (5101ms)
      ✓ should honor the autoCreate option (3561ms)
      ✓ should confirm if a topic exists (206ms)
      ✓ should confirm if a topic does not exist (248ms)
      ✓ should publish a message (411ms)
      ✓ should publish a message with attributes (8738ms)
(node:357) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
      ✓ should get the metadata of a topic (191ms)
```

**Comment by merlinnot** [comment]
See https://github.com/grpc/grpc-node/issues/1027 and https://github.com/grpc/grpc-node/issues/1027#issuecomment-532852102. I was surprised it went GA with this bug in place. Unlucky v1.0.0 :)

**Comment by alexander-fenster** [comment]
Oh, thanks @merlinnot, I somehow missed that grpc-node issue. I'll close this one then in favor of the general issue.

Speaking about going GA, GA is essentially a message that this library API is stable. To have that gRPC issue is indeed unlucky, but it's a dependency, and technically is not a problem of this particular library. I hope it will be fixed soon anyway :)
