### ISSUE TITLE
PubSub: No redelivery message if I don't ack or nack message.

### ISSUE THREAD

**Issue by Royfangs** [googleapis/nodejs-pubsub#753]
Hello, I set up pubsub service for our project, and we use pull way to subscribe, everything is working fine, then we want to modify ackDeadlineSeconds option to test our flow, here comes problems.

If we don't ack or nack message, we don't receive any message no matter what seconds we set up for ackDeadlineSeconds, seems like pubsub doesn't redelivery message at all, and then we add back ack and nack, everything is working again.

My problem is:
Is this expected behavior? It looks like ackDeadlineSeconds doesn't do anything at all.
How can we modify ackDeadlineSeconds and make it work?

#### Environment details

  - OS: MacOS 10.14.6
  - Node.js version: v12.6.0
  - npm version: 6.9.0
  - `@google-cloud/pubsub` version: 0.31.1

Thanks foy any suggestions!

**Comment by callmehiphop** [comment]
👋 @Royfangs I'm not sure which version of the client you're using, but there is a configurable setting on the hand written PubSub client that will attempt to extend the ack deadline to prevent messages from being redelivered. You can configure it like so

```js
const {PubSub} = require('@google-cloud/pubsub');
const pubsub = new PubSub();
const subscription = pubsub.subscription('my-sub', {
  flowControl: {
    maxExtension: 10 // 10 seconds
  }
});
```

If you want to disable it entirely you can set it to `0`.

Please let me know if this does the trick!

**Comment by Royfangs** [comment]
@callmehiphop  Sorry, I should mention we already modify maxExtension and it doesn't work too.
Below is our code snippet:

`const {PubSub} = require('@google-cloud/pubsub');
const pubsub = new PubSub();
const createSubscriptionOptions = {
      flowControl: {
        maxExtension: 0
      },
      ackDeadlineSeconds: 20,
      expirationPolicy: {
        ttl: {
          seconds: 31536000
        }
      }
 };

const [subscription] = await pubsub.createSubscription(
        this.topicName,
        this.subscriptionName,
        createSubscriptionOptions
);`

**Comment by callmehiphop** [comment]
@Royfangs Some of the subscriber/subscription options don't actually persist to the server. Could you try out the following code and see if it helps?

```js
const createSubscriptionOptions = {
  expirationPolicy: {
    ttl: {
      seconds: 31536000
    }
  }
};

const [subscription] = await pubsub.createSubscription(
  topicName,
  subscriptionName,
  createSubscriptionOptions
);

subscription.setOptions({
  ackDeadline: 20,
  flowControl: {
    maxExtension: 0
  }
});
```

**Comment by Royfangs** [comment]
Hello, I got this error message after add seOptions as your suggestion.

(node:57369) UnhandledPromiseRejectionWarning: Error: Failed to "modifyAckDeadline" for 1 message(s). Reason:
    at /Users/royfang/Documents/zelda/node_modules/@google-cloud/pubsub/build/src/message-queues.js:201:23

But no matter our original setup or your method, we can see it actually set up ack deadline on goold cloud platform, but not working.

![Screen Shot 2019-09-24 at 2 32 13 PM](https://user-images.githubusercontent.com/44253265/65486929-56148b80-ded8-11e9-87fb-86c53f37e94e.png)

**Comment by callmehiphop** [comment]
@Royfangs would you be able to provide us with a minimal amount of code that can reproduce the issue in its entirety?

**Comment by callmehiphop** [comment]
@Royfangs sorry, maybe I mislead you a bit here. Setting `ackDeadline` via `setOptions` does not configure the ack deadline on the server like providing it at creation time would. It does 2 things

1. It configures the `stream_ack_deadline_seconds` field for all [`StreamingPull` requests](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.StreamingPullRequest).
2. It is used to configure the frequency at which the client will extend the deadline for any messages that have yet to be acked or nacked. 

Setting `flowControl.maxExtension` to 0 should prevent the deadline from being extended automatically, which in turn would cause the message to be re-delivered.

I went ahead and created a topic with a single message published to it and then used the following code to try and reproduce:

```js
async function subscribe() {
  const [subscription] = await topic.createSubscription('my-sub');

  subscription.setOptions({
    flowControl: {
      maxExtension: 0
    },
    ackDeadline: 20
  });

  subscription
    .on('error', err => console.error(err))
    .on('message', message => {
      const time = new Date().toTimeString();
      console.log(`Received message at ${time}`);
    });
}
```

However it works as expected and I'm receiving the redelivery roughly every 20 seconds without any errors. Is there anything you can think of that I should change in my sample to help reproduce the issue you are seeing?

**Comment by Royfangs** [comment]
@callmehiphop Thanks to mentioning, I know where is the problem.

The problem is I used new pubsub subscription every time I subscribe.
```
  public subscribe(task) {
// This line causes problem, so I delete it and change it to this.subscription(I encapsulated PubSub service into class, this.subscription is the subscription return by PubSub.createSubscription or get subscription.) ;
    const subscription = this.pubsub.subscription(this.subscriptionName);
    const messageHandler = async message => {
      try {
        await task();
        message.ack();
      } catch (e) {
        message.nack();
      }
    };
    subscription.on('message', messageHandler);
  }
}
```

And I need to use setOptions every times I got existed subscription, or it didn't configure stream_ack_deadline_seconds when restart project.
```
  private async getSubscription() {
    try {
      const [subscription] = await this.pubsub
        .topic(this.topicName)
        .subscription(this.subscriptionName)
        .get();
      subscription.setOptions({
        flowControl: {
          maxExtension: 0
        },
        ackDeadline: 20
      });
      return subscription;
    } catch (e) {
      console.log('error', e)
    }
  }
```

Now it works as expected, thank you so much!

**Comment by callmehiphop** [comment]
Awesome, thanks for letting us know!
