### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by amsibamsi** [googleapis/nodejs-pubsub#757]
#### Environment details

  - OS: Debian 9.11
  - Node.js version: 10.16.3
  - npm version: 6.9.0
  - `@google-cloud/pubsub` version: 1.0.0

#### Steps to reproduce

Run the following sample program with GCP project `myproject` and Pub/Sub topic `mytopic` set up and observe warnings like:

`(node:22056) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`

 ```javascript
const projectId = 'myproject';
const topicName = 'mytopic';
const {PubSub} = require('@google-cloud/pubsub');
const pubsub = new PubSub({projectId});
const topic = pubsub.topic(`projects/${projectId}/topics/${topicName}`);

async function sleep(ms) {
        return new Promise(resolve => {
                setTimeout(resolve, ms);
        });
}

function publish() {
        const data = Buffer.from(JSON.stringify({date: Date.now()}));
        topic.publish(data, function(err, mId) {
                console.log(err, mId);
        });
}

async function main() {
        for (let i = 0; i < 1000; i++) {
                await publish();
                await sleep(20);
        }
}

main();
```

Watching this program run for a while it indeed grows to 300 MB resident memory quickly. Is there indeed a memory leak, and if yes, how can it be fixed?

Also tested this with older pubsub versions like 0.30.0, 0.29.0, etc. and newest release of Nodejs 12, same issue. Is this indeed a bug in the library or related to my code?

**Comment by callmehiphop** [comment]
👋 @amsibamsi we've been seeing this issue pop up across several of our Node.js clients, I believe this is a grpc issue (https://github.com/grpc/grpc-node/issues/1027) which may or may not be resolved already.

Can you check to see if `@grpc/grpc-js@0.5.4` is installed? If it isn't, you may need to delete any lock files you might have and/or re-install your dependencies.

**Comment by amsibamsi** [comment]
Thanks, this indeed fixed the problem.

**Comment by callmehiphop** [comment]
@amsibamsi awesome, thanks for letting us know!

**Comment by ctavan** [comment]
@callmehiphop wouldn't it be appropriate to upgrade the dependency in `package.json` to `"@grpc/grpc-js": "^0.5.4",` then?

**Comment by callmehiphop** [comment]
@ctavan yep, absolutely! We'll need to make that update across the board
