### ISSUE TITLE
TypeScript compilation fails on clean repo

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-pubsub#769]
![image](https://user-images.githubusercontent.com/4015807/66143152-87b5e280-e5bb-11e9-9e12-1cb4b13491a5.png)

Looks like some dependency changed its types in an incompatible way.

Repro:
```sh
rm -rf node_modules package-lock.json
npm install
```

**Comment by sindresorhus** [comment]
Fixed in v1.2.0: https://github.com/sindresorhus/is/releases/tag/v1.2.0

**Comment by bcoe** [comment]
@sindresorhus :wave: thanks!
