### ISSUE TITLE
docs: dead link to gax CallOptions

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [googleapis/nodejs-pubsub#775]
https://github.com/googleapis/nodejs-pubsub/blob/2071954ad2deefa74e76e76e57c034cc58aae990/src/v1/publisher_client.js#L328 states the wrong link I suppose. You likely mean https://googleapis.github.io/gax-nodejs/interfaces/CallOptions.html

**Comment by stephenplusplus** [comment]
I'm probably missing something, but it seems like it's doing the right thing. The address in the docs matches the link you suggested, https://googleapis.github.io/gax-nodejs/interfaces/CallOptions.html.
