### ISSUE TITLE
StreamingPull Retries on OK

### ISSUE THREAD

**Issue by hongalex** [googleapis/nodejs-pubsub#776]
https://github.com/googleapis/nodejs-pubsub/blob/b9122763d85d08335a86559e8299c3cebfe5372a/src/message-stream.ts#L60-L71

[The gRPC "OK" code](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) indicates success and should not be retried.

**Comment by hongalex** [comment]
cc @jadekler @callmehiphop

**Comment by callmehiphop** [comment]
@hongalex thanks for bringing this up! Those specific set of codes are not passed to gax/grpc and are only used internally when trying to determine if we should continue to create new StreamingPull requests when previous ones have closed.

A side note is that as far as I know in the history of StreamingPull we've never actually received an OK response (lol). GAX configures a deadline and the only time we don't hit a deadline exceeded is when a different error occurs first.

**Comment by hongalex** [comment]
Definitely! For more context, we're actually trying to use the "OK" code in a pubsub emulator for benchmarking. If the server/emulator closed the stream (without errors), we want to use the "OK" code as an indicator to not spin up new streams in `FillStreamPool`. I can make this change if that's fine with you?

**Comment by callmehiphop** [comment]
Yeah, absolutely.
