### ISSUE TITLE
batching behaviour and promises

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#779]
The docs aren't clear about this (to me at least).  I'm trying to send messages in a batch from a cloud function.  I can't leave any code to run after the function completes so I need to know when all messages have been sent. 

I want to use batching as I'm sending a lot of messages, so I set up a publisher like this:

        const publisher = this._pubsub.topic(topicName, {
            batching: {
                maxMessages: 50,
                maxMilliseconds: maxWaitTime,
            },
        });

How do I know when all messages sent to this publisher have been published (and so it's safe to end my cloud function)?

**Comment by callmehiphop** [comment]
:wave: @npomfret we do batching under the hood automatically, if you want to know when all messages are published you could either use something like `Promise.all()` or wait for the last publish call to resolve.


```js
const promises = messages.map(message => topic.publish(message));
await Promise.all(promises);

// or

let promise;

for (const message of messages) {
  promise = topic.publish(message);
}

await promise
```

**Comment by npomfret** [comment]
Ok, thanks.  That's exactly what I'm doing.

**Comment by cbosco** [comment]
Hi, regarding the `Promise.all()` approach here, I am curious the behavior of a batch failure.

For example, if I have a batch size of `10`, and assuming that a HTTP failure would apply to an entire batch, not one discrete message, would I expect 10 of my promises to reject?

**Comment by cbosco** [comment]
Is there a better place to ask this question? I thought this context was helpful, but maybe because it's a closed issue, I should raise an issue for it?

**Comment by feywind** [comment]
@cbosco No, this is totally the right place to ask. I've just been flying solo on this repo for the most part and buried lately. My off the cuff understanding is that you'd get a failure for each message in a batch. The batching is meant to be more or less transparent.

I am actually working on something right now that will let you explicitly flush any batched messages, for closing down the client connection. I'm not sure if that will be useful for you, but I figured I'd mention it while I'm on the topic of the original issue. :)

**Comment by cbosco** [comment]
@feywind Thanks this sounds like my assumption, so whatever fails with regard to the batch, any individual message callback (or promise) gets called/rejected as if there was no batch mediating it? The PR was helpful to look at!
