### ISSUE TITLE
begin testing @grpc/grpc-js@0.6.9 as alternative to grpc

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#780]
@murgatroid99 believes he's continued to address some bugs in the `@grpc/grpc-js` libraries, based on logs we've been provided while debugging #770. 

We're holding off on making this a recommendation for all users, as we don't want to continue to create disruptions, and the `grpc` transport is working well.

However, if a few folks would like to pilot the latest changes to `@grpc/grpc-js`, we would greatly appreciate the help).

The latest version is `0.6.9`, after installing you should run `npm ls`, to make sure other dependencies have not pinned you on an older `@grpc/grpc-js`.

CC: @MichaelMarkieta, @Redgwell, @RaptDept, @xoraingroup

**Comment by Legogris** [comment]
@bcoe Motivation for closing this? `0.6.9`  Unfurtunately does not work for us. Just discovered the thread in https://github.com/googleapis/nodejs-pubsub/issues/770 now and will see if using `grpc` changes anything. Are there any known issues with `0.5.4`?
