### ISSUE TITLE
document grpc as alternative to @grpc/grpc-js for some workloads

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#781]
## The Problem

In #770 we continue to see a percentage of customers who bump into exceptional behavior with the `@grpc/grpc-js` library.

We haven't figured out a consistent reproduction of this issue, but most folks running into issues, have indicated in the thread that swapping in the [grpc](https://www.npmjs.com/package/grpc) dependency helps mitigate the issue.

## Document the grpc option

We should document in the README for `nodejs-pubsub`, that for folks running workloads that seem to run afoul of the default `@grpc/grpc-js` dependency, running the `C++` bindings is a viable alternative.

CC: @MatthieuLemoine @MichaelMarkieta

**Comment by andrewphamvk** [comment]
@bcoe I believe grpc has been deprecated and they are suggesting to use grpc-js..

https://www.npmjs.com/package/grpc
