### ISSUE TITLE
not all grpc libraries are consistently installing 0.6.9 dependency

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#790]
### Problem

Some dependencies still pin on older versions of `grpc`.

### Original Message

@ericpearson I've moved your comments here, since it's unrelated to the memory issues that are reported in #788 

An update here on our issues:

We use a ton of google libraries (stackdriver trace, debug, cloud tasks, pubsub etc). They all seem to share the same common dependecies what I did was go into the package-lock and update all of these to make sure they are pinned at grpc-js 0.6.9 and pinned google-gax which a lot of them depend on to 1.7.5.

This has resolved most of the issues we were having across multiple client libraries (this issue is not limited to pubsub). This was more effective than just pinning 0.6.9 in the package.json, which caused a ton of memory leaks and did not fix the timeout issues.

It seems to be that there are a lot of problems or conflicts with other google libraries using different versions of grpc-js and google-gax (this looks like the brains behind things). We also had issues where google-gax was upgraded, stopped working and when we attempted to downgrade again, completely killled our developers machines and pubsub wouldn't even work locally until their machines were rebooted. This seems similar to the issues observed when running in the cloud. Is some sort of weird state keeping going on in here? This would also maybe explain the versions conflicting with each other.

As of writing we are still seeing message timeouts but they are not on the scale as they were before but we are still impacted by this issue.

**Comment by bcoe** [comment]
@ericpearson would you be able to share the final `npm ls` after you performed surgery on `package-lock.json`, it sounds very odd to me that pinning to `0.6.9` would have different behavior than manually editing the `package-lock.json`, I'm curious what it looked like before and after.

**Comment by ericpearson** [comment]
the file is too large to post but it was mainly replacing everywhere "google-gax" was mentioned in the client lib deps like this:

`    "google-gax": {
      "version": "1.7.5",
      "resolved": "https://registry.npmjs.org/google-gax/-/google-gax-1.7.5.tgz",
      "integrity": "sha512-Tz2DFs8umzDcCBTi2W1cY4vEgAKaYRj70g6Hh/MiiZaJizrly7PgyxsIYUGi7sOpEuAbARQymYKvy5mNi8hEbg==",
      "requires": {
        "@grpc/grpc-js": "0.6.9",
        "@grpc/proto-loader": "^0.5.1",
        "abort-controller": "^3.0.0",
        "duplexify": "^3.6.0",
        "google-auth-library": "^5.0.0",
        "is-stream-ended": "^0.1.4",
        "lodash.at": "^4.6.0",
        "lodash.has": "^4.5.2",
        "node-fetch": "^2.6.0",
        "protobufjs": "^6.8.8",
        "retry-request": "^4.0.0",
        "semver": "^6.0.0",
        "walkdir": "^0.4.0"
      }`

**Comment by bcoe** [comment]
@ericpearson I'll spend the day today updating our dependencies to all explicitly pull in the known good version of gax.

Due to the nature of lock files, I think this still would require some manually fiddling, to make sure each library you use is on the latest patch release.

**Comment by ericpearson** [comment]
yeah I wouldn't call this even a fix it's more of a mitigation until someone can be done, at least there were improvements so I was hoping it would help solve what is going on

**Comment by bcoe** [comment]
@ericpearson could you explain the issues you're continuing to see in a new issue? Or I can open an issue.

If you're no longer seeing issues with 0.6.9, this is the version that folks will start getting when they install. If you're continuing to see issues with 0.6.9, it would be really helpful if we could describe and reproduce what you're seeing in an isolated manner.

**Comment by bcoe** [comment]
@ericpearson what I'm trying to separate out, is the issues related to there still being references to broken `@gprc/grpc-js` versions in your stack, which I believe will be addressed by us explicitly updating the version in all our libraries, and your final point:

> As of writing we are still seeing message timeouts but they are not on the scale as they were before but we are still impacted by this issue.

:point_up: this is disconcerting, and I believe is unrelated to `gax` version, so we should dig into independently.

Any chance we could run one of your nodes with debugging enabled?

**Comment by ericpearson** [comment]
it looks like this ended up not fixing our problems we are seeing memory leaks and timeouts again in our project in alignment with #791

**Comment by bcoe** [comment]
@ericpearson just moved your update to the #791 thread, apologize for the deleted message. So far we haven't had many additional folks report issues, so if you're willing, I'd like to help dig in to your specific issues with our engineers.

Even if we end up pinning `@google-cloud/pubsub` to `grpc`, it would be good to have forensic information to correct issues with `@grpc/grpc-js`.

**Comment by bcoe** [comment]
I've released versions now of all our libraries that rely on `@grpc/grpc-js`, such that they should force the `0.6.9` dependency.

This might not address all issues (_@ericpearson let's see if we can't get to the bottom of what the heck is happening to you) but this at least means it should be easier to ensure we're testing with a specific version of the library.
