### ISSUE TITLE
can publish but not receive from subscription on hosted environnement

### ISSUE THREAD

**Issue by ad34** [googleapis/nodejs-pubsub#797]
**Environment details**

Node.js version: v12.13.0
yarn version: 1.17.3
@google-cloud/pubsub": "^1.1.2"

**Steps to reproduce :** 

I have issues with google pubsub.

**On local workstation:**

I can publish & receive message from my subscription

**On Hosted K8S instance (corporate cloud, behind proxy)**

I can publish message but no message is received in the subscription

Any suggestion ? I configured http_proxy & https_proxy on the container but it doesnt solve the issue.

**Comment by bcoe** [comment]
@ad34 bind sharing a snippet of code demonstrating the publisher/subscriber you've created?

**Comment by feywind** [comment]
Closing this out as a stale issue, please re-open with sample code if possible, if this is still a problem.

May be related to this, re proxies: https://github.com/googleapis/nodejs-pubsub/issues/679
