### ISSUE TITLE
"Failed to connect before the deadline" errors being seen

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#818]
Since upgrading to the latest pubsub (`"@google-cloud/pubsub": "1.1.5"`) my node is still getting occasional errors from the underlying grpc library.  My app is using grpc-js@0.6.9:

$ npm ls | grep grpc-js
│ │ ├─┬ @grpc/grpc-js@0.6.9
 

It's not as bad as it was.  When I first upgraded to pubsub 1.x it simply didn't work at all, I'd get an error within a few seconds of the app starting and from then no messages would get delivered.

Now the problem is much less bad (my app is working), but I still see the following errors in my logs:

From `subscription.on(`error`, (err) => {` I see this:

    {"code":4,"details":"Failed to connect before the deadline","metadata":{"internalRepr":{},"options":{}}}

And in my logs I've also noticed these (excuse the formatting):

`Error: Failed to add metadata entry @���: Wed, 13 Nov 2019 07:13:16 GMT. Metadata key "@���" contains illegal characters at validate (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/metadata.js:35:15) at Metadata.add (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/metadata.js:87:9) at values.split.forEach.v (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/metadata.js:226:63) at Array.forEach (<anonymous>) at Object.keys.forEach.key (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/metadata.js:226:43) at Array.forEach (<anonymous>) at Function.fromHttp2Headers (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/metadata.js:200:30) at ClientHttp2Stream.stream.on (/home/nodeapp/apps/crypto-trader-prototype/shared-code/node_modules/@grpc/grpc-js/build/src/call-stream.js:211:56) at ClientHttp2Stream.emit (events.js:193:13) at emit (internal/http2/core.js:244:8) at processTicksAndRejections (internal/process/task_queues.js:81:17)`

.. but the two don't seem to be related.

I will start running with the debug flags enabled and report back

**Comment by bcoe** [comment]
as discussed [here](https://github.com/grpc/grpc-node/issues/1173) this is a known, non-fatal, warning coming out of `@grpc/grpc-js`; there's a hunch that it might actually be a problem with the HTTP2 implementation in Node.js.

**Comment by npomfret** [comment]
@bcoe including the "Failed to connect before the deadline" error?

It happened again today with the debug flags on:

```
F 2019-11-13T12:40:23.450999975Z {"code":4,"details":"Failed to connect before the deadline","metadata":{"internalRepr":{},"options":{}}} 
E 2019-11-13T12:40:23.450999975Z 2019-11-13T12:40:23.451Z | subchannel | 172.217.203.95:443 IDLE -> TRANSIENT_FAILURE 

```

**Comment by bcoe** [comment]
@callmehiphop can you speak to the above :point_up: , what situations can lead to this (I believe you were helping a user with a similar issue last week).

**Comment by callmehiphop** [comment]
@bcoe this is not the same issue, this looks like the same issue we were having with gRPC previously. That specific error occurs when a timeout occurs while waiting for the gRPC channel to get put into a ready state.

**Comment by bcoe** [comment]
@callmehiphop @alexander-fenster I was wondering if there's a parameter that can be tuned to increase the connect timeout.

@npomfret would you be able to provide the detailed debug output when this connection error occurs?

**Comment by callmehiphop** [comment]
@bcoe there is, but the default value is 5 minutes, so I'm not sure I think that increasing the timeout here is the right solution.

**Comment by npomfret** [comment]
> would you be able to provide the detailed debug output when this connection error occurs?

I have (above).  I tuned on `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG` as instructed.  The only output I saw in stackdriver that was at a similar time to the error occurring is:

`E 2019-11-13T12:40:23.450999975Z 2019-11-13T12:40:23.451Z | subchannel | 172.217.203.95:443 IDLE -> TRANSIENT_FAILURE 
`

All other logging at that time came from my app.

**Comment by bcoe** [comment]
@npomfret it sounds like your logs have given @murgatroid99 a hunch, as to what's happening. If you're open to it, we can try floating a patch to you early next week?

CC: @alexander-fenster who I've been working on a process with to facilitate releasing candidate versions to folks.

**Comment by npomfret** [comment]
@bcoe happy to help

**Comment by flunderpero** [comment]
Every time we see this error, the subscription stops working and no new messages are consumed until we restart the POD.

**Comment by bcoe** [comment]
@npomfret we've released `@google-cloud/pubsub@next` (`1.1.6-beta.0`), which has `@grpc/grpc-js@6.12.0`, there's a bug fix related to the error you reported.

If you have a chance, try it out? and we'll release more widely after the american holidays?

**Comment by npomfret** [comment]
I'll do a release today using @google-cloud/pubsub@next and run it for a few days

**Comment by npomfret** [comment]
I've had two of these in the past 24h with the new code:

`{"code":4,"details":"Failed to connect before the deadline","metadata":{"internalRepr":{},"options":{}}}`

My app is still running and receiving messages.

**Comment by npomfret** [comment]
[update] I've had zero errors since the 24th November.

**Comment by bcoe** [comment]
:+1: @npomfret that's great to hear, I'll close as soon as we've ensure that all of our libraries are on `@grpc/grpc-js@6.12.0`.

**Comment by npomfret** [comment]
Sadly I spoke too soon.  I upgraded from `"@google-cloud/pubsub": "^1.1.6-beta.0"` to `"@google-cloud/pubsub": "^1.1.6"` on the 6th November, and according to my logs the errors came back on the 6th November.  At the same time I also upgraded `@google-cloud/firestore` and `@google-cloud/logging` to the latest versions, perhaps the problem lies in them?  Currently I'm running with:

    "@google-cloud/firestore": "^2.6.1",
    "@google-cloud/logging": "6.0.0",
    "@google-cloud/logging-bunyan": "^2.0.2",
    "@google-cloud/pubsub": "^1.1.6",

**Comment by bcoe** [comment]
@murgatroid99 ☝️ does anything jump out at you in these logs, is there anything additional that @npomfret can provide to help you debug.

**Comment by npomfret** [comment]
I'm still getting these with the latest release, although it has to be said they do appear to be reducing in frequency (2 in the past 4 days, before it was more like 4 per day on my system).

Using...

    "@google-cloud/firestore": "^3.4.1",
    "@google-cloud/logging": "7.1.0",
    "@google-cloud/logging-bunyan": "^2.0.3",
    "@google-cloud/pubsub": "^1.4.1",

**Comment by npomfret** [comment]
I may be speaking too soon, but it looks like the latest release may have fixed this issue.

Recent releases seem to have steadily reduced the number of errors, but until recently I was getting one or two errors per day.  I've had zero for five days now.  The upgrade in question took my deps from:

    "@google-cloud/firestore": "^3.4.1",
    "@google-cloud/logging": "7.1.0",
    "@google-cloud/logging-bunyan": "^2.0.3",
    "@google-cloud/pubsub": "^1.4.1",

to ..

    "@google-cloud/firestore": "^3.5.0",
    "@google-cloud/logging": "7.1.0",
    "@google-cloud/logging-bunyan": "^2.0.3",
    "@google-cloud/pubsub": "^1.5.0",

**Comment by npomfret** [comment]
Closing this as no errors have occurred in my system for 9 days now.

**Comment by ZHamburglar** [comment]
`{"code":4,"details":"Failed to connect before the deadline","metadata":{"internalRepr":{},"options":{}},"level":"error","message":"GCP subscription errorFailed to connect to channel. Reason: Failed to connect before the deadline","stack":"Error: Failed to connect to channel. Reason: Failed to connect before the deadline\n    at MessageStream._waitForClientReady (/kw/node_modules/@google-cloud/pubsub/build/src/message-stream.js:318:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}`

Just wanted to jump in and say that I was having this issue previously as well. The issue arose from the GRPC Subscriber Client not being the same as ProjectID the Subscription Path. Once these two were set as the same, then the issue cleared up. In case anyone Googling this issue finds it, hopefully this can help them.
