### ISSUE TITLE
all builds are failing due to upstream dependency

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#842]
All builds are currently failing, e.g., #841, due to a breaking upstream dependency preventing TypeScript compilation.

```bash
node_modules/@sindresorhus/is/dist/index.d.ts:137:13 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.

137     [Symbol.observable](): ObservableLike;
                 ~~~~~~~~~~
```

> Computers are the Worst

  -- **Benjamin Coe**

**Comment by stephenplusplus** [comment]
Looks like #843 removed `is`, so that probably fixed this one.
