### ISSUE TITLE
Various problems seem to be happening in regards to grpc-js

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#868]
Over the course of the last few months, I've been tracking a number of issues where the answer was "roll back to an earlier version", and often when I ask people to try the newest version, but sub in the gRPC C++ bindings, it also works fine. (Or sometimes even better than the older version.)

There is something going on there that needs to be figured out. I'm making this to track related things independently of adjacent issues.

Potentially related:
https://github.com/googleapis/nodejs-pubsub/issues/679#issuecomment-511708702
https://github.com/googleapis/nodejs-pubsub/issues/788
https://github.com/googleapis/nodejs-pubsub/issues/789
https://github.com/googleapis/nodejs-pubsub/issues/818
https://github.com/googleapis/nodejs-pubsub/issues/825
https://github.com/googleapis/nodejs-pubsub/issues/850

**Comment by Ezard** [comment]
@feywind #770 is another one

**Comment by feywind** [comment]
After reading that issue, I think this may also fall into the bucket: https://github.com/googleapis/nodejs-pubsub/issues/866

**Comment by feywind** [comment]
Potentially related. https://github.com/googleapis/nodejs-pubsub/issues/885

**Comment by yagodorea** [comment]
I saw some bugs were resolved by the latest pubsub release. Is this gRPC issue one of them? If changing the default binding can solve it, can't we make it the default binding in the lib?

**Comment by ThomWright** [comment]
Could I add grpc/grpc-node#767 as another example of things going wrong because of `grpc-js`?

Thanks for looking into this, we've been stuck on an old version (`0.28.1`) for almost a year. It's a case of choosing which bugs are least problematic (we're suffering from #574), and at the moment I'm still convinced that upgrading to v1 is too risky.

**Comment by ctavan** [comment]
@ThomWright I can feel you 😉 Maybe to bolster you up a bit:

```
@google-cloud/pubsub@1.5.0
@grpc/grpc-js@0.6.18
```

is the first combination in months that really seems to work flawlessly for me, see https://github.com/googleapis/nodejs-pubsub/issues/850#issuecomment-593930469.

**Comment by feywind** [comment]
The sort of gestalt I'm seeing lately is that grpc-js is really a lot more stable for everyone, so I'm going to go ahead and close this out. Please feel free to add more comments with examples of problems, though. These examples are being fed into internal notes about pain points everyone has been experiencing.

I'm hoping to get us onto grpc-js 1.x soon, as it's no longer marked as a pre-release.
