### ISSUE TITLE
code example doesn't work

### ISSUE THREAD

**Issue by Zimovets** [googleapis/nodejs-pubsub#886]
![Аннотация 2020-02-12 181329](https://user-images.githubusercontent.com/28711392/74354287-cfe3dd80-4dc3-11ea-978f-c473f9dcd770.jpg)
![Аннотация 2020-02-12 181359](https://user-images.githubusercontent.com/28711392/74354292-d07c7400-4dc3-11ea-9913-b2efc90478ff.jpg)

I did all as mentioned in docs, I got JSON  with credentials, I set the environment variable for windows, but I got an error, recently I work with translate API and use there keyFileName parameter, I try this way, nothing
![image](https://user-images.githubusercontent.com/28711392/74354718-716b2f00-4dc4-11ea-9cd6-a58812a2342f.png)

**Comment by Zimovets** [comment]
was searching the solution and tried to install Google Clouse SDK, and got this

![image](https://user-images.githubusercontent.com/28711392/74355998-4eda1580-4dc6-11ea-84c3-a7ef65d8ed6e.png)

**Comment by feywind** [comment]
@Zimovets Thanks for the report. It sounds like there might be two separate issues here. I'll see if I can get the latter issue pushed to the gcloud installer folks. For the former, this is a total shot in the dark, but can you try removing the spaces from the filename of the json file?

**Comment by Zimovets** [comment]
> @Zimovets Thanks for the report. It sounds like there might be two separate issues here. I'll see if I can get the latter issue pushed to the gcloud installer folks. For the former, this is a total shot in the dark, but can you try removing the spaces from the filename of the json file?

I tried remove spaces, it didn't work, but this problem I solved using process.env

![image](https://user-images.githubusercontent.com/28711392/74418497-21867980-4e51-11ea-8d67-8773e44d6583.png)

**Comment by feywind** [comment]
@Zimovets Thanks for the update! Was the Powershell part of that in a sample/doc somewhere? If so, it sounds like we might need to update the docs, if the env setting didn't make it through.

**Comment by Zimovets** [comment]
setting up environment variable on windows didn't work for me, maybe I did something wrong

**Comment by feywind** [comment]
I did end up creating an internal bug for the installer issue. For the environment variable, there's also this comment from another project: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/117#issuecomment-221343452

It seems like it would be nice for the docs to explicitly call out how to do this stuff in Windows, so I'll pass that comment on to the writers as well.

I'm going to go ahead and close this out, but feel free to re-open if there are other concerns!
