### ISSUE TITLE
Notification delay time

### ISSUE THREAD

**Issue by Zimovets** [googleapis/nodejs-pubsub#888]
I was testing the library and can't understand one thing, how much time should pass after I changed or posted review and I will get the notification using subClient.pull, because, I changed something and get only 4 DEADLINE_EXCEEDED: Deadline exceeded , as I understand this error occurs if the queue is empty, but one time I got some message but unfortunately didn't check is it the message about review I have changed earlier or some another review was changed or added by some client

**Comment by feywind** [comment]
Generally the lag between posting to a topic and receiving on a subscription should be fairly short. I'm not as familiar with the queue empty behavior, but DEADLINE_EXCEEDED does kind of make sense if you're doing synchronous pull calls.

**Comment by feywind** [comment]
@Zimovets Are you still having trouble with this one? If so, can you go into a bit more detail on what you're doing in your publisher and subscriber, and what changed between it working and not working?

**Comment by stephenplusplus** [comment]
@Zimovets I'm going to close the issue, but please just let us know if there's more we can help with.
