### ISSUE TITLE
Synchronous Pull problem

### ISSUE THREAD

**Issue by Zimovets** [googleapis/nodejs-pubsub#891]
I run this code every minute to test API, what I expected, the first time I should get messages about the new and edited review, then for this subscriber, this messages will be acknowledged, and during next iteration I got nothig

![image](https://user-images.githubusercontent.com/28711392/74928865-008acf00-53e3-11ea-96f1-956789c0c7fb.png)

but every iteration I get the same message

![image](https://user-images.githubusercontent.com/28711392/74929071-742cdc00-53e3-11ea-91d5-1db2983a4be0.png)

I faced this issue today, for example, earlier acknowledge function work properly and I got message only one time
In the same time I try to get notification about another review adding/changing but get nothing, maybe this stuck message break the queue

**Comment by feywind** [comment]
Taking a closer look at this, it's possible that between the time you run the publisher and the subscriber, it's timing out and retrying delivery of the message, which would go into the same topic. Do you get similar results if you run them consecutively? Like:

```
./publisher && ./subscriber
```

(I mean, conceptually, because your files are no doubt different.)

I believe it's possible to adjust that ack timeout if that's the issue.

**Comment by Zimovets** [comment]
> Taking a closer look at this, it's possible that between the time you run the publisher and the subscriber, it's timing out and retrying delivery of the message, which would go into the same topic. Do you get similar results if you run them consecutively? Like:
> 
> ```
> ./publisher && ./subscriber
> ```
> 
> (I mean, conceptually, because your files are no doubt different.)
> 
> I believe it's possible to adjust that ack timeout if that's the issue.

can't understand what do you mean saying, run publisher and subscriber, as I understand we have publisher it is the service that create messages when review changed or created, then we created subscriber, then I posted or changed some review, using this subscriber profile (if we can call it like this) I tried to get messages about my actions, as I expected I should get message only one time then acknowledge the message and it should be deleted from queue for this subscriber, but i got the same message every time, it seems wrong,  today I riun the code to check will get I something or not, I got nothing although I know for sure that recently some review was changed, is it bug or I make something wrong

**Comment by feywind** [comment]
@Zimovets I was wondering if this is still a problem for you.

To clarify my last comment there, the default ack extension timeout is pretty short by default. So if you push a lot of messages onto a topic (which has a subscriber) and aren't reading them off that subscriber relatively quickly, they can end up being redelivered. So you might end up with N copies of the same message.

@kamalaboulhosn Double-checking, does my comment make sense in your understanding of the Pub/Sub service?

**Comment by feywind** [comment]
I'm going to go ahead and close this for now for lack of comments, but please feel free to comment/re-open if needed.
