### ISSUE TITLE
`maxRetries` field missing from ClientConfig type

### ISSUE THREAD

**Issue by nicknovitski** [googleapis/nodejs-pubsub#914]
The docs say I can specify `maxRetries` when instantiating a client, but typescript does not allow it.

#### Environment details

  - OS: macOS 10.15.3
  - Node.js version: 10.17.0
  - npm version: 6.11.3
  - `@google-cloud/pubsub` version: 1.6.0
  - typescript version: 3.7.2

#### Steps to reproduce

  1. create a new file containing `new Pubsub({projectId: "whatever", maxRetries: 5})`
  2. run `tsc --noEmit`

```
error TS2345: Argument of type '{ projectId: string; maxRetries: number; }' is not assignable to parameter of type 'ClientConfig'.
  Object literal may only specify known properties, and 'maxRetries' does not exist in type 'ClientConfig'.
```

**Comment by feywind** [comment]
Thanks for the report!

I'm not sure at a glance if this is a code or docs bug, but I'll have to look a bit more.

**Comment by feywind** [comment]
After looking at the code a bit, I'm going to guess this is a docs bug - I don't see maxRetries referenced anywhere else in the code besides those comments in pubsub.ts, so this is probably something that was removed earlier in the context of not supporting client-side delayed redelivery. I'm going to see if anyone else has thoughts on why this is in there.

**Comment by feywind** [comment]
The consensus seems to be that this library used to be based on `@google-cloud/common`, which did provide a maxRetries option (and thus Pub/Sub probably inherited it into its `ClientConfig`). But at this point, the only things between this library and the service endpoint are gax and grpc, which don't seem to support that concept of setting max retries.

So the docs do definitely need to be updated in the PubSub class.

What were you aiming to do by setting maxRetries? Maybe we can find another way to do it.

**Comment by nicknovitski** [comment]
I see now that there are other ways of doing this, through the gaxOptions arguments.
