### ISSUE TITLE
testing pubsub client on docker - Could not load the default credentials

### ISSUE THREAD

**Issue by oreporan** [googleapis/nodejs-pubsub#924]
After reading googleapis/google-cloud-node#2610

#### Environment details

  - OS: docker node:10...node:12
  - Node.js version: 10..12
  - google-cloud-node version: 0.28.1 and 1.6.0

#### Steps to reproduce

```ts
import {PubSub} from '@google-cloud/pubsub';

let pubsub: PubSub;

const getPubsub = () => {
    if (pubsub) return pubsub;
     pubsub = new PubSub({
            projectId: 'blackbox_tests',
        });
        return pubsub;
};

const getSubs = async () => {
  const [subscriptions] = await getPubsub().getSubscriptions();
}

```

Error:

```
blackbox-tests_1             |     Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
blackbox-tests_1             | 
blackbox-tests_1             |       at GoogleAuth. (node_modules/google-auth-library/build/src/auth/googleauth.js:168:23)
blackbox-tests_1             |       at fulfilled (node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
```

**Comment by feywind** [comment]
@oreporan Thanks for the report. A couple of questions:

1) Is the code snippet above part of a Cloud Function? I know some of our people were working on some issues related to being unable to get authentication info during client object creation, which I think should be covered by the way you wrote that, but I might run this by them to see if it looks at all familiar.

2) I'm assuming the credentials are being fed in by environment variable? I believe that it will need to find a key file by way of environment variables or an explicit parameter to the PubSub constructor.

**Comment by oreporan** [comment]
Hey

This is all part of a test environment.

I have a docker-compose setup, one of them being a container running the pubsub like so:

```
FROM google/cloud-sdk:alpine
RUN apk --update add openjdk7-jre
RUN gcloud components install --quiet beta pubsub-emulator
EXPOSE 8085
CMD ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port", "0.0.0.0:8085"]
```

Then I'm passing to my test runner (also on docker, running `node:12`) like so:

`PUBSUB_EMULATOR_HOST=pubsub:8085`

As my understanding no authentication is needed at this point

**Comment by feywind** [comment]
I want to say that there was an issue in the past with the library looking for credentials when it was running with the emulator. I don't see one open now. I'll try to give this a test in a bit.

**Comment by merlinnot** [comment]
There is a leaner version of a Docker image with PubSub Emulator, [Dott](https://ridedott.com/) maintains it: https://github.com/ridedott/pubsub-emulator-docker. You can also just take a look at the Dockerfile.

As for the configuration, here's a simple setup:

```ts
import * as pubSub from '@google-cloud/pubsub';
import { env } from 'process';

export const PUBSUB_SERVICE_HOSTNAME =
  typeof env.PUBSUB_SERVICE_HOSTNAME === 'string'
    ? env.PUBSUB_SERVICE_HOSTNAME
    : 'localhost';
export const PUBSUB_PORT =
  typeof env.PUBSUB_PORT === 'string'
    ? env.PUBSUB_PORT
    : '4502';

export class PubSub extends pubSub.PubSub {
  public constructor(options: ConstructorParameters<typeof pubSub.PubSub>[0]) {
    const address = `${PUBSUB_SERVICE_HOSTNAME}:${PUBSUB_PORT}`;

    super({ ...options, apiEndpoint: address, projectId: 'test' });
  }
}
```

Hope that will help.

**Comment by feywind** [comment]
Thanks @merlinnot!

**Comment by feywind** [comment]
@oreporan Is this still causing you troubles? I'm wondering if merlinnot's suggestion helped.

**Comment by feywind** [comment]
I'm going to go ahead and close this since it's been idle, but please feel free to comment/re-open if needed.
