### ISSUE TITLE
strange delays in message delivery to pubsub cloud function

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#959]
Not sure if this is a bug report or a support request, sorry!

I'm trying to understand some strange behaviour I'm seeing from time to time.  In summary, I am occasionally seeing messages that are just _sitting_ in the subscriber, for no apparent reason, until their acknowledgement deadline is reached, at which point they get delivered.  It doens't happen very often, but when it does it wreaks havoc on my system because it doesn't deal well with these huge (and unexpected) latencies.

Here is an example (apologies for using screen shots).

My GCE server sends messages and it does so, it them and [logs them](https://gist.github.com/npomfret/9a35b2ef316775c88ee95e6f730b6f56) along with their pubsub message id:
<img width="2513" alt="Screenshot 2020-04-13 at 00 13 34" src="https://user-images.githubusercontent.com/5489469/79113390-b980e080-7d78-11ea-8d0d-38b9543b7b5b.png">

The message in question (above) has id 1116943657777511, and was sent at 2020-04-12T22:58.20...Z.

The consumer of this message is a cloud function that has an acknowledgement deadline of 600s, and is deployed with the following command:

`gcloud beta functions deploy --quiet handleClientOrder --runtime nodejs10 --max-instances 10 --memory 512 --region europe-west1 --timeout 30 --trigger-topic client_orders --retry --set-env-vars=FUNCTION_REGION=europe-west1,GCLOUD_PROJECT=my-project-id,DEPLOYMENT_TIME=2020-04-12T11:21:56.603Z --entry-point app --allow-unauthenticated`

Typically, 99+% of messages are delivered within a few milliseconds if there is no backlog, which there rarely is.  The cloud function [also logs](https://gist.github.com/npomfret/b21e9524ed9e0373714159ff30fa8714) when it consumes the message:
<img width="2525" alt="Screenshot 2020-04-13 at 00 13 57" src="https://user-images.githubusercontent.com/5489469/79113997-0f09bd00-7d7a-11ea-9ffd-3afec90c13e8.png">

You can see that the message in question was consumed at 2020-04-12T23:08:21...Z, **exactly 10 minutes after it was sent**.  When I search Stackdriver for that message id, I can see that it was delivered once and only once.

I can see at the time there is no backlog in the subscriber, but I do see a large spike in the oldest unacked message, and I also see my unacked message count flat lining above zero for a period of time:
<img width="1487" alt="Screenshot 2020-04-13 at 00 13 06" src="https://user-images.githubusercontent.com/5489469/79114482-4c227f00-7d7b-11ea-8455-4305ba105b86.png">

It's as if the cloud function just decided not to consume this message until the last possible moment, possibly others too.

So my questions are: 

 * is this expected behaviour?
 * if so, what causes it?  is there a way to avoid it
 * if not, what can I do to investigate the cause?

**Comment by kamalaboulhosn** [comment]
From the Pub/Sub perspective, it looks like this message was delivered right after it was published, but received a 503 error. It was then redelivered 10 minutes later. The 503 error could cause backoff behavior in redeliveries, particularly if there were other 503 errors happening at the time. Therefore, it looks like something happened outside of Pub/Sub itself. It could be something with the Cloud Function or with the application code processing the message.

**Comment by npomfret** [comment]
Where do you see this 503 error?

**Comment by kamalaboulhosn** [comment]
You should be able to see it in the Stackdriver subscription/push_request_count metric (see[ pubsub metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-pubsub)), which can be broken down by response_class and response_code.

**Comment by npomfret** [comment]
I mean, where did YOU see the 503?  I didn't show any 503 in the data I posted in this ticket (did I?).  Do you have access to the data?

**Comment by kamalaboulhosn** [comment]
I was able to look at internal logs for the provided message ID.

**Comment by npomfret** [comment]
Oh, thanks for taking the time!

Thanks for pointing me at the metrics explorer.  I can't see the problem though.  I filtered the time range down to that in question (one hour either side) and I don't see any errors.

<img width="2135" alt="Screenshot 2020-04-14 at 18 14 28" src="https://user-images.githubusercontent.com/5489469/79253962-e8cc4600-7e7b-11ea-9a4f-e225bd483be9.png">

**Comment by kamalaboulhosn** [comment]
It could be a transient issue with Cloud Functions infrastructure, e.g., if a server restarts at the moment the message is sent.

**Comment by npomfret** [comment]
It's happening often enough that it's becoming quite a problem for me.  The messages doesn't get redelivered until the acknowledgment deadline, and that's set to a very high figure compared with the _normal_ latencies that my app expects.

Is there a workaround?

How do I file a bug report?

**Comment by kamalaboulhosn** [comment]
It could happen occasionally because acks and nacks (which is what the 503 is interpreted as) can be dropped under certain circumstances. We are aware that the frequency of these has increased and are working to mitigate it, though it will take a few weeks for such changes to roll out. If you want to file a bug report, it is best to create a support case via the [support page in the Cloud console](https://console.cloud.google.com/support).

**Comment by npomfret** [comment]
Thanks.

https://issuetracker.google.com/issues/154260226
