### ISSUE TITLE
max instance appears to get exceeded

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-pubsub#962]
I've been experiencing times where my app is crashing badly and I've noticed that my cloud functions are having trouble getting a db connection.  The metrics explorer shows that the number of instances is far greater than the number I've configured.  

Is this a known issue?  
Is there a way around it?

https://stackoverflow.com/questions/61206658/google-cloud-functions-maximum-function-instances-regularly-exceeded

**Comment by feywind** [comment]
@npomfret I'm going to guess that it's actually a GCF issue rather than a Pub/Sub issue, but we can leave this here to track it.

**Comment by npomfret** [comment]
Apologies, of course it is.  Can you advise me on where I can report it?

**Comment by feywind** [comment]
@npomfret Sorry for the late response. I think the answer is "it's complicated", because of some discussions we've been having around support channels, but let me see if I can find someone who can route it.

**Comment by feywind** [comment]
@npomfret I finally got this link from someone, you might want to try putting in a bug here?

https://issuetracker.google.com/issues?q=status:open%20componentid:187195&s=created_time:desc

**Comment by npomfret** [comment]
@feywind thanks, I already created an issue: https://issuetracker.google.com/issues/154260228

It appears that `maxInstances` isn't what it sounds like.  It's more of a guideline than a rule.

**Comment by feywind** [comment]
@npomfret I just wanted to double-check: does this need any more attention from the Pub/Sub client library side of things? If not, do you mind going ahead and closing? Thanks!
