### ISSUE TITLE
Pin dependencies to minor versions

### ISSUE THREAD

**Issue by kamalaboulhosn** [googleapis/nodejs-pubsub#969]
In an attempt to minimize issues caused by bad minor releases in dependencies and to make the rollback procedure for customers easier, we should pin dependencies to a minor version. When new minor versions are released, we should increase the pinned minor version to match the new version in a PR and release a new version of the Pub/Sub client library. If there is no new code in the library, but there are new dependency minor version increments, we should release a new version at least once a month. It is fine to release at a faster cadence than that if desired. This is how things work in the Java library and in fact, the minor version increase PRs are automatically generated. Perhaps thy could be auto generated in Node as well.

**Comment by feywind** [comment]
There's still some ongoing discussion about this internally, I think. The last I heard is that this may not be an issue with the Node libraries since most things are pretty properly semver versioned. I'll leave it open for now until we can get a complete resolution.

**Comment by kamalaboulhosn** [comment]
It looks like we are going to explore other options for dealing with this issue. Closing.
