### ISSUE TITLE
Re-export `ClientConfig` from pubsub.ts in package index.ts

### ISSUE THREAD

**Issue by chungnho** [googleapis/nodejs-pubsub#972]
**Is your feature request related to a problem? Please describe.**
I am using the PubSub package in a TS project. I would like to be able to import the `ClientConfig` interface/type that is defined here: https://github.com/googleapis/nodejs-pubsub/blob/966614d43db9bbffc6d821f713733168d3e1d67f/src/pubsub.ts#L63-L68

eg
```
import { PubSub, ClientConfig } from '@google-cloud/pubsub';

const myConfig: ClientConfig = { projectId: 'my-project-id' };
myConfig.keyFilename = 'my-key-filename.txt';

const client: PubSub = new PubSub(myConfig);
```

 **Describe the solution you'd like**
Include `ClientConfig` in the list of exports from `./pubsub` in the `index.ts` file: https://github.com/googleapis/nodejs-pubsub/blob/966614d43db9bbffc6d821f713733168d3e1d67f/src/index.ts#L94-L107

 **Describe alternatives you've considered**
Manually redefining the ClientConfig interface by looking at the source code, or a pared down version of it.

 **Additional context**
N/A

**Comment by feywind** [comment]
@chungnho This looks pretty straightforward, I'll put it in the queue. I suspect it got exported correctly in other libraries because (I think) the microgenerator would be responsible for that code.
