### ISSUE TITLE
Broken link for gaxOpts

### ISSUE THREAD

**Issue by mrdulin** [googleapis/nodejs-pubsub#990]
Broken link(404): https://googleapis.github.io/gax-nodejs/CallSettings.html

From the doc: https://googleapis.dev/nodejs/pubsub/latest/PubSub.html#createTopic

The description of `gaxOpts` option.

The correct link maybe http://googleapis.github.io/gax-nodejs/interfaces/CallOptions.html

**Comment by feywind** [comment]
@mrdulin Thanks for the report! I think a comment in there just needs an update.

**Comment by stephenplusplus** [comment]
Thanks @mrdulin! There were apparently a lot of broken links like that! PR sent: #999

**Comment by feywind** [comment]
This will go in with the 2.0 release.
